### ISSUE TITLE
error enabling Intel RealSense

### ISSUE THREAD

**Issue by kbonnen** [pupil-labs/pupil#1034]
I am running pupil capture from source on a Macbook early 2016, OSX 10.12.6.  Initially the world camera wasn't working so I followed the directions [(here)](https://docs.pupil-labs.com/#intel-realsense-3d) to enable the Intel RealSense 3D camera.  These built successfully but now when I run the pupil capture from source, I get this error:

KathrynsMacBook:pupil_src kathrynbonnen$ python3 main.py
MainProcess - [INFO] os_utils: Disabled idle sleep.
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/Users/kathrynbonnen/Documents/pupil/pupil_src/launchables/world.py", line 118, in world
    from plugin_manager import Plugin_Manager
  File "/Users/kathrynbonnen/Documents/pupil/pupil_src/shared_modules/plugin_manager.py", line 15, in <module>
    from video_capture import Base_Manager, Base_Source
  File "/Users/kathrynbonnen/Documents/pupil/pupil_src/shared_modules/video_capture/__init__.py", line 47, in <module>
    from .realsense_backend import Realsense_Source, Realsense_Manager
  File "/Users/kathrynbonnen/Documents/pupil/pupil_src/shared_modules/video_capture/realsense_backend.py", line 17, in <module>
    import pyrealsense as pyrs
  File "/usr/local/lib/python3.6/site-packages/pyrealsense/__init__.py", line 8, in <module>
    from .core import Service
  File "/usr/local/lib/python3.6/site-packages/pyrealsense/core.py", line 15, in <module>
    from .constants import RS_API_VERSION, rs_stream, rs_option, rs_format
  File "/usr/local/lib/python3.6/site-packages/pyrealsense/constants.py", line 30, in <module>
    with io.open(os.path.join(res_path, 'lrs_parsed_classes'), "rb") as ser2_classes:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/pyrealsense/lrs_parsed_classes'

MainProcess - [INFO] os_utils: Re-enabled idle sleep.

Any ideas?  Please let me know if additional information about my environment, etc would be helpful.

**Comment by papr** [comment]
This is a known issue. Please checkout this branch and reinstall pyrealsense: https://github.com/pupil-labs/pyrealsense/pull/7
