### ISSUE TITLE
Player:  Crash upon raw export: KeyError: 'timestamp'

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil#1046]
Note that I am using my own custom plugin that does add some data to g_pool.  Could this perhaps be the culprit?  If so, where shall I add the timestamp data?

Thanks
- gD

Process Export (pid: 4922) crashed with trace:
Traceback (most recent call last):
  File "/Users/counterfeit/NSAProject/PupilLabsSource/pupil/pupil_src/shared_modules/exporter.py", line 150, in export
    g_pool.fixations_by_frame = correlate_data(g_pool.fixations, g_pool.timestamps)
  File "/Users/counterfeit/NSAProject/PupilLabsSource/pupil/pupil_src/shared_modules/player_methods.py", line 48, in correlate_data
    data.sort(key=lambda d: d['timestamp'])
  File "/Users/counterfeit/NSAProject/PupilLabsSource/pupil/pupil_src/shared_modules/player_methods.py", line 48, in <lambda>
    data.sort(key=lambda d: d['timestamp'])
KeyError: 'timestamp'

player - [INFO] raw_data_exporter: Created 'gaze_positions.csv' file.

**Comment by papr** [comment]
It looks like your fixations do not have a `timestamp` key. It is required to correlate the fixation events with their respective world frames.

**Comment by mkassner** [comment]
I put this down to the custom plugin. How can we improve docs to help users add data to pupil player?
