### ISSUE TITLE
Issue running new Pupil Capture 1.3 bundle on OS X

### ISSUE THREAD

**Issue by hookdump** [pupil-labs/pupil#1053]
Opening the bundle for OS X immediately closes the app, before even creating its windows.

Manually launching the executable `pupil_capture` outputs the following:

```
➜  MacOS ./pupil_capture
MainProcess - [INFO] os_utils: Disabled idle sleep.
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "launchables/world.py", line 118, in world
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "/Users/mkassner/Envs/py3/lib/python3.6/site-packages/PyInstaller-3.4.dev0+g133d181-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "shared_modules/plugin_manager.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "/Users/mkassner/Envs/py3/lib/python3.6/site-packages/PyInstaller-3.4.dev0+g133d181-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "shared_modules/video_capture/__init__.py", line 47, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "/Users/mkassner/Envs/py3/lib/python3.6/site-packages/PyInstaller-3.4.dev0+g133d181-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "shared_modules/video_capture/realsense_backend.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "/Users/mkassner/Envs/py3/lib/python3.6/site-packages/PyInstaller-3.4.dev0+g133d181-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/pyrealsense-2.2-py3.6-macosx-10.9-x86_64.egg/pyrealsense/__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "/Users/mkassner/Envs/py3/lib/python3.6/site-packages/PyInstaller-3.4.dev0+g133d181-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/pyrealsense-2.2-py3.6-macosx-10.9-x86_64.egg/pyrealsense/core.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "/Users/mkassner/Envs/py3/lib/python3.6/site-packages/PyInstaller-3.4.dev0+g133d181-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/pyrealsense-2.2-py3.6-macosx-10.9-x86_64.egg/pyrealsense/constants.py", line 33, in <module>
Exception: librealsense/rs.h header not found at /usr/local/include/librealsense/rs.h

MainProcess - [INFO] os_utils: Re-enabled idle sleep.
```

This is on `OS X 10.12.3`

Hardware:

```
    USB 3.0 Bus:

      Host Controller Driver: AppleUSBXHCIPPT
      PCI Device ID: 0x1e31
      PCI Revision ID: 0x0004
      PCI Vendor ID: 0x8086

        Pupil Cam1 ID0:

          Product ID: 0x9230
          Vendor ID: 0x05a3  (V Automation Inc.)
          Version: 1.00
          Speed: Up to 480 Mb/sec
          Manufacturer: Pupil Cam1 ID0
          Location ID: 0x14200000 / 4
          Current Available (mA): 500
          Current Required (mA): 500
          Extra Operating Current (mA): 0

        HD Webcam C525:

          Product ID: 0x0826
          Vendor ID: 0x046d  (Logitech Inc.)
          Version: 0.10
          Serial Number: 64A92C50
          Speed: Up to 480 Mb/sec
          Location ID: 0x14100000 / 3
          Current Available (mA): 500
          Current Required (mA): 500
          Extra Operating Current (mA): 0
```

Some extra information:
 - Pupil Capture 1.2 work just fine on my system.
 - Pupil Service 1.3 and Pupil Player 1.3 seem to work fine. The only issue is with Pupil Capture 1.3.

**Comment by mkassner** [comment]
@hookdump  I think I fixed this. Can you re-download and try again?

**Comment by mkassner** [comment]
fixed
