### ISSUE TITLE
Crash on manual marker calibration

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#106]
```bash
WORLD Process [WARNING] audio : could not say: '%s'. Please install spd-say if you want Pupil capture to speek to you.
Traceback (most recent call last):
  File "/home/rafael/cpicanco/pupil/pupil_src/capture/main.py", line 154, in <module>
    main()
  File "/home/rafael/cpicanco/pupil/pupil_src/capture/main.py", line 145, in main
    world(g_pool,world_src,world_size)
  File "/home/rafael/cpicanco/pupil/pupil_src/capture/world.py", line 320, in world
    p.update(frame,events)
  File "/home/rafael/cpicanco/pupil/pupil_src/capture/calibration_routines/manual_marker_calibration.py", line 205, in update
    audio.beep()
  File "/home/rafael/cpicanco/pupil/pupil_src/shared_modules/audio/__init__.py", line 39, in beep
    sp.Popen(["paplay", "/usr/share/sounds/ubuntu/stereo/message.ogg"])
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by mkassner** [comment]
Thanks for catching that. I ll fix this bug. We are using system sounds that come with MacOS/Ubunut only. Thats a problem.

**Comment by mkassner** [comment]
should not crash anymore. Custom sounds for Pupil could be nice, but thats for a different issue.
