### ISSUE TITLE
Frame Publisher crashes when Fake Capture for World Video is used

### ISSUE THREAD

**Issue by mattem86** [pupil-labs/pupil#1083]
2018-02-19 11:33:17,080 - world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "launchables/world.py", line 467, in world
  File "shared_modules/zmq_tools.py", line 140, in send
  File "zmq/backend/cython/socket.pyx", line 636, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:7314)
  File "zmq/backend/cython/socket.pyx", line 683, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:7057)
  File "zmq/backend/cython/socket.pyx", line 188, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2824)
  File "zmq/utils/buffers.pxd", line 200, in zmq.utils.buffers.asbuffer_r (zmq/backend/cython/socket.c:8885)
  File "zmq/utils/buffers.pxd", line 151, in zmq.utils.buffers.asbuffer (zmq/backend/cython/socket.c:8211)
TypeError: None does not provide a buffer interface.

This issue is on Windows and Mac, Pupil Version 1.3 and 1.4 affected (lower not tested)

**Comment by papr** [comment]
Thank you for the report. The issue is that the default frame publisher format is set to jpeg and Fake_Source does not support yuv or jpeg buffers. For now, there two possible work-arounds:
1. Start the frame publisher plugin and set its format to `BGR` before activating the Fake Capture.
2. Start the frame publisher plugin via a the `open_plugin` and pass the `BGR` format as an argument.

The frame publisher has logic in place to recognize unsupported formats. The problem is that did not trigger in the case of Fake Capture.
