### ISSUE TITLE
ZeroDivisionError when minimizing a window

### ISSUE THREAD

**Issue by cboulay** [pupil-labs/pupil#1087]
Running pupil capture from source on Win10 x64. When I minimize a window the console spits out the following:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "C:\work\pupil\pupil_src\launchables\eye.py", line 176, in on_resize
    hdpi_factor = float(glfw.glfwGetFramebufferSize(window)[0] / glfw.glfwGetWindowSize(window)[0])
ZeroDivisionError: division by zero
```

**Comment by cboulay** [comment]
Just for completeness, here is the same error for the world window:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "C:\work\pupil\pupil_src\launchables\world.py", line 223, in on_resize
    hdpi_factor = float(glfw.glfwGetFramebufferSize(window)[0] / glfw.glfwGetWindowSize(window)[0])
ZeroDivisionError: division by zero
```
