### ISSUE TITLE
Current brew boost-python version is incompatible on macos

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#1089]
`brew` changed the `boost-python` formula to deprecate the `--with-python3` option and only provides bottled versions for python2 as it seems. 

```
player - [ERROR] launchables.player: Process Player crashed with trace:
Traceback (most recent call last):
  File "/Users/pabloprietz/work/pupil/pupil_src/launchables/player.py", line 82, in player
    from plugin_manager import Plugin_Manager
  File "/Users/pabloprietz/work/pupil/pupil_src/shared_modules/plugin_manager.py", line 14, in <module>
    from calibration_routines import Calibration_Plugin, Gaze_Mapping_Plugin
  File "/Users/pabloprietz/work/pupil/pupil_src/shared_modules/calibration_routines/__init__.py", line 13, in <module>
    from . screen_marker_calibration import Screen_Marker_Calibration
  File "/Users/pabloprietz/work/pupil/pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py", line 28, in <module>
    from . finish_calibration import finish_calibration
  File "/Users/pabloprietz/work/pupil/pupil_src/shared_modules/calibration_routines/finish_calibration.py", line 19, in <module>
    from . optimization_calibration import bundle_adjust_calibration
  File "/Users/pabloprietz/work/pupil/pupil_src/shared_modules/calibration_routines/optimization_calibration/__init__.py", line 19, in <module>
    from . calibration_methods import bundle_adjust_calibration
ImportError: dlopen(/Users/pabloprietz/work/pupil/pupil_src/shared_modules/calibration_routines/optimization_calibration/calibration_methods.cpython-36m-darwin.so, 2): Symbol not found: _PyClass_Type
  Referenced from: /usr/local/opt/boost-python/lib/libboost_python.dylib
  Expected in: flat namespace
 in /usr/local/opt/boost-python/lib/libboost_python.dylib
```

**Comment by cboulay** [comment]
As of 11 days ago, there's a [boost-python3 recipe](https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost-python3.rb). [PR](https://github.com/Homebrew/homebrew-core/pull/23322).

**Comment by papr** [comment]
Thank you so much! I will try this out and change the docs accordingly.
