### ISSUE TITLE
Crash on restoring minimized pupil_capture window (Win10)

### ISSUE THREAD

**Issue by cboulay** [pupil-labs/pupil#1097]
Running pupil_capture from source.

If I minimize the Pupil Capture World window, then restore it, it crashes with the following error in console:

```
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "C:\work\pupil\pupil_src\launchables\world.py", line 473, in world
    gl_utils.glViewport(0, 0, *camera_render_size)
  File "C:\Users\Chad\AppData\Local\conda\conda\envs\pupil\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'invalid value',
	baseOperation = glViewport,
	cArguments = (0, 0, 1280, 720)
)

eye0 - [INFO] launchables.eye: Process shutting down.
```

**Comment by papr** [comment]
Fixed with https://github.com/pupil-labs/pupil/pull/1104
