### ISSUE TITLE
Pupil Player: Crash if removing a surface

### ISSUE THREAD

**Issue by sfeu** [pupil-labs/pupil#1106]
If i add a couple of surfaces and thereafter try to delete one of them using the trashbin
symbol in the surface menu i always get these crashes:

player - [ERROR] launchables.player: Process Player crashed with trace:
Traceback (most recent call last):
  File "launchables\player.py", line 479, in player
  File "pyglui\ui.pyx", line 195, in pyglui.ui.UI.update
  File "pyglui\ui.pyx", line 137, in pyglui.ui.UI.handle_input
  File "pyglui\menus.pxi", line 625, in pyglui.ui.Scrolling_Menu.handle_input
  File "pyglui\menus.pxi", line 643, in pyglui.ui.Scrolling_Menu.handle_input
  File "pyglui\menus.pxi", line 418, in pyglui.ui.Growing_Menu.handle_input
  File "pyglui\menus.pxi", line 430, in pyglui.ui.Growing_Menu.handle_input
  File "pyglui\menus.pxi", line 418, in pyglui.ui.Growing_Menu.handle_input
  File "pyglui\menus.pxi", line 430, in pyglui.ui.Growing_Menu.handle_input
  File "pyglui\ui_elements.pxi", line 971, in pyglui.ui.Button.handle_input
  File "pyglui\ui_elements.pxi", line 983, in pyglui.ui.Button.handle_input
  File "shared_modules\offline_surface_tracker.py", line 162, in <lambda>
  File "shared_modules\offline_surface_tracker.py", line 190, in remove_surface
AttributeError: attribute 'height' of 'pyglui.ui.UI_element' objects is not writ
able

player - [INFO] launchables.player: Process shutting down.

**Comment by papr** [comment]
Fixed with 87669ce64d8b468f190f5b4f774399acba73e138
