### ISSUE TITLE
Audio stream clock Issue

### ISSUE THREAD

**Issue by sotodea** [pupil-labs/pupil#1139]
Hello all, 
I have been having trouble getting Audio.MP4 files from pupil Capture. 

When running PupilCapture v1.16 on Ubuntu 16.04 (from bundle) the Audio plugin does not recognize any on the microphones. 

I down graded to v.1.15 of Capture. Here it does recognize the microphones, but does not generate an Audio.MP4 file when recording . 

When running on Windows machine Capture v1.16, the Audio plugin does recognize all microphones (I tried several), however, when clicking the desired one, the tab defaults to 'no audio' and the message "World: could not identify audio stream clock'' appears on the visualization of the World cam. No audio.mp4 file is created here either.

Has anyone resolved this issue? Thank you all 
Cheers
Vicente

**Comment by fneitzel** [comment]
Recording from Pupil mobil

```
pupil_player
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [ERROR] player_methods: No valid dir supplied
player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
player - [INFO] launchables.player: Starting new session with '/media/user/data/Pupil/20180410151335652'
player - [INFO] player_methods: Updating meta info
player - [INFO] player_methods: Checking for world-less recording
player - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
player - [INFO] launchables.player: Application Version: 1.6.13
player - [INFO] launchables.player: System Info: User: neitzel, Platform: Linux, Machine: name, Release: 4.13.0-38-generic, Version: #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018
player - [INFO] camera_models: Previously recorded calibration found and loaded!
player - [INFO] launchables.player: Session setting are a different version of this app. I will not use those.
ALSA lib confmisc.c:674:(snd_determine_driver) could not open control for card 0
ALSA lib conf.c:3328:(snd_config_hooks_call) function snd_config_hook_load_for_all_cards returned error: Invalid argument
ALSA lib confmisc.c:674:(snd_determine_driver) could not open control for card 0
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_card_driver returned error: Invalid argument
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_concat returned error: Invalid argument
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_refer returned error: Invalid argument
ALSA lib conf.c:4727:(snd_config_expand) Evaluate error: Invalid argument
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.default
ALSA lib confmisc.c:674:(snd_determine_driver) could not open control for card 0
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_card_driver returned error: Invalid argument
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_concat returned error: Invalid argument
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_refer returned error: Invalid argument
ALSA lib conf.c:4727:(snd_config_expand) Evaluate error: Invalid argument
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:674:(snd_determine_driver) could not open control for card 0
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_card_driver returned error: Invalid argument
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_concat returned error: Invalid argument
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_refer returned error: Invalid argument
ALSA lib conf.c:4727:(snd_config_expand) Evaluate error: Invalid argument
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM dmix
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
player - [INFO] audio_playback: Reopening audio stream...
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection terminated

Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->playback, alsaApi, outParams, StreamDirection_Out, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2175
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2840
player - [ERROR] launchables.player: Process Player crashed with trace:
Traceback (most recent call last):
  File "launchables/player.py", line 469, in player
  File "shared_modules/audio_playback.py", line 198, in recent_events
  File "pyaudio.py", line 750, in open
  File "pyaudio.py", line 441, in __init__
OSError: [Errno -9993] Illegal combination of I/O devices

player - [INFO] launchables.player: Process shutting down.
```

**Comment by pointcontrols** [comment]
@fneitzel have you tried this on a different machine (different integrated audio type)? It appears like a libportaudio problem.

**Comment by pointcontrols** [comment]
@sotodea Can you please share capture.log of the session that produced the crashing recording?
