### ISSUE TITLE
Crash: Pupil mobil import issue - missing eye video - missing visualisations? | Pupil player

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#1149]
I have trouble offline calibrating pupil mobile videos:

![screenshot from 2018-04-10 16-36-36](https://user-images.githubusercontent.com/10213803/38563551-6b829758-3cdd-11e8-876a-f43f4bd3afcc.png)

- Detection will always stop
- world camera has recording gaps
- recorded fps of eye1 and eye0 don't show up

I recorded a few videos and issues seem persistent - always noticable gaps within the recorded fps.

```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [ERROR] player_methods: No valid dir supplied
player - [INFO] launchables.player: Starting new session with '/media/user/data/Pupil/re/20180410161545802'
player - [INFO] player_methods: Updating meta info
player - [INFO] player_methods: Converting Pupil Mobile recording to v0.9.4 format
player - [INFO] player_methods: Creating "eye0_timestamps.npy"
player - [INFO] player_methods: Renaming "Pupil Cam2 ID0.mjpeg" to "eye0.mjpeg"
player - [WARNING] libav.mjpeg: Format mjpeg detected only with low score of 1, misdetection possible!
player - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID2 at resolution (1280, 720)
player - [INFO] camera_models: Loading pre-recorded calibration
player - [INFO] camera_models: Calibration for camera world at resolution (1280, 720) saved to /media/neitzel/data/Pupil/google/re/20180410161545802/world.intrinsics
player - [INFO] player_methods: Creating "world_timestamps.npy"
player - [INFO] player_methods: Renaming "Pupil Cam1 ID2.mjpeg" to "world.mjpeg"
player - [INFO] player_methods: Creating "eye1_timestamps.npy"
player - [INFO] player_methods: Renaming "Pupil Cam2 ID1.mjpeg" to "eye1.mjpeg"
player - [INFO] player_methods: Creating "pupil_data"
player - [INFO] player_methods: Updating meta info
player - [INFO] player_methods: Updating recording from v0.9.4 to v0.9.13
player - [INFO] player_methods: Updating meta info
player - [INFO] player_methods: Updating recording from v0.9.13 to v0.9.15
player - [INFO] player_methods: Updating meta info
player - [INFO] player_methods: Updating recording from v0.9.15 to v1.3
player - [INFO] player_methods: Updating meta info
player - [INFO] player_methods: Updating recording from v1.3 to v1.4
player - [INFO] player_methods: Updating meta info
player - [INFO] player_methods: Checking for world-less recording
player - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
player - [INFO] launchables.player: Application Version: 1.6.13
player - [INFO] launchables.player: System Info: User: user, Platform: Linux, Machine: name
, Release: 4.13.0-38-generic, Version: #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018
player - [INFO] camera_models: Previously recorded calibration found and loaded!
eye0 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
eye1 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
eye0 - [INFO] launchables.eye: Session setting are from a different version of this app. I will not use those.
eye0 - [INFO] camera_models: No user calibration found for camera eye0 at resolution (192, 192)
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
eye1 - [INFO] camera_models: No user calibration found for camera eye1 at resolution (192, 192)
eye1 - [INFO] camera_models: No pre-recorded calibration available
eye1 - [WARNING] camera_models: Loading dummy calibration
eye0 - [WARNING] launchables.eye: Process started.
eye1 - [WARNING] launchables.eye: Process started.
eye0 - [ERROR] launchables.eye: Process Eye0 crashed with trace:
Traceback (most recent call last):
  File "launchables/eye.py", line 524, in eye
  File "shared_modules/video_capture/file_backend.py", line 165, in run_func
  File "shared_modules/video_capture/file_backend.py", line 296, in recent_events_own_timing
  File "shared_modules/video_capture/file_backend.py", line 165, in run_func
  File "shared_modules/video_capture/file_backend.py", line 231, in get_frame
  File "shared_modules/video_capture/file_backend.py", line 212, in _next_frame
  File "av/packet.pyx", line 38, in av.packet.Packet.decode (src/av/packet.c:2582)
  File "av/stream.pyx", line 203, in av.stream.Stream.decode (src/av/stream.c:4561)
  File "av/video/stream.pyx", line 51, in av.video.stream.VideoStream._decode_one (src/av/video/stream.c:2059)
  File "av/utils.pyx", line 78, in av.utils.err_check (src/av/utils.c:1742)
av.AVError: [Errno 1] Operation not permitted

eye1 - [ERROR] libav.mjpeg: dqt: invalid precision
eye1 - [ERROR] launchables.eye: Process Eye1 crashed with trace:
Traceback (most recent call last):
  File "launchables/eye.py", line 524, in eye
  File "shared_modules/video_capture/file_backend.py", line 165, in run_func
  File "shared_modules/video_capture/file_backend.py", line 296, in recent_events_own_timing
  File "shared_modules/video_capture/file_backend.py", line 165, in run_func
  File "shared_modules/video_capture/file_backend.py", line 231, in get_frame
  File "shared_modules/video_capture/file_backend.py", line 212, in _next_frame
  File "av/packet.pyx", line 38, in av.packet.Packet.decode (src/av/packet.c:2582)
  File "av/stream.pyx", line 203, in av.stream.Stream.decode (src/av/stream.c:4561)
  File "av/video/stream.pyx", line 51, in av.video.stream.VideoStream._decode_one (src/av/video/stream.c:2059)
  File "av/utils.pyx", line 78, in av.utils.err_check (src/av/utils.c:1742)
av.AVError: [Errno 1] Operation not permitted
```

**Comment by mkassner** [comment]
This was due to a Slow SD card or other phone issue. 

I ll close this.

**Comment by fneitzel** [comment]
+ old Pupil Mobile version 0.19.1
