### ISSUE TITLE
Player crahes

### ISSUE THREAD

**Issue by alexander-pastukhov** [pupil-labs/pupil#1180]
We have made a recording using 1.6.11 pupil-capture using a Windows 7 x64 machine. Although the pupil player works on that machine, same recording crashes the pupil-player on a Win10 x64 machine and Ubuntu 16.04. 

--- info.csv ---
key,value
Recording Name,STEM
Start Date,08.05.2018
Start Time,16:26:24
Start Time (System),1525789584.199259
Start Time (Synced),946.988856
Duration Time,00:03:03
World Camera Frames,5087
World Camera Resolution,1280x720
Capture Software Version,1.6.11
Data Format Version,1.6.11
System Info,"User: Juwis, Platform: Windows, Machine: MR-11-2013-14-N, Release: 7, Version: 6.1.7601"

--- player.log from Win10 x64, pupil-player, pupil-player 1.7-42 ---
2018-05-14 09:48:36,405 - MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
2018-05-14 09:48:37,055 - player - [ERROR] player_methods: No valid dir supplied
2018-05-14 09:48:37,055 - player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
2018-05-14 09:49:07,845 - player - [INFO] launchables.player: Starting new session with 'E:\Bamberg\CCC\Stem2-Results\Session B\VP5\Pupil lab\001'
2018-05-14 09:49:07,861 - player - [INFO] player_methods: Updating meta info
2018-05-14 09:49:08,155 - player - [INFO] player_methods: Checking for world-less recording
2018-05-14 09:49:08,664 - player - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
2018-05-14 09:49:08,970 - player - [INFO] launchables.player: Application Version: 1.6.11
2018-05-14 09:49:08,970 - player - [INFO] launchables.player: System Info: User: sasha, Platform: Windows, Machine: MR-11-2014-07-N, Release: 10, Version: 10.0.14393
2018-05-14 09:49:08,986 - player - [INFO] camera_models: Previously recorded calibration found and loaded!
2018-05-14 09:49:08,987 - player - [INFO] launchables.player: Session setting are a different version of this app. I will not use those.
2018-05-14 09:49:10,567 - player - [INFO] file_methods: E:\Bamberg\CCC\Stem2-Results\Session B\VP5\Pupil lab\001\pupil_data has a deprecated format: Will be updated on save
2018-05-14 09:49:10,575 - player - [ERROR] launchables.player: Process Player crashed with trace:
Traceback (most recent call last):
  File "shared_modules\file_methods.py", line 58, in load_object
  File "msgpack/_unpacker.pyx", line 164, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:2622)
  File "msgpack/_unpacker.pyx", line 139, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2068)
TypeError: unhashable type: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "launchables\player.py", line 246, in player
  File "shared_modules\file_methods.py", line 64, in load_object
  File "shared_modules\file_methods.py", line 48, in _load_object_legacy
ValueError: unregistered extension code 1886744751

2018-05-14 09:49:10,575 - player - [INFO] launchables.player: Process shutting down.

--- player.log Ubuntu 16.04 on a virtual machine, pupil-player 1.7-42 ---
2018-05-14 09:35:25,683 - MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
2018-05-14 09:35:27,336 - player - [ERROR] player_methods: No valid dir supplied (/opt/pupil_player/pupil_player)
2018-05-14 09:35:27,343 - player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
2018-05-14 10:01:34,170 - player - [INFO] launchables.player: Starting new session with '/home/sasha/stem2-results/001'
2018-05-14 10:01:34,181 - player - [INFO] player_methods: Updating meta info
2018-05-14 10:01:34,182 - player - [INFO] player_methods: Checking for world-less recording
2018-05-14 10:01:34,614 - player - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
2018-05-14 10:01:34,880 - player - [INFO] launchables.player: Application Version: 1.7.42
2018-05-14 10:01:34,881 - player - [INFO] launchables.player: System Info: User: sasha, Platform: Linux, Machine: sasha-VirtualBox, Release: 4.13.0-41-generic, Version: #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018
2018-05-14 10:01:34,887 - player - [DEBUG] video_capture.file_backend: loaded videostream: <av.VideoStream #0 mjpeg, yuvj422p 1280x720 at 0x7f888a101278>
2018-05-14 10:01:34,887 - player - [DEBUG] video_capture.file_backend: No audiostream found in media container
2018-05-14 10:01:34,893 - player - [DEBUG] video_capture.file_backend: Auto loaded 5087 timestamps from /home/sasha/stem2-results/001/world_timestamps.npy
2018-05-14 10:01:34,904 - player - [INFO] camera_models: Previously recorded calibration found and loaded!
2018-05-14 10:01:34,904 - player - [INFO] launchables.player: Session setting are a different version of this app. I will not use those.
2018-05-14 10:01:35,788 - player - [INFO] file_methods: /home/sasha/stem2-results/001/pupil_data has a deprecated format: Will be updated on save
2018-05-14 10:01:35,791 - player - [ERROR] launchables.player: Process Player crashed with trace:
Traceback (most recent call last):
  File "shared_modules/file_methods.py", line 58, in load_object
  File "msgpack/_unpacker.pyx", line 164, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:2622)
  File "msgpack/_unpacker.pyx", line 139, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2068)
TypeError: unhashable type: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "launchables/player.py", line 246, in player
  File "shared_modules/file_methods.py", line 64, in load_object
  File "shared_modules/file_methods.py", line 48, in _load_object_legacy
ValueError: unregistered extension code 1886744751

2018-05-14 10:01:35,793 - player - [INFO] launchables.player: Process shutting down.

**Comment by papr** [comment]
Please send the recording to data@pupil-labs.com such that I can investigate this issue.

**Comment by mkassner** [comment]
stale. Closing...
