### ISSUE TITLE
Open GLError

### ISSUE THREAD

**Issue by emolyzr** [pupil-labs/pupil#1185]
Sometimes I encounter this unsystematic error and pupil player stops. Next time it will work again, but it's a pain, because all calculations are very slow. Is this a WIN 10 Error only?

2018-05-17 22:23:33,302 - MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
2018-05-17 22:23:33,871 - player - [ERROR] player_methods: No valid dir supplied (C:\Program Files\pupil_player_windows_x64_v1.7-42-7ce62c8\pupil_player.exe)
2018-05-17 22:23:36,831 - player - [INFO] launchables.player: Starting new session with 'C:\Users\myPC\Desktop\TEST DATA DROP\DOUBLE REC\NO INTERRUPTION LOCAL REC'
2018-05-17 22:23:36,833 - player - [INFO] player_methods: Updating meta info
2018-05-17 22:23:36,836 - player - [INFO] player_methods: Converting Pupil Mobile recording to v0.9.4 format
2018-05-17 22:23:36,837 - player - [INFO] player_methods: Creating "audio_timestamps.npy"
2018-05-17 22:23:36,851 - player - [INFO] player_methods: Renaming "audio_00010000.mp4" to "audio.mp4"
2018-05-17 22:23:36,861 - player - [WARNING] libav.mov,mp4,m4a,3gp,3g2,mj2: sample aspect ratio already set to 1:1, ignoring 'pasp' atom (65536:65536)
2018-05-17 22:23:36,862 - player - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID2 at resolution (1280, 720)
2018-05-17 22:23:36,863 - player - [INFO] camera_models: Loading pre-recorded calibration
2018-05-17 22:23:36,864 - player - [INFO] camera_models: Calibration for camera world at resolution (1280, 720) saved to C:\Users\myPC\Desktop\TEST DATA DROP\DOUBLE REC\NO INTERRUPTION LOCAL REC\world.intrinsics
2018-05-17 22:23:36,865 - player - [INFO] player_methods: Creating "world_timestamps.npy"
2018-05-17 22:23:36,892 - player - [INFO] player_methods: Renaming "Pupil Cam1 ID2.mp4" to "world.mp4"
2018-05-17 22:23:36,893 - player - [INFO] player_methods: Creating "eye0_timestamps.npy"
2018-05-17 22:23:36,907 - player - [INFO] player_methods: Renaming "Pupil Cam2 ID0.mjpeg" to "eye0.mjpeg"
2018-05-17 22:23:36,908 - player - [INFO] player_methods: Creating "eye1_timestamps.npy"
2018-05-17 22:23:36,914 - player - [INFO] player_methods: Renaming "Pupil Cam2 ID1.mjpeg" to "eye1.mjpeg"
2018-05-17 22:23:36,915 - player - [INFO] player_methods: Creating "pupil_data"
2018-05-17 22:23:36,917 - player - [INFO] player_methods: Updating meta info
2018-05-17 22:23:36,924 - player - [INFO] player_methods: Updating recording from v0.9.4 to v0.9.13
2018-05-17 22:23:36,925 - player - [INFO] player_methods: Updating meta info
2018-05-17 22:23:36,929 - player - [INFO] player_methods: Updating recording from v0.9.13 to v0.9.15
2018-05-17 22:23:36,930 - player - [INFO] player_methods: Updating meta info
2018-05-17 22:23:36,938 - player - [INFO] player_methods: Updating recording from v0.9.15 to v1.3
2018-05-17 22:23:36,941 - player - [INFO] player_methods: Updating meta info
2018-05-17 22:23:36,948 - player - [INFO] player_methods: Updating recording from v1.3 to v1.4
2018-05-17 22:23:36,949 - player - [INFO] player_methods: Updating meta info
2018-05-17 22:23:36,954 - player - [INFO] player_methods: Checking for world-less recording
2018-05-17 22:23:37,533 - player - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
2018-05-17 22:23:37,808 - player - [INFO] launchables.player: Application Version: 1.7.42
2018-05-17 22:23:37,809 - player - [INFO] launchables.player: System Info: User: myPC, Platform: Windows, Machine: DESKTOP-IT2TACH, Release: 10, Version: 10.0.17134
2018-05-17 22:23:37,819 - player - [DEBUG] video_capture.file_backend: loaded videostream: <av.VideoStream #0 h264, yuv420p 1280x720 at 0x78ad5f8>
2018-05-17 22:23:37,829 - player - [DEBUG] video_capture.file_backend: No audiostream found in media container
2018-05-17 22:23:37,834 - player - [DEBUG] video_capture.file_backend: Auto loaded 2704 timestamps from C:\Users\myPC\Desktop\TEST DATA DROP\DOUBLE REC\NO INTERRUPTION LOCAL REC\world_timestamps.npy
2018-05-17 22:23:37,841 - player - [INFO] camera_models: Previously recorded calibration found and loaded!
2018-05-17 22:23:38,440 - player - [DEBUG] plugin: Loading plugin: Seek_Control with settings {'playback_speed': 1.0}
2018-05-17 22:23:38,440 - player - [DEBUG] plugin: Loading plugin: Pupil_From_Recording with settings {}
2018-05-17 22:23:38,442 - player - [DEBUG] pupil_producers: pupil positions changed
2018-05-17 22:23:38,443 - player - [DEBUG] plugin: Loading plugin: Gaze_From_Recording with settings {}
2018-05-17 22:23:38,445 - player - [DEBUG] gaze_producers: gaze positions changed
2018-05-17 22:23:38,445 - player - [DEBUG] plugin: Loading plugin: Log_Display with settings {}
2018-05-17 22:23:38,463 - player - [DEBUG] plugin: Loading plugin: Plugin_Manager with settings {}
2018-05-17 22:23:38,464 - player - [DEBUG] plugin: Loading plugin: System_Graphs with settings {'show_cpu': True, 'show_fps': True, 'show_conf0': True, 'show_conf1': True, 'show_dia0': False, 'show_dia1': False}
2018-05-17 22:23:38,469 - player - [DEBUG] plugin: Loading plugin: System_Timelines with settings {}
2018-05-17 22:23:38,471 - player - [DEBUG] plugin: Loading plugin: Video_Export_Launcher with settings {}
2018-05-17 22:23:38,471 - player - [DEBUG] plugin: Loading plugin: Audio_Playback with settings {}
2018-05-17 22:23:38,487 - player - [DEBUG] audio_playback: loaded audiostream: <av.AudioStream #0 aac at 44100Hz, mono, fltp at 0x926b198>
2018-05-17 22:23:38,488 - player - [DEBUG] audio_playback: audio_pts_rate = 1024 start_pts = 0
2018-05-17 22:23:38,488 - player - [DEBUG] audio_playback: Audio file format fltp chans 1 rate 44100 framesize 1024
2018-05-17 22:23:38,621 - player - [DEBUG] audio_playback: Audio output latency: 0.09287981859410431
2018-05-17 22:23:38,634 - player - [DEBUG] audio_utils: loaded audiostream: <av.AudioStream #0 aac at 44100Hz, mono, fltp at 0x926b208>
2018-05-17 22:23:38,634 - player - [DEBUG] plugin: Loading plugin: Vis_Polyline with settings {'color': [1.0, 0.0, 0.4, 1.0], 'thickness': 2}
2018-05-17 22:23:38,635 - player - [DEBUG] plugin: Loading plugin: Vis_Circle with settings {'radius': 20, 'color': [0.0, 0.7, 0.25, 0.2], 'thickness': 2, 'fill': True}
2018-05-17 22:23:46,544 - player - [DEBUG] plugin: Plugin <pupil_producers.Pupil_From_Recording object at 0x00000000078F8EB8> of base class Pupil_Producer_Base will be replaced by Pupil_From_Recording.
2018-05-17 22:23:46,544 - player - [DEBUG] plugin: Unloaded Plugin: <pupil_producers.Pupil_From_Recording object at 0x00000000078F8EB8>
2018-05-17 22:23:46,549 - player - [DEBUG] pupil_producers: pupil positions changed
2018-05-17 22:23:51,345 - player - [DEBUG] plugin: Plugin <gaze_producers.Gaze_From_Recording object at 0x00000000078F8F28> of base class Gaze_Producer_Base will be replaced by Gaze_From_Recording.
2018-05-17 22:23:51,346 - player - [DEBUG] plugin: Unloaded Plugin: <gaze_producers.Gaze_From_Recording object at 0x00000000078F8F28>
2018-05-17 22:23:51,348 - player - [DEBUG] gaze_producers: gaze positions changed
2018-05-17 22:23:52,679 - player - [DEBUG] audio_playback: Audio sync = 0.09887281859386642 rt_delay = -0.005992999999762105 adj_delay = -0.09887281859386642
2018-05-17 22:23:52,721 - player - [DEBUG] audio_playback: Measured latency = 0.1318976306292825
2018-05-17 22:23:54,511 - player - [DEBUG] audio_playback: *** Audio desync detected: 7.5242891685402356
2018-05-17 22:23:54,694 - player - [DEBUG] audio_playback: Audio sync = 0.0528138185945347 rt_delay = 0.04006599999956961 adj_delay = -0.0528138185945347
2018-05-17 22:23:54,741 - player - [DEBUG] audio_playback: Measured latency = 0.13268320151200896
2018-05-17 22:23:55,481 - player - [DEBUG] audio_playback: *** Audio desync detected: 12.140931169261421
2018-05-17 22:23:55,654 - player - [DEBUG] audio_playback: Audio sync = 0.08560581859450687 rt_delay = 0.007273999999597436 adj_delay = -0.08560581859450687
2018-05-17 22:23:55,701 - player - [DEBUG] audio_playback: Measured latency = 0.13275464205344178
2018-05-17 22:23:56,799 - player - [DEBUG] audio_playback: Audio sync = 0.10743281859408237 rt_delay = -0.014552999999978056 adj_delay = -0.10743281859408237
2018-05-17 22:23:56,841 - player - [DEBUG] audio_playback: Measured latency = 0.11663955670246651
2018-05-17 22:23:58,051 - player - [DEBUG] audio_playback: *** Audio desync detected: 35.577452619339965
2018-05-17 22:23:58,422 - player - [DEBUG] audio_playback: Audio sync = 0.07591481859430425 rt_delay = 0.016964999999800057 adj_delay = -0.07591481859430425
2018-05-17 22:23:58,471 - player - [DEBUG] audio_playback: Measured latency = 0.14765760154114105
2018-05-17 22:24:11,477 - player - [DEBUG] plugin: Plugin <pupil_producers.Pupil_From_Recording object at 0x000000000F109438> of base class Pupil_Producer_Base will be replaced by Offline_Pupil_Detection.
2018-05-17 22:24:11,478 - player - [DEBUG] plugin: Unloaded Plugin: <pupil_producers.Pupil_From_Recording object at 0x000000000F109438>
2018-05-17 22:24:12,018 - eye0 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
2018-05-17 22:24:12,026 - eye0 - [DEBUG] file_methods: Session settings file 'C:\Users\myPC\pupil_player_settings\user_settings_eye0' not found. Will make new one on exit.
2018-05-17 22:24:12,026 - eye0 - [INFO] launchables.eye: Session setting are from a different version of this app. I will not use those.
2018-05-17 22:24:12,074 - eye1 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
2018-05-17 22:24:12,087 - eye0 - [DEBUG] video_capture.file_backend: loaded videostream: <av.VideoStream #0 mjpeg, yuvj422p 192x192 at 0x5d3f668>
2018-05-17 22:24:12,087 - eye0 - [DEBUG] video_capture.file_backend: No audiostream found in media container
2018-05-17 22:24:12,089 - eye1 - [DEBUG] file_methods: Session settings file 'C:\Users\myPC\pupil_player_settings\user_settings_eye1' not found. Will make new one on exit.
2018-05-17 22:24:12,089 - eye1 - [INFO] launchables.eye: Session setting are from a different version of this app. I will not use those.
2018-05-17 22:24:12,092 - eye0 - [DEBUG] video_capture.file_backend: Auto loaded 19137 timestamps from C:\Users\myPC\Desktop\TEST DATA DROP\DOUBLE REC\NO INTERRUPTION LOCAL REC\eye0_timestamps.npy
2018-05-17 22:24:12,092 - eye0 - [INFO] camera_models: No user calibration found for camera eye0 at resolution (192, 192)
2018-05-17 22:24:12,093 - eye0 - [INFO] camera_models: No pre-recorded calibration available
2018-05-17 22:24:12,093 - eye0 - [WARNING] camera_models: Loading dummy calibration
2018-05-17 22:24:12,143 - eye1 - [DEBUG] video_capture.file_backend: loaded videostream: <av.VideoStream #0 mjpeg, yuvj422p 192x192 at 0x5d3f668>
2018-05-17 22:24:12,143 - eye1 - [DEBUG] video_capture.file_backend: No audiostream found in media container
2018-05-17 22:24:12,148 - eye1 - [DEBUG] video_capture.file_backend: Auto loaded 19373 timestamps from C:\Users\myPC\Desktop\TEST DATA DROP\DOUBLE REC\NO INTERRUPTION LOCAL REC\eye1_timestamps.npy
2018-05-17 22:24:12,149 - eye1 - [INFO] camera_models: No user calibration found for camera eye1 at resolution (192, 192)
2018-05-17 22:24:12,149 - eye1 - [INFO] camera_models: No pre-recorded calibration available
2018-05-17 22:24:12,149 - eye1 - [WARNING] camera_models: Loading dummy calibration
2018-05-17 22:24:13,701 - eye0 - [WARNING] launchables.eye: Process started.
2018-05-17 22:24:14,804 - eye1 - [WARNING] launchables.eye: Process started.
2018-05-17 22:25:18,160 - eye1 - [DEBUG] video_capture.file_backend: End of videofile 19372 19373
2018-05-17 22:25:18,160 - eye1 - [INFO] video_capture.file_backend: Video has ended.
2018-05-17 22:25:18,171 - player - [DEBUG] pupil_producers: eye 1 process complete
2018-05-17 22:25:18,277 - eye1 - [INFO] launchables.eye: Process shutting down.
2018-05-17 22:25:26,824 - eye0 - [DEBUG] video_capture.file_backend: End of videofile 19136 19137
2018-05-17 22:25:26,824 - eye0 - [INFO] video_capture.file_backend: Video has ended.
2018-05-17 22:25:26,841 - player - [DEBUG] pupil_producers: eye 0 process complete
2018-05-17 22:25:26,919 - player - [DEBUG] pupil_producers: pupil positions changed
2018-05-17 22:25:26,969 - eye0 - [INFO] launchables.eye: Process shutting down.
2018-05-17 22:25:27,193 - player - [INFO] pupil_producers: Cached detected pupil data to C:\Users\myPC\Desktop\TEST DATA DROP\DOUBLE REC\NO INTERRUPTION LOCAL REC\offline_data\offline_pupil_data
2018-05-17 22:25:33,709 - eye0 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
2018-05-17 22:25:33,723 - eye1 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
2018-05-17 22:25:33,782 - eye0 - [DEBUG] video_capture.file_backend: loaded videostream: <av.VideoStream #0 mjpeg, yuvj422p 192x192 at 0x5d3f668>
2018-05-17 22:25:33,782 - eye0 - [DEBUG] video_capture.file_backend: No audiostream found in media container
2018-05-17 22:25:33,782 - eye1 - [DEBUG] video_capture.file_backend: loaded videostream: <av.VideoStream #0 mjpeg, yuvj422p 192x192 at 0x5d3f668>
2018-05-17 22:25:33,782 - eye1 - [DEBUG] video_capture.file_backend: No audiostream found in media container
2018-05-17 22:25:33,787 - eye0 - [DEBUG] video_capture.file_backend: Auto loaded 19137 timestamps from C:\Users\myPC\Desktop\TEST DATA DROP\DOUBLE REC\NO INTERRUPTION LOCAL REC\eye0_timestamps.npy
2018-05-17 22:25:33,788 - eye1 - [DEBUG] video_capture.file_backend: Auto loaded 19373 timestamps from C:\Users\myPC\Desktop\TEST DATA DROP\DOUBLE REC\NO INTERRUPTION LOCAL REC\eye1_timestamps.npy
2018-05-17 22:25:33,788 - eye0 - [INFO] camera_models: No user calibration found for camera eye0 at resolution (192, 192)
2018-05-17 22:25:33,788 - eye0 - [INFO] camera_models: No pre-recorded calibration available
2018-05-17 22:25:33,788 - eye1 - [INFO] camera_models: No user calibration found for camera eye1 at resolution (192, 192)
2018-05-17 22:25:33,788 - eye0 - [WARNING] camera_models: Loading dummy calibration
2018-05-17 22:25:33,788 - eye1 - [INFO] camera_models: No pre-recorded calibration available
2018-05-17 22:25:33,788 - eye1 - [WARNING] camera_models: Loading dummy calibration
2018-05-17 22:25:35,700 - eye1 - [WARNING] launchables.eye: Process started.
2018-05-17 22:25:36,670 - eye0 - [WARNING] launchables.eye: Process started.
2018-05-17 22:27:01,049 - eye0 - [DEBUG] video_capture.file_backend: End of videofile 19136 19137
2018-05-17 22:27:01,049 - eye0 - [INFO] video_capture.file_backend: Video has ended.
2018-05-17 22:27:01,050 - player - [DEBUG] pupil_producers: eye 0 process complete
2018-05-17 22:27:01,070 - eye1 - [DEBUG] video_capture.file_backend: End of videofile 19372 19373
2018-05-17 22:27:01,070 - eye1 - [INFO] video_capture.file_backend: Video has ended.
2018-05-17 22:27:01,085 - player - [DEBUG] pupil_producers: eye 1 process complete
2018-05-17 22:27:01,177 - eye0 - [INFO] launchables.eye: Process shutting down.
2018-05-17 22:27:01,192 - eye1 - [INFO] launchables.eye: Process shutting down.
2018-05-17 22:27:01,230 - player - [DEBUG] pupil_producers: pupil positions changed
2018-05-17 22:27:01,472 - player - [INFO] pupil_producers: Cached detected pupil data to C:\Users\myPC\Desktop\TEST DATA DROP\DOUBLE REC\NO INTERRUPTION LOCAL REC\offline_data\offline_pupil_data
2018-05-17 22:27:08,634 - player - [DEBUG] plugin: Plugin <gaze_producers.Gaze_From_Recording object at 0x000000000F109518> of base class Gaze_Producer_Base will be replaced by Offline_Calibration.
2018-05-17 22:27:08,637 - player - [DEBUG] plugin: Unloaded Plugin: <gaze_producers.Gaze_From_Recording object at 0x000000000F109518>
2018-05-17 22:27:10,368 - circle_detector - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
2018-05-17 22:27:10,391 - circle_detector - [INFO] camera_models: Previously recorded calibration found and loaded!
2018-05-17 22:27:10,395 - circle_detector - [INFO] launchables.marker_detectors: Starting calibration marker detection...
2018-05-17 22:27:19,759 - player - [INFO] gaze_producers: Calibrating section 1 (Unnamed section) in 3d mode...
2018-05-17 22:27:39,956 - player - [INFO] gaze_producers: Calibrating section 1 (Calib) in 3d mode...
2018-05-17 22:28:10,524 - player - [INFO] gaze_producers: Cached offline calibration data to C:\Users\myPC\Desktop\TEST DATA DROP\DOUBLE REC\NO INTERRUPTION LOCAL REC\offline_data\offline_calibration_gaze
2018-05-17 22:29:51,719 - player - [ERROR] launchables.player: Process Player crashed with trace:
Traceback (most recent call last):
  File "launchables\player.py", line 478, in player
  File "site-packages\OpenGL\error.py", line 232, in glCheckError
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'ung\xfcltiger Wert',
	baseOperation = glViewport,
	cArguments = (0, 0, 1280, 720)
)

2018-05-17 22:29:51,719 - player - [INFO] launchables.player: Process shutting down.

**Comment by emolyzr** [comment]
Howdy,

I found this closed thread: https://github.com/pupil-labs/pupil/issues/1097

I tried minimizing the pupil player window, upon restore the error appears. Might not be as unsystematic as I first thougt. Okay. So, a potential workaround is not to minimize the window. But it doesn't seem to be fixed - at least not in the latest release 1.7.42.

**Comment by mkassner** [comment]
dublicate.
