### ISSUE TITLE
Problem running pupil from source - cholmod_solve

### ISSUE THREAD

**Issue by jicont21** [pupil-labs/pupil#1186]
Hi, I'm trying to run pupil source cloned from git.
I get this output

```
[aero@vision-movil pupil_src]$ pwd
/home/aero/pupil/pupil_src
[aero@vision-movil pupil_src]$ python main.py 
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] launchables.world: Application Version: 1.7.57
world - [INFO] launchables.world: System Info: User: aero, Platform: Linux, Machine: vision-movil, Release: 4.16.8-1-ARCH, Version: #1 SMP PREEMPT Wed May 9 11:25:02 UTC 2018
world - [INFO] pupil_detectors.build: Building extension modules...
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/aero/pupil/pupil_src/launchables/world.py", line 113, in world
    import pupil_detectors
  File "/home/aero/pupil/pupil_src/shared_modules/pupil_detectors/__init__.py", line 19, in <module>
    from .detector_3d import Detector_3D
ImportError: /home/aero/pupil/pupil_src/shared_modules/pupil_detectors/detector_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cholmod_solve

world - [INFO] launchables.world: Process shutting down.
[aero@vision-movil pupil_src]$ 
```
I haven't modified the source code

Anyone know what happened?

**Comment by jicont21** [comment]
Hi,
I have deleted the cloned source, recompiled ceres, installed it, cloned the source again, and then tried to run pupil... same results :(

```
[aero@vision-movil ~]$ git clone https://github.com/pupil-labs/pupil.git
Clonando en 'pupil'...
remote: Counting objects: 31738, done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 31738 (delta 62), reused 54 (delta 32), pack-reused 31637
Recibiendo objetos: 100% (31738/31738), 13.60 MiB | 251.00 KiB/s, listo.
Resolviendo deltas: 100% (22637/22637), listo.
[aero@vision-movil ~]$ cd pupil/
[aero@vision-movil pupil]$ ls
COPYING  COPYING.LESSER  deployment  pupil_external  pupil_src  README.md  update_license_header.py
[aero@vision-movil pupil]$ cd pupil_src/
[aero@vision-movil pupil_src]$ python main.py 
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] launchables.world: Application Version: 1.7.57
world - [INFO] launchables.world: System Info: User: aero, Platform: Linux, Machine: vision-movil, Release: 4.16.8-1-ARCH, Version: #1 SMP PREEMPT Wed May 9 11:25:02 UTC 2018
world - [INFO] pupil_detectors.build: Building extension modules...
cc1plus: aviso: la opción de línea de órdenes ‘-Wstrict-prototypes’ es válida para C/ObjC pero no para C++
cc1plus: aviso: la opción de línea de órdenes ‘-Wstrict-prototypes’ es válida para C/ObjC pero no para C++
cc1plus: aviso: la opción de línea de órdenes ‘-Wstrict-prototypes’ es válida para C/ObjC pero no para C++
cc1plus: aviso: la opción de línea de órdenes ‘-Wstrict-prototypes’ es válida para C/ObjC pero no para C++
cc1plus: aviso: la opción de línea de órdenes ‘-Wstrict-prototypes’ es válida para C/ObjC pero no para C++
cc1plus: aviso: la opción de línea de órdenes ‘-Wstrict-prototypes’ es válida para C/ObjC pero no para C++
cc1plus: aviso: la opción de línea de órdenes ‘-Wstrict-prototypes’ es válida para C/ObjC pero no para C++
cc1plus: aviso: la opción de línea de órdenes ‘-Wstrict-prototypes’ es válida para C/ObjC pero no para C++
cc1plus: aviso: la opción de línea de órdenes ‘-Wstrict-prototypes’ es válida para C/ObjC pero no para C++
cc1plus: aviso: la opción de línea de órdenes ‘-Wstrict-prototypes’ es válida para C/ObjC pero no para C++
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/aero/pupil/pupil_src/launchables/world.py", line 113, in world
    import pupil_detectors
  File "/home/aero/pupil/pupil_src/shared_modules/pupil_detectors/__init__.py", line 19, in <module>
    from .detector_3d import Detector_3D
ImportError: /home/aero/pupil/pupil_src/shared_modules/pupil_detectors/detector_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cholmod_solve

world - [INFO] launchables.world: Process shutting down.
[aero@vision-movil pupil_src]$
```
I've installed all the dependencies listed on the documentation... Is there something else I could check?

**Comment by mkassner** [comment]
@jicont21  we are about to simplify the install instructions for Ubunut 18.04. Once this is done, no need to build ceres anymore...

**Comment by jicont21** [comment]
Please, add a comment to this issue the moment you accomplish this so I can try this again with a frash cloned source.

**Comment by jicont21** [comment]
Hello, how are you?
Is there any news on this?
I look forward to your comments.

**Comment by jicont21** [comment]
Hi. How are you?
Do we have any news on this?
Cheers.

**Comment by jicont21** [comment]
This was actually my problem:

I was building ceres-solver from 
http://ceres-solver.org/
instead of
https://ceres-solver.googlesource.com/ 

I recompiled the source code downloaded from the site cited in the documentation (ceres-solver.googlesource.com) and the problem was solved.

Thanks for the feedback.

**Comment by eicm** [comment]
@papr I'm building the pupil source on Fedora 29, when building the ceres from source which ceres branch/version should I use for building
