### ISSUE TITLE
library not found for -lboost_python3 even though it's installed

### ISSUE THREAD

**Issue by burknator** [pupil-labs/pupil#1196]
When installing everything according to the docs and starting `python3 pupil_src/main.py`, the build of pupil_detectors fails:

```
python3 pupil_src/main.py
MainProcess - [INFO] os_utils: Disabled idle sleep.
world - [INFO] launchables.world: Application Version: 1.7.57
world - [INFO] launchables.world: System Info: User: patrick, Platform: Darwin, Machine: the-machine.local, Release: 17.5.0, Version: Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64
world - [INFO] pupil_detectors.build: Building extension modules...
ld: library not found for -lboost_python3
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang++' failed with exit status 1
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/Users/patrick/Code/pupil/pupil_src/launchables/world.py", line 113, in world
    import pupil_detectors
  File "/Users/patrick/Code/pupil/pupil_src/shared_modules/pupil_detectors/__init__.py", line 16, in <module>
    build_cpp_extension()
  File "/Users/patrick/Code/pupil/pupil_src/shared_modules/pupil_detectors/build.py", line 25, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/opt/python/bin/python3.6', 'setup.py', 'install', '--install-lib=/Users/patrick/Code/pupil/pupil_src/shared_modules']' returned non-zero exit status 1.

world - [INFO] launchables.world: Process shutting down.
MainProcess - [INFO] os_utils: Re-enabled idle sleep.
```

It seems like the current version of the Homebrew package `boost-python3` needs different linker flags than previous versions. As you can the [in the test of the formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost-python3.rb#L92), they use a different name for boost_python (`boost-python36` instead of `boost-python3`).

I created the PR #1195 to fix this.

**Comment by burknator** [comment]
#1195 was merged, I guess that closes this issue.
