### ISSUE TITLE
Version Error

### ISSUE THREAD

**Issue by LIUMeng0823** [pupil-labs/pupil#1202]
After installing Linux dependencies, I run the main.py and got the error as the following:

/home/meng/Downloads/pupil-master/venv/bin/python /home/meng/Downloads/pupil-master/pupil_src/main.py
Error calling git: "Command '['git', 'describe', '--tags']' returned non-zero exit status 128" 
 output: "b'fatal: Not a git repository (or any of the parent directories): .git\n'"
Traceback (most recent call last):
  File "/home/meng/Downloads/pupil-master/pupil_src/main.py", line 50, in <module>
    app_version = get_version(version_file)
  File "/home/meng/Downloads/pupil-master/pupil_src/shared_modules/version_utils.py", line 56, in get_version
    version = pupil_version()
  File "/home/meng/Downloads/pupil-master/pupil_src/shared_modules/version_utils.py", line 40, in pupil_version
    raise ValueError('Version Error')
ValueError: Version Error

Process finished with exit code 1

Would someone tell me how to fix this? Thanks!

**Comment by papr** [comment]
You need to use git clone to copy the repository instead of downloading the zipped source code.

**Comment by LIUMeng0823** [comment]
Thanks! Problem solved! Really appreciate!
