### ISSUE TITLE
WORLD Process [ERROR] recorder : Could not save metadata.

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#124]
Reported! 
```
WORLD Process [ERROR] recorder : Could not save metadata. Please report this bug!
Traceback (most recent call last):
  File "/home/rafael/pupil/pupil_src/capture/recorder.py", line 311, in stop
    username = os.getlogin()
OSError: [Errno 25] Inappropriate ioctl for device
```

**Comment by willpatera** [comment]
Thanks @cpicanco -- could you remind me again what Linux distro you're using?

**Comment by cpicanco** [comment]
Lubuntu 14.04 LTS

**Comment by mkassner** [comment]
I think that's the issue. this bug is not critical so Ill close this.

**Comment by cpicanco** [comment]
@mkassner , I am getting this error after stop a recording, but apparently the metadata is really being saved. 
```
WORLD Process [ERROR] recorder : Could not save metadata. Please report this bug!
Traceback (most recent call last):
  File "/home/rafael/pupil-o/pupil_src/capture/recorder.py", line 307, in stop
    username = os.getlogin()
OSError: [Errno 25] Inappropriate ioctl for device
```

**Comment by cpicanco** [comment]
here is the info.csv content:
Ubuntu 14.0.4 LTS this time.

```
Recording Name	2015_05_11
Start Date	11.05.2015
Start Time	15:26:40
Duration Time	00:06:00
Eye Mode	monocular
Duration Time	00:06:00
World Camera Frames	10824
World Camera Resolution	1280x720
Capture Software Version	0.4.5.1
```
