### ISSUE TITLE
Eyetracker recording via Pupil Capture and Pupil Mobile is broken

### ISSUE THREAD

**Issue by ewolf29** [pupil-labs/pupil#1248]
System: MacOS
Pupil Capture: V1.8.12
Pupil Player: V1.8.12
Pupil Mobile: 0.30.0
Wifi: 5Ghz with 850Mbit

Today, I have tried to record a session with Pupil Capture and Pupil Mobile. The recording is for some reason broken in the middle. When you play the file in Pupil Player and it comes to a certain point, the player crashes. Also, the filling of the marker cache is stopping at this point.

Reconding: https://oc.informatik.uni-wuerzburg.de/index.php/s/KyNeyRX66pKgkX5
Password: pupillabs

**Comment by papr** [comment]
I can recreate the issue. It looks like the video file itself is broken. I will test if transcoding the video file helps.

```
player - [ERROR] libav.mjpeg: overread 8
player - [ERROR] libav.mjpeg: error count: 65
player - [ERROR] libav.mjpeg: error y=0 x=39
player - [ERROR] libav.IMGUTILS: Picture size 65535x33023 is invalid
player - [ERROR] launchables.player: Process Player crashed with trace:
Traceback (most recent call last):
  File "/home/papr/work/pupil/pupil_src/launchables/player.py", line 464, in player
    p.recent_events(events)
  File "/home/papr/work/pupil/pupil_src/shared_modules/video_capture/file_backend.py", line 170, in run_func
    return func(self, *args, **kwargs)
  File "/home/papr/work/pupil/pupil_src/shared_modules/video_capture/file_backend.py", line 287, in recent_events_external_timing
    frame = frame or self.get_frame()
  File "/home/papr/work/pupil/pupil_src/shared_modules/video_capture/file_backend.py", line 170, in run_func
    return func(self, *args, **kwargs)
  File "/home/papr/work/pupil/pupil_src/shared_modules/video_capture/file_backend.py", line 235, in get_frame
    for frame in self.next_frame:
  File "/home/papr/work/pupil/pupil_src/shared_modules/video_capture/file_backend.py", line 217, in _next_frame
    for frame in packet.decode():
  File "av/packet.pyx", line 107, in av.packet.Packet.decode (src/av/packet.c:3590)
  File "av/stream.pyx", line 136, in av.stream.Stream.decode (src/av/stream.c:3672)
  File "av/codec/context.pyx", line 365, in av.codec.context.CodecContext.decode (src/av/codec/context.c:7016)
  File "av/codec/context.pyx", line 241, in av.codec.context.CodecContext._send_packet_and_recv (src/av/codec/context.c:5254)
  File "av/utils.pyx", line 105, in av.utils.err_check (src/av/utils.c:2577)
av.AVError: [Errno 1094995529] Invalid data found when processing input (libav.IMGUTILS: Picture size 65535x33023 is invalid)
```

**Comment by ewolf29** [comment]
It seems like recordings can break quite easy when recording it from Pupil Mobile. Is there may be a general issue? The best would be when, for example, missing frames are just dropped and the recording won't break.

**Comment by papr** [comment]
I was able to playback the recording after transcoding the video using
1. `ffmpeg -i world.mp4 world2.mp4`
2. Renaming `world.mp4` to `world_original.mp4`
3. Renaming `world2.mp4` to `world.mp4`

Be aware that this likely drops the broken frames which results in slightly misaligned world timestamps.

**Comment by papr** [comment]
Unfortunately correct. May I ask which phone you use and if you are recording to an sd card?

**Comment by ewolf29** [comment]
We are using the OnePlus 5T and we are recording using Pupil Capture and connecting the phone via Wifi to a MacBook. The first plan was to record to the phone directly but compression makes surface tracking really inaccurate and using no compression leads to the problem that files grow to fast reaching the file size limit after 10 minutes.

**Comment by papr** [comment]
Oh, ok, I understand. Then this is actually something that should be fixable in Capture. Let me talk to my colleague about this.

**Comment by ewolf29** [comment]
Just to make sure, `ffmpeg -i world.mp4 world2.mp4` is compressing the file, isn't it? Doesn't this lead again to worse trackable surfaces?

**Comment by papr** [comment]
Yes, this is the default. I think there are ffmpeg parameters that define the output format and the compression rate.

**Comment by papr** [comment]
Closing due to inactivity.
