### ISSUE TITLE
Crash when recording during Frame Publisher enabled

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#1263]
Issue: Frame Publisher places frame data into the events dict and it is not properly ignored by the recorder. Reproduced on macOS using Fake Capture.

Reported by @mattem86

**Comment by prernaneja** [comment]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] launchables.world: Application Version: 1.8.26
world - [INFO] launchables.world: System Info: User: Administrator, Platform: Windows, Machine: CELLAP034, Release: 10, Version: 10.0.10586
world - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID2 at resolution [1280, 720]
world - [INFO] camera_models: No pre-recorded calibration available
world - [WARNING] camera_models: Loading dummy calibration
world - [WARNING] pyre.pyre_node: Group default-time_sync-v1 not found.
world - [WARNING] video_capture.ndsi_backend: Make sure the `time_sync` plugin is loaded!
world - [WARNING] launchables.world: Process started.
eye1 - [WARNING] video_capture.ndsi_backend: Make sure the `time_sync` plugin is loaded!
eye1 - [WARNING] launchables.eye: Process started.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "shared_modules\zmq_tools.py", line 41, in emit
  File "shared_modules\zmq_tools.py", line 146, in send
  File "msgpack\__init__.py", line 47, in packb
  File "msgpack\_packer.pyx", line 284, in msgpack._packer.Packer.pack
  File "msgpack\_packer.pyx", line 290, in msgpack._packer.Packer.pack
  File "msgpack\_packer.pyx", line 287, in msgpack._packer.Packer.pack
  File "msgpack\_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack\_packer.pyx", line 232, in msgpack._packer.Packer._pack
  File "msgpack\_packer.pyx", line 281, in msgpack._packer.Packer._pack
TypeError: can't serialize UUID('f8f78d45-ecdd-4591-956b-4eaf3e366ce2')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "pyre\zactor.py", line 57, in run
  File "pyre\pyre_node.py", line 53, in __init__
  File "pyre\pyre_node.py", line 519, in run
  File "pyre\pyre_node.py", line 478, in recv_beacon
  File "logging\__init__.py", line 1318, in warning
  File "logging\__init__.py", line 1442, in _log
  File "logging\__init__.py", line 1452, in handle
  File "logging\__init__.py", line 1514, in callHandlers
  File "logging\__init__.py", line 863, in handle
  File "shared_modules\zmq_tools.py", line 45, in emit
  File "shared_modules\zmq_tools.py", line 146, in send
  File "msgpack\__init__.py", line 47, in packb
  File "msgpack\_packer.pyx", line 284, in msgpack._packer.Packer.pack
  File "msgpack\_packer.pyx", line 290, in msgpack._packer.Packer.pack
  File "msgpack\_packer.pyx", line 287, in msgpack._packer.Packer.pack
  File "msgpack\_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack\_packer.pyx", line 232, in msgpack._packer.Packer._pack
  File "msgpack\_packer.pyx", line 281, in msgpack._packer.Packer._pack
TypeError: can't serialize UUID('f8f78d45-ecdd-4591-956b-4eaf3e366ce2')
Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "main.py", line 160, in log_loop
  File "shared_modules\zmq_tools.py", line 99, in recv
  File "shared_modules\zmq_tools.py", line 110, in deserialize_payload
  File "msgpack\_unpacker.pyx", line 208, in msgpack._unpacker.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "shared_modules\zmq_tools.py", line 41, in emit
  File "shared_modules\zmq_tools.py", line 146, in send
  File "msgpack\__init__.py", line 47, in packb
  File "msgpack\_packer.pyx", line 284, in msgpack._packer.Packer.pack
  File "msgpack\_packer.pyx", line 290, in msgpack._packer.Packer.pack
  File "msgpack\_packer.pyx", line 287, in msgpack._packer.Packer.pack
  File "msgpack\_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack\_packer.pyx", line 232, in msgpack._packer.Packer._pack
  File "msgpack\_packer.pyx", line 281, in msgpack._packer.Packer._pack
TypeError: can't serialize UUID('5551021e-5115-462a-9798-f7b4b926fe29')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "pyre\zactor.py", line 57, in run
  File "pyre\pyre_node.py", line 53, in __init__
  File "pyre\pyre_node.py", line 519, in run
  File "pyre\pyre_node.py", line 478, in recv_beacon
  File "logging\__init__.py", line 1318, in warning
  File "logging\__init__.py", line 1442, in _log
  File "logging\__init__.py", line 1452, in handle
  File "logging\__init__.py", line 1514, in callHandlers
  File "logging\__init__.py", line 863, in handle
  File "shared_modules\zmq_tools.py", line 45, in emit
  File "shared_modules\zmq_tools.py", line 146, in send
  File "msgpack\__init__.py", line 47, in packb
  File "msgpack\_packer.pyx", line 284, in msgpack._packer.Packer.pack
  File "msgpack\_packer.pyx", line 290, in msgpack._packer.Packer.pack
  File "msgpack\_packer.pyx", line 287, in msgpack._packer.Packer.pack
  File "msgpack\_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack\_packer.pyx", line 232, in msgpack._packer.Packer._pack
  File "msgpack\_packer.pyx", line 281, in msgpack._packer.Packer._pack
TypeError: can't serialize UUID('5551021e-5115-462a-9798-f7b4b926fe29')

**Comment by papr** [comment]
@prernaneja I was mistaken. Your issue is independent of this issue. Please open a new issue if it still persists.

**Comment by prernaneja** [comment]
I have tried using both version 1.7 and 1.8, and I am still getting some
errors due to which the pupil capture crashes. Finally, when I de-selected
pupil remote, the software stopped crashing.

Could you please let me know how I could resolve this?

Best,
Prerna
