### ISSUE TITLE
Pupil Capture crash

### ISSUE THREAD

**Issue by schtiefel** [pupil-labs/pupil#1284]
Lately *Capture* sometimes crashes a few seconds after starting — it has not yet happened at a later time.

Console output including trace looks like this:
```
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] launchables.world: Application Version: 1.8.26
world - [INFO] launchables.world: System Info: User: ###, Platform: Windows, Machine: ###, Release: 10, Version: 10.0.17134
world - [INFO] plugin: Added: <class 'plugin.Analysis_Plugin_Base'>
world - [INFO] plugin: Added: <class 'blink_detection_fixed.Blink_Detection_Fixed'>
world - [WARNING] launchables.world: Process started.
Running  PupilDrvInst.exe --vid 1443 --pid 37424
OPT: VID number 1443
OPT: PID number 37424
...
eye0 - [INFO] camera_models: No user calibration found for camera Pupil Cam2 ID0 at resolution (400, 400)
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
Running  PupilDrvInst.exe --vid 1443 --pid 37424
OPT: VID number 1443
OPT: PID number 37424
...
eye1 - [INFO] camera_models: No user calibration found for camera Pupil Cam2 ID1 at resolution (400, 400)
eye1 - [INFO] camera_models: No pre-recorded calibration available
eye1 - [WARNING] camera_models: Loading dummy calibration
eye1 - [WARNING] uvc: Could not set Value. 'Backlight Compensation'.
eye0 - [WARNING] launchables.eye: Process started.
Estimated / selected altsetting bandwith : 617 / 800.
!!!!Packets per transfer = 32 frameInterval = 83263
eye1 - [WARNING] launchables.eye: Process started.
Estimated / selected altsetting bandwith : 617 / 800.
!!!!Packets per transfer = 32 frameInterval = 83263
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "launchables\world.py", line 482, in world
  File "OpenGL\error.py", line 232, in glCheckError
OpenGL.error.GLError: GLError(
        err = 1281,
        description = b'ung\xfcltiger Wert',
        baseOperation = glViewport,
        cArguments = (0, 0, 1330, 720)
)
```

**Comment by Windsooon** [comment]
@schtiefel, just to be clear, after you run `python main.py capture` , the `capture` crashed. Then it works when you run that command again?

**Comment by schtiefel** [comment]
I tried, but cannot reproduce the issue right now.
Maybe it was an issue with v1.8, maybe with the hotfixed plugin [Blink_Detection_Fixed](https://github.com/pupil-labs/pupil/pull/1283).

I always use `pupil_capture.exe` instead of the python command (not sure if this makes any difference).
But, yes, as far as I remember, the issue did only occur occasionally. So, running it again was (sometimes) the solution.

**Comment by pfaion** [comment]
Quote @papr in #1870:
> The issue is caused if there is no scene image but pupil data that is recognized to be a blink.
I'll see if I can reproduce and fix this issue.

**Comment by vkmcheung** [comment]
Apologies for posting here (this was the most relevant open thread I could find on the topic); Just wanted to say that we recently encountered a  "could not set value: Backlight Compensation" warning, and we seemed to have resolved it by adjusting the forward-facing camera so that the monitor was in its field of view.
