### ISSUE TITLE
Launching Pupil lab from terminal

### ISSUE THREAD

**Issue by valvador92** [pupil-labs/pupil#1337]
I tried to launch the program from the terminal: python3 main.py.
It seems that I have a version error. I don't know how to fix it!

Thank You

Error calling git: "Command '['git', 'describe', '--tags']' returned non-zero exit status 128" 
 output: "b'fatal: Not a git repository (or any of the parent directories): .git\n'"
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    app_version = get_version(version_file)
  File "/home/student/Desktop/pupil-master/pupil_src/shared_modules/version_utils.py", line 56, in get_version
    version = pupil_version()
  File "/home/student/Desktop/pupil-master/pupil_src/shared_modules/version_utils.py", line 40, in pupil_version
    raise ValueError('Version Error')
ValueError: Version Error

**Comment by valvador92** [comment]
Thank you for your fast response. It fixed the error. But now I have an other one:

Traceback (most recent call last):
  File "main.py", line 58, in <module>
    import zmq
ImportError: No module named 'zmq'

**Comment by papr** [comment]
Please follow the instructions on how to install all source dependencies: https://docs.pupil-labs.com/#running-pupil-from-source

**Comment by valvador92** [comment]
Thank you
