### ISSUE TITLE
Messing around with new topic "Annotation" fires exception

### ISSUE THREAD

**Issue by mattem86** [pupil-labs/pupil#1382]
Pupil Capture becomes unresponsive and will not start anymore until I delete the pupil_capture_settings folder. The exception is:

2018-11-09 14:39:25,206 - world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "pyglui/ui_elements.pxi", line 382, in pyglui.ui.Selector._on_change (pyglui/ui.cpp:21371)
ValueError: 'Dummy' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "launchables/world.py", line 488, in world
  File "pyglui/ui.pyx", line 195, in pyglui.ui.UI.update (pyglui/ui.cpp:11371)
  File "pyglui/ui.pyx", line 125, in pyglui.ui.UI.sync (pyglui/ui.cpp:10105)
  File "pyglui/menus.pxi", line 19, in pyglui.ui.Base_Menu.sync (pyglui/ui.cpp:49745)
  File "pyglui/menus.pxi", line 22, in pyglui.ui.Base_Menu.sync (pyglui/ui.cpp:49676)
  File "pyglui/menus.pxi", line 19, in pyglui.ui.Base_Menu.sync (pyglui/ui.cpp:49745)
  File "pyglui/menus.pxi", line 22, in pyglui.ui.Base_Menu.sync (pyglui/ui.cpp:49676)
  File "pyglui/ui_elements.pxi", line 376, in pyglui.ui.Selector.sync (pyglui/ui.cpp:21192)
  File "pyglui/ui_elements.pxi", line 377, in pyglui.ui.Selector.sync (pyglui/ui.cpp:21145)
  File "pyglui/ui.pyx", line 364, in pyglui.ui.Synced_Value.sync (pyglui/ui.cpp:67694)
  File "pyglui/ui_elements.pxi", line 388, in pyglui.ui.Selector._on_change (pyglui/ui.cpp:21469)
ValueError: Synced value 'Dummy' is not part of selection.

**Comment by papr** [comment]
Could you please list the steps to reproduce the issue.

**Comment by mattem86** [comment]
I'm trying to send annotations over the topic "annotation" – the client application throws an error, "Req.XSend - cannot send another request". Pupil Capture becomes unresponsive – I close it and it will crash on restart (see exception)
