### ISSUE TITLE
world camera process crash during exposure adjustment

### ISSUE THREAD

**Issue by beasfall** [pupil-labs/pupil#143]
Was experimenting with manual adjustment of world camera exposure using the Capture program UI. (toggling exposure mode buttons and moving Exposure_abs slider)

Running from source (at commit 9423f340bee44af28978f3c0f392975d462fee0d) on OSX 10.9.

Error:
```
Apr 22 14:11:11 mac.local se.dm9.uvcc[81735] <Error>: uvccSendRawRequest: ControlRequest returned 0xe00002e8 (kIOReturnOverrun): data overrun.
Traceback (most recent call last):
  File "main.py", line 149, in <module>
    main()
  File "main.py", line 140, in main
    world(g_pool,world_src,world_size)
  File "/Users/d/Projects/bg/items/Pupil-internal/pupil_src/capture/world.py", line 346, in world
    g_pool.gui.update()
  File "pyglui/ui.pyx", line 132, in pyglui.ui.UI.update (pyglui/ui.c:7461)
  File "pyglui/ui.pyx", line 120, in pyglui.ui.UI.draw (pyglui/ui.c:7323)
  File "pyglui/menus.pxi", line 459, in pyglui.ui.Scrolling_Menu.draw (pyglui/ui.c:37161)
  File "pyglui/menus.pxi", line 466, in pyglui.ui.Scrolling_Menu.draw (pyglui/ui.c:37029)
  File "pyglui/menus.pxi", line 487, in pyglui.ui.Scrolling_Menu.draw_scroll_window_elements (pyglui/ui.c:37414)
  File "pyglui/menus.pxi", line 291, in pyglui.ui.Growing_Menu.draw (pyglui/ui.c:34171)
  File "pyglui/menus.pxi", line 303, in pyglui.ui.Growing_Menu.draw (pyglui/ui.c:33993)
  File "pyglui/ui_elements.pxi", line 102, in pyglui.ui.Slider.draw (pyglui/ui.c:12100)
  File "pyglui/ui_elements.pxi", line 108, in pyglui.ui.Slider.draw (pyglui/ui.c:11006)
TypeError: a float is required
```

**Comment by mkassner** [comment]
Thanks for the report. Fixed!
