### ISSUE TITLE
find_concentric_circles not compatible with opencv4

### ISSUE THREAD

**Issue by sonny07** [pupil-labs/pupil#1463]
I'm running pupil capture from source and it will shut down after I click on calibration. The machine is running on Ubuntu 18.04.2

Here is the trace:
> world - [INFO] calibration_routines.screen_marker_calibration: Starting Calibration
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/kap0536/Videos/eye gaze/pupil/pupil_src/launchables/world.py", line 607, in world
    p.recent_events(events)
  File "/home/kap0536/Videos/eye gaze/pupil/pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py", line 306, in recent_events
    self.markers = self.circle_tracker.update(gray_img)
  File "/home/kap0536/Videos/eye gaze/pupil/pupil_src/shared_modules/circle_detector.py", line 59, in update
    markers = self._check_frame(img)
  File "/home/kap0536/Videos/eye gaze/pupil/pupil_src/shared_modules/circle_detector.py", line 99, in _check_frame
    ellipses_list = find_pupil_circle_marker(img, scale)
  File "/home/kap0536/Videos/eye gaze/pupil/pupil_src/shared_modules/circle_detector.py", line 249, in find_pupil_circle_marker
    min_ellipses_num=2,
  File "/home/kap0536/Videos/eye gaze/pupil/pupil_src/shared_modules/circle_detector.py", line 431, in find_concentric_circles
    edge, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_TC89_KCOS
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by papr** [comment]
Hi @sonny07 
As you have mentioned in #1464, you have installed opencv4 instead of opencv3. The code is currently not compatible with opencv4, therefore the ValueError. As mentioned in #1464, we are planning on transitioning to opencv4 in the future: https://github.com/pupil-labs/pupil/issues/1437

If you want to speed up this process, keep testing from source with opencv 4 and report all opencv related issue has you have done with this one. 👍

**Comment by papr** [comment]
@sonny07 Please checkout https://github.com/pupil-labs/pupil/tree/opencv4

**Comment by papr** [comment]
Fixed via #1495
