### ISSUE TITLE
pyrealsense.utils.RealsenseError: rs_create_context(api_version:11203) crashed with: UVCIOC_CTRL_QUERY:UVC_GET_CUR error 56, Invalid request code

### ISSUE THREAD

**Issue by jhs0053** [pupil-labs/pupil#1479]
Hello.

I have installed librealsense and pyrealsense for ubuntu 18.04.

Then, I have run pupil with realsense R200.

However, I have got an error as:

jhs@jhs-desktop:~/pupil/pupil_src$ python3 main.py
 world - [INFO] launchables.world: Application Version: 1.11.37
 world - [INFO] launchables.world: System Info: User: jhs, Platform: Linux, Machine: jhs-desktop, Release: 4.15.0-47-generic, Version: #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019
 world - [INFO] pupil_detectors.build: Building extension modules...
 world - [INFO] calibration_routines.optimization_calibration.build: Building extension modules...
 world - [INFO] cython_methods.build: Building extension modules...
 world - [ERROR] launchables.world: Process Capture crashed with trace:
 Traceback (most recent call last):
   File "/home/jhs/pupil/pupil_src/launchables/world.py", line 547, in world
     g_pool, session_settings.get("loaded_plugins", default_plugins)
   File "/home/jhs/pupil/pupil_src/shared_modules/plugin.py", line 307, in __init__
     self.add(plugin_by_name[name], args)
   File "/home/jhs/pupil/pupil_src/shared_modules/plugin.py", line 340, in add
     plugin_instance = new_plugin(self.g_pool, **args)
   File "/home/jhs/pupil/pupil_src/shared_modules/video_capture/realsense_backend.py", line 213, in __init__
     self.service = pyrs.Service()
   File "/home/jhs/.local/lib/python3.6/site-packages/pyrealsense/core.py", line 27, in __init__
     self.start()
   File "/home/jhs/.local/lib/python3.6/site-packages/pyrealsense/core.py", line 36, in start
     _check_error(e)
   File "/home/jhs/.local/lib/python3.6/site-packages/pyrealsense/utils.py", line 46, in _check_error
     pp(lrs.rs_get_error_message, e))
 pyrealsense.utils.RealsenseError: rs_create_context(api_version:11203) crashed with: UVCIOC_CTRL_QUERY:UVC_GET_CUR error 56, Invalid request code

world - [INFO] launchables.world: Process shutting down.

Anyone knows how to solve this error?

Thank you.

**Comment by papr** [comment]
Intel has dropped the official support for the R200 product as well as its drivers and libraries. Therefore, we are not able to further maintain this video backend.
