### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by jhs0053** [pupil-labs/pupil#1486]
Hello.

I have run pupil software in Linux ubuntu 18.04.

I have got this error as:

world - [INFO] calibration_routines.screen_marker_calibration: Starting Calibration
 world - [ERROR] launchables.world: Process Capture crashed with trace:
 Traceback (most recent call last):
   File "/home/jhs/pupil_backup/pupil_src/launchables/world.py", line 607, in world
     p.recent_events(events)
   File "/home/jhs/pupil_backup/pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py", line 306, in recent_events
     self.markers = self.circle_tracker.update(gray_img)
   File "/home/jhs/pupil_backup/pupil_src/shared_modules/circle_detector.py", line 59, in update
     markers = self._check_frame(img)
   File "/home/jhs/pupil_backup/pupil_src/shared_modules/circle_detector.py", line 99, in _check_frame
     ellipses_list = find_pupil_circle_marker(img, scale)
   File "/home/jhs/pupil_backup/pupil_src/shared_modules/circle_detector.py", line 249, in find_pupil_circle_marker
     min_ellipses_num=2,
   File "/home/jhs/pupil_backup/pupil_src/shared_modules/circle_detector.py", line 431, in find_concentric_circles
     edge, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_TC89_KCOS
 ValueError: not enough values to unpack (expected 3, got 2)

world - [INFO] launchables.world: Process shutting down.
 eye1 - [INFO] launchables.eye: Process shutting down.
 eye0 - [INFO] launchables.eye: Process shutting down.

I have got the solution for this problem in the site as: https://github.com/pupil-labs/pupil-docs/issues/233

I have installed opencv through following command in pupil labs website: sudo apt install python3-opencv libopencv-dev.

Anyone knows how to upgrade opencv version without error?

I am new to linux ubuntu. Please let me know specific command or other actions.

Thank you.

**Comment by papr** [comment]
Fixed via #1495
