### ISSUE TITLE
Pupil Player - Exception: Bad value [position        ...]

### ISSUE THREAD

**Issue by robbeofficial** [pupil-labs/pupil#15]
sometimes i get the following exception when trying to load a recorded session with pupil player. it looks like it's trying to seek to a position after the end of the recording. this problem can be resolved by deleting the "player_settings" directory.

./pupil_player /home/mpi/Downloads/Pupil_Capture/recordings/2014_07_31/002/
ERROR(AntTweakBar) >> Bad value
ERROR(AntTweakBar) >> Bad value [position        ...]
Traceback (most recent call last):
  File "<string>", line 478, in <module>
  File "<string>", line 389, in main
  File "/home/mkassner/pupil/deploy_player/build/bundle/out00-PYZ.pyz/vis_circle", line 54, in init_gui
  File "/home/mkassner/pupil/deploy_player/build/bundle/out00-PYZ.pyz/atb", line 198, in __init__
  File "/home/mkassner/pupil/deploy_player/build/bundle/out00-PYZ.pyz/atb", line 773, in define
  File "/home/mkassner/pupil/deploy_player/build/bundle/out00-PYZ.pyz/atb", line 20, in check_error
Exception: Bad value [position        ...]

machine: Ubuntu 12.10, i686, 3.5.0-49-generic

**Comment by mkassner** [comment]
Since we replace atb completely this will not be fixed.
