### ISSUE TITLE
Linux Bundle Unified Capture Backend feedback

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#151]
Hi everyone,

I am testing the bundle right now and will document my experience. This post will receive incremental updates.

- installation:
    - 1 - Ubuntu Software Center shows License as "Unknown";

**Comment by cpicanco** [comment]
First execution gives that error. Eye windows opened, but in random image mode.

´´´
Traceback (most recent call last):
  File "<string>", line 141, in <module>
  File "<string>", line 132, in main
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/world", line 140, in world
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/video_capture", line 73, in autoCreateCapture
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/video_capture.uvc_capture", line 53, in __init__
  File "uvc.pyx", line 338, in uvc.Capture.__init__ (uvc.c:9340)
  File "uvc.pyx", line 541, in uvc.Capture._enumerate_controls (uvc.c:12043)
  File "controls.pxi", line 141, in uvc.Control.__init__ (uvc.c:7388)
  File "controls.pxi", line 169, in uvc.Control._uvc_get (uvc.c:7821)
Exception: Error: Input/output error.
´´´

Second trial gives the same error, but eye window was loaded successfully.

```
rafael@B14HM21:~$ pupil_capture 
Traceback (most recent call last):
  File "<string>", line 141, in <module>
  File "<string>", line 132, in main
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/world", line 140, in world
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/video_capture", line 73, in autoCreateCapture
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/video_capture.uvc_capture", line 53, in __init__
  File "uvc.pyx", line 338, in uvc.Capture.__init__ (uvc.c:9340)
  File "uvc.pyx", line 541, in uvc.Capture._enumerate_controls (uvc.c:12043)
  File "controls.pxi", line 141, in uvc.Control.__init__ (uvc.c:7388)
  File "controls.pxi", line 169, in uvc.Control._uvc_get (uvc.c:7821)
Exception: Error: Input/output error.
EYE0 Process [WARNING] video_capture.uvc_capture : 90fps capture mode not available at ((640, 480)) on 'Microsoft? LifeCam HD-5000'. Selected 30fps. 
EYE0 Process [ERROR] uvc : Can't stop stream: Error:'Operation timed out.'. Will ignore this and try to continue.
```

**Comment by mkassner** [comment]
Hi,

I think the microsoft cameras of Pupil Dev are a bit stubbern and need to asked a few times to stream mjpeg. Thus your first error. Do I understand though that ultimately it does work?

**Comment by cpicanco** [comment]
No @mkassner , world does not work. I could try again with more instructions.

**Comment by mkassner** [comment]
Hi,

what cameras are you using again?

M

**Comment by cpicanco** [comment]
Logitech C615 -> world
Microsoft HD-5000 -> eye

**Comment by mkassner** [comment]
Yes, I think there must be a problem with this type of camera (c615)... You could build pyvc on your machine and try to debug it. Its hard for me todo because I dont have that camera.

**Comment by cpicanco** [comment]
I will explore this option after finishing some on going work with the old version. Are there build instruction? What is the state of the docs?

**Comment by mkassner** [comment]
I have updated all the instructions on the wiki. Build instructions are
there.

**Comment by cpicanco** [comment]
Thank you @mkassner !

**Comment by cpicanco** [comment]
Ahhhhhh... please, when you guys expect to merge the unified branch with the master?

**Comment by mkassner** [comment]
Already happened :-)

M

**Comment by cpicanco** [comment]
Oh! Good.
