### ISSUE TITLE
Linux - cannot import name device_list

### ISSUE THREAD

**Issue by adjivas** [pupil-labs/pupil#157]
Hi @all!

I try to install Pupil on my Archlinux and I encounter this problem.

Thank you for your helps!

```shell
[adjivas@./pupil/pupil_src/player]$ python main.py
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    from video_capture import autoCreateCapture,EndofVideoFileError,FileSeekError,FakeCapture
  File "/home/adjivas/Project/pupil/pupil_src/shared_modules/video_capture/__init__.py", line 39, in <module>
    from uvc_capture import Camera_Capture,device_list,CameraCaptureError
  File "/home/adjivas/Project/pupil/pupil_src/shared_modules/video_capture/uvc_capture.py", line 12, in <module>
    from uvc import device_list
ImportError: cannot import name device_list
```

***
About my Python:
```python
Python 2.7.10 (default, May 26 2015, 04:16:29)
[GCC 5.1.0] on linux2
```

**Comment by mkassner** [comment]
hi,

please make sure to delete the dir 'uvc' in shared modules/video_capture

Best,

Moritz

**Comment by adjivas** [comment]
@mkassner, thank you for your response; at **./pupil_src/shared_modules/video_capture**, there isn't a **%uvc%/** folder:
```shell
-rw-r--r-- 1 adjivas users  6995 Jun 29 23:00 av_file_capture.py
-rw-r--r-- 1 adjivas users  3609 Jun 29 23:00 fake_capture.py
-rw-r--r-- 1 adjivas users  6673 Jun 29 23:00 file_capture.py
-rw-r--r-- 1 adjivas users  3412 Jun 29 23:00 __init__.py
-rw-r--r-- 1 adjivas users 11241 Jun 29 23:00 uvc_capture.py
```
My **./pupil_src** is a initial git clone from https://github.com/pupil-labs/pupil.git, I haven't modified this project yet.

**Comment by mkassner** [comment]
hi,

I merged some code,

can you try again?

Please make sure to have the right version of pyuvc installed:
https://github.com/pupil-labs/pyuvc

**Comment by adjivas** [comment]
Hi dear @mkassner.

I have new reinstalled the pyuvc's package with this lines:
```shell
$ git clone https://github.com/pupil-labs/pyuvc && cd pyuvc
$ sudo python setup.py install
  running install
  running build
  running build_ext
  running install_lib
  copying build/lib.linux-x86_64-2.7/uvc.so -> /usr/lib/python2.7/site-packages
  running install_egg_info
  Writing /usr/lib/python2.7/site-packages/uvc-0.1-py2.7.egg-info
```
And check the **example.py**.
```shell
$ python example.py # <- Strange bug, I will investigate.
  Traceback (most recent call last):
    File "example.py", line 11, in <module>
      dev_list =  uvc.device_list()
  AttributeError: 'module' object has no attribute 'device_list'
$ sudo python example.py  # <- Good work.
  156
  1
  0
  0
  0
  0
  0
  133
  5
  2
  83
  20
  4500
  1
  Microsoft? LifeCam HD-6000 for Notebooks
  Capture device
           device_address:3
           name:Microsoft? LifeCam HD-6000 for Notebooks
           idVendor:1118
           serialNumber:unknown
           bus_number:4
           idProduct:1903
           uid:4:3
           manufacturer:Microsoft
  Estimated / selected altsetting bandwith : 309 / 512.
  DEBUG:uvc:Stream start.
  DEBUG:uvc:Could not get Frame. Error: "Operation timed out.". Tried 0 times.
  ERROR:uvc:Can't stop stream: Error:'Operation timed out.'. Will ignore this and try to continue.
  DEBUG:uvc:Stream closed
  DEBUG:uvc:Stream stop.
  DEBUG:uvc:UVC device closed.
```
The files ***/usr/lib/python2.7/site-package/uvc-0.1-py2.7.egg-info*** and ***/usr/lib/python2.7/site-package/uvc.so*** was good created.
About mention "device_list", there was found at:
```shell
% grep -Ril "device_list" /usr/lib/python2.7/site-packages/
  /usr/lib/python2.7/site-packages/uvc.so
% grep -Ril "device_list" $HOME/pyuvc/
  /home/adjivas/pyuvc/uvc.pyx
  /home/adjivas/pyuvc/cuvc.pxd
  /home/adjivas/pyuvc/example.py
  /home/adjivas/pyuvc/build/lib.linux-x86_64-2.7/uvc.so
  /home/adjivas/pyuvc/build/temp.linux-x86_64-2.7/uvc.o
  /home/adjivas/pyuvc/uvc.c
  /home/adjivas/pyuvc/README.md
```
***
About **pupil-labs/pupil.git**, not news:
```shell
$ git clone https://github.com/pupil-labs/pupil.git && cd pupil
$ python pupil_src/player/main.py
  Traceback (most recent call last):
    File "pupil_src/player/main.py", line 90, in <module>
      from video_capture import autoCreateCapture,EndofVideoFileError,FileSeekError,FakeCapture
    File "/home/adjivas/pupil/pupil_src/shared_modules/video_capture/__init__.py", line 39, in <module>
      from uvc_capture import Camera_Capture,device_list,CameraCaptureError
    File "/home/adjivas/pupil/pupil_src/shared_modules/video_capture/uvc_capture.py", line 12, in <module>
      from uvc import device_list
  ImportError: cannot import name device_list

```

**Comment by mkassner** [comment]
can you please try this:

open terminal:
```
python
from uvc import device_list
```

if you still get this error you must have a different module called uvc installed. Please remove it and everything should work.

M

**Comment by adjivas** [comment]
At */home/adjivas/pyuvc*, the command *python -c "from uvc import device_list"* work.
At */home/adjivas/pupil*, the command *python -c "from uvc import device_list"* fail.
```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name device_list
```

**Comment by mkassner** [comment]
did you do:

sudo python setup.py install inside pyuvc?

Best,

Moritz

**Comment by adjivas** [comment]
It's fixed with a *sudo chmod adjivas /usr/lib/python2.7*:
```python
[adjivas@adjivas ~] git clone https://github.com/pupil-labs/pyuvc && cd pyuvc
[adjivas@adjivas pyuvc]$ python setup.py install
...
uvc.c:12911:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   __pyx_v_processing_unit = uvc_get_processing_units(__pyx_v_self->devh);
                           ^
uvc.c:12920:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   __pyx_v_extension_unit = uvc_get_extension_units(__pyx_v_self->devh);
                          ^
uvc.c: In function ‘__pyx_f_3uvc_7Capture__enumerate_formats’:
uvc.c:13486:23: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   __pyx_v_format_desc = uvc_get_format_descs(__pyx_v_self->devh);
creating build/lib.linux-x86_64-2.7
gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-2.7/uvc.o /opt/libjpeg-turbo/lib64/libturbojpeg.a -L/usr/lib -luvc -lrt -lpython2.7 -o build/lib.linux-x86_64-2.7/uvc.so -Wl,-R/usr/local/lib/
running install_lib
copying build/lib.linux-x86_64-2.7/uvc.so -> /usr/lib/python2.7/site-packages
running install_egg_info
Removing /usr/lib/python2.7/site-packages/uvc-0.2-py2.7.egg-info
Writing /usr/lib/python2.7/site-packages/uvc-0.2-py2.7.egg-info
```
But it's don't fix the import of *device_list*:
```python
[adjivas@adjivas pyuvc]$ python -c "from uvc import device_list"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name device_list
```
And the example of repository:
```python
[adjivas@adjivas pyuvc]$ python example.py
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    dev_list =  uvc.device_list()
AttributeError: 'module' object has no attribute 'device_list'
```

**Comment by mkassner** [comment]
Hi,

since this works on my machine and other users it must be a problem with
your setup.

My guess is that you either have an older version of pyuvc or some other
module with the same name. You will need to fix that.

Best,

Moritz

**Comment by mkassner** [comment]
hi, 
have you been able to resolve this?

**Comment by adjivas** [comment]
Hi @mkassner,

In two days, I will again investigate about this problem.
Out of curiosity, I have also try to automate this solution of deployment: [adjivas/docker-pupil] (https://github.com/adjivas/docker-pupil/).

**Comment by adjivas** [comment]
Hi @mkassner,

Today, this is a new try, I have reproduced this incident in this [container](https://github.com/adjivas/archpupil/blob/master/Dockerfile). I think it proves that:
- There is not older version of ***pyuvc***:
[RUN git clone https://github.com/pupil-labs/pyuvc /tmp/pyuvc](https://github.com/adjivas/archpupil/blob/master/Dockerfile#L43) ;
- There is not some other module of ***pyuvc*** with the same name:
```shell
[root@archpupil ~]# ls -d1 /usr/lib/python2.7/site-packages/*/
[root@archpupil site-packages]# ls -d1 */
/usr/lib/python2.7/site-packages/Cython-0.22.1-py2.7.egg-info/
/usr/lib/python2.7/site-packages/Cython/
/usr/lib/python2.7/site-packages/IPython/
/usr/lib/python2.7/site-packages/OpenGL/
/usr/lib/python2.7/site-packages/PyOpenGL-3.1.0-py2.7.egg-info/
/usr/lib/python2.7/site-packages/_markerlib/
/usr/lib/python2.7/site-packages/av-0.2.4-py2.7-linux-x86_64.egg/
/usr/lib/python2.7/site-packages/avahi/
/usr/lib/python2.7/site-packages/avahi_discover/
/usr/lib/python2.7/site-packages/numexpr-2.4.3-py2.7.egg-info/
/usr/lib/python2.7/site-packages/numexpr/
/usr/lib/python2.7/site-packages/numpy/
/usr/lib/python2.7/site-packages/pkg_resources/
/usr/lib/python2.7/site-packages/psutil-3.0.1-py2.7.egg-info/
/usr/lib/python2.7/site-packages/psutil/
/usr/lib/python2.7/site-packages/pygame/
/usr/lib/python2.7/site-packages/pyglui/
/usr/lib/python2.7/site-packages/pyximport/
/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg-info/
/usr/lib/python2.7/site-packages/setuptool
```

Please, can you check my procedure of installation described in my [container](https://github.com/adjivas/archpupil/blob/master/Dockerfile)? To see if I have forgotten a flag when I compile any dependency or another problem.

Remember, this linux distribution haven't the same package manager.

If you want test my [container](https://github.com/adjivas/archpupil/blob/master/Dockerfile), you can use these lines in a Linux configuration that has the Docker software:
```shell
[adjivas@adjivas ~]$ git clone git@github.com:adjivas/archpupil.git /tmp/archpupil && cd /tmp/archpupil
[adjivas@adjivas archpupil]$ docker build -t "archpupil" . ;
...
[adjivas@adjivas archpupil]$ docker run --rm -it  --device /dev/video0 --device /dev/video1 --device /dev/video2 -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/adjivas/.Xauthority:/tmp/.Xauthority -v /dev/snd:/dev/snd -e DISPLAY=unix:0.0 -e XAUTHORITY=/tmp/.Xauthority -h archpupil "archpupil" ;
[root@archpupil ~]# cd /tmp/pyuvc
[root@archpupil pyuvc]# python2 setup.py install
Compiling uvc.pyx because it changed.
Cythonizing uvc.pyx
running install
running build
running build_ext
building 'uvc' extension
creating build
creating build/temp.linux-x86_64-2.7
gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -I/usr/lib/python2.7/site-packages/numpy/core/include -I/opt/libjpeg-turbo/include -I/usr/include/python2.7 -c uvc.c -o build/temp.linux-x86_64-2.7/uvc.o
In file included from /usr/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from uvc.c:289:
/usr/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
uvc.c: In function '__pyx_f_3uvc_7Capture__start':
uvc.c:11937:20: error: too many arguments to function 'uvc_stream_start'
   __pyx_v_status = uvc_stream_start(__pyx_v_self->strmh, NULL, NULL, __pyx_v_self->_bandwidth_factor, 0);
                    ^
In file included from uvc.c:285:0:
/usr/local/include/libuvc/libuvc.h:529:13: note: declared here
 uvc_error_t uvc_stream_start(uvc_stream_handle_t *strmh,
             ^
uvc.c: In function '__pyx_f_3uvc_7Capture__enumerate_controls':
uvc.c:12893:26: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
   __pyx_v_input_terminal = uvc_get_input_terminals(__pyx_v_self->devh);
                          ^
uvc.c:12902:27: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
   __pyx_v_output_terminal = uvc_get_output_terminals(__pyx_v_self->devh);
                           ^
uvc.c:12911:27: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
   __pyx_v_processing_unit = uvc_get_processing_units(__pyx_v_self->devh);
                           ^
uvc.c:12920:26: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
   __pyx_v_extension_unit = uvc_get_extension_units(__pyx_v_self->devh);
                          ^
uvc.c: In function '__pyx_f_3uvc_7Capture__enumerate_formats':
uvc.c:13486:23: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
   __pyx_v_format_desc = uvc_get_format_descs(__pyx_v_self->devh);
                       ^
error: command 'gcc' failed with exit status 1
```

**Comment by mkassner** [comment]
Hi,

I found the error: You are not using our fork of libuvc: Please use https://github.com/pupil-labs/libuvc instead. Then it will work.

**Comment by adjivas** [comment]
Hi and thank you **@mkassner**!

I will investigate to next problems but It's fix my issue. I wish in the future to automate the installation of *pupil* with this *dockerfile*.
