### ISSUE TITLE
Linux Bundle: Pupil Player v.0.5.2 - Vis Light Points Plugin

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#158]
Hi there!

The plugin chrashes the player, if you play the video:

Player [INFO] video_capture.file_capture : Filecapture is not a realtime source. -NOW- will be the current timestamp
Traceback (most recent call last):
  File "<string>", line 478, in <module>
  File "<string>", line 420, in main
  File "/home/mkassner/pupil/deploy_player/build/bundle/out00-PYZ.pyz/vis_light_points", line 39, in update
  File "/home/mkassner/pupil/deploy_player/build/bundle/out00-PYZ.pyz/methods", line 448, in denormalize
KeyError: 0

**Comment by mkassner** [comment]
thanks for finding this bug. Fixed in v0.5_restruct branch.
