### ISSUE TITLE
Pupil Capture shuts down because of libstdc++

### ISSUE THREAD

**Issue by ranran9991** [pupil-labs/pupil#1636]
OS: Ubuntu 16.04

Trying to run latest pupil_capture downloaded from packaged binaries.
When running by clicking the icon I see the icon of the program but it just waits a few seconds and then closes.

When running from the command line I get the following error:
```
world - [INFO] launchables.world: Application Version: 1.15.65
world - [INFO] launchables.world: System Info: User: root, Platform: Linux, Machine: ArielsLab, Release: 4.15.0-60-generic, Version: #67~16.04.1-Ubuntu SMP Mon Aug 26 08:57:33 UTC 2019
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "launchables/world.py", line 136, in world
  File "/home/pupil-labs/.pyenv/versions/3.6.0/envs/general/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "shared_modules/pupil_detectors/__init__.py", line 21, in <module>
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/pupil_capture/pupil_detectors/detector_3d.cpython-36m-x86_64-linux-gnu.so)

world - [INFO] launchables.world: Process shutting down.
```
Would love some help on how to fix the issue

**Comment by ranran9991** [comment]
Fixed using instructions from here
https://github.com/lhelontra/tensorflow-on-arm/issues/13
