### ISSUE TITLE
Timestamp error when recording

### ISSUE THREAD

**Issue by marhkb** [pupil-labs/pupil#1657]
I just had a subject here and wanted to make a recording. Several attempts, no success.
Eye process crashes.

last lines of log
```
world - [WARNING] video_capture.uvc_backend: Received frame with invalid timestamp. This can happen after a disconnect. Frame will be dropped!
eye0 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
eye0 - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID0 at resolution (320, 240)
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the -global-isel-abort option: may only occur zero or one times!
eye0 - [WARNING] launchables.eye: Process started.
Estimated / selected altsetting bandwith : 200 / 256. 
!!!!Packets per transfer = 32 frameInterval = 83263
eye0 - [WARNING] video_capture.uvc_backend: Received frame with invalid timestamp. This can happen after a disconnect. Frame will be dropped!
world - [INFO] recorder: Started Recording.
eye0 - [INFO] launchables.eye: Will save eye video to: /home/marcus/recordings/2019_09_26/005/
*** Correcting clock frequency to 15000086
*** Correcting clock frequency to 15001000
eye0 - [ERROR] launchables.eye: Process Eye0 crashed with trace:
Traceback (most recent call last):
  File "launchables/eye.py", line 716, in eye
  File "shared_modules/av_writer.py", line 155, in write_video_frame
ValueError: Non-monotonic timestamps!Last timestamp: 75951.617444. Given timestamp: 75951.605253
```

**Comment by papr** [comment]
Hi @marhkb 
It is unfortunate to hear that this happened during your data collection! Is it possible that you are using some kind of time sync?

Please let us know which Pupil Capture and which Linux operating system you are using.

**Comment by marhkb** [comment]
Hi,

No there is no time sync plugin loaded. Just 'Accurracy Visualizer', 'Fixation Detector' and 'Surface Tracker'

from screenfetch:
```
 OS: Arch Linux 
 Kernel: x86_64 Linux 5.3.1-zen1-1-zen
 Uptime: 1d 1m
 Packages: 1650
 Shell: zsh 5.7.1
 Resolution: 1920x1200
 DE: KDE 5.62.0 / Plasma 5.16.5
 WM: KWin
 GTK Theme: Materia-dark-compact [GTK2/3]
 Icon Theme: Papirus-Dark
 Font: Fira Sans Regular
 CPU: Intel Core i5-4670 @ 4x 3.8GHz [27.8°C]
 GPU: AMD Radeon HD 7800 Series (PITCAIRN, DRM 3.33.0, 5.3.1-zen1-1-zen, LLVM 8.0.1)
 RAM: 4022MiB / 15953MiB
```

**Comment by papr** [comment]
Mmh, in this case I suspect that there is a problem with the calculation of the camera hardware timestamps in Arch. We have only tested it under Ubuntu. :-/

Reference: https://github.com/pupil-labs/libuvc/blob/master/src/stream.c#L534

**Comment by papr** [comment]
We have encountered this issue on one of our Linux machines, too. I will let you know as soon as we find out more.

**Comment by samtuhka** [comment]
We also have this problem on our Ubuntu machine. For whatever reason, it keeps continually correcting the clock frequency during the recording.
```
eye0 - [WARNING] video_capture.uvc_backend: Received frame with invalid timestamp. This can happen after a disconnect. Frame will be dropped!
world - [INFO] recorder: Started Recording.
eye1 - [INFO] launchables.eye: Will save eye video to: /home/tru/recordings/session_pupilli_testi/001/
eye0 - [INFO] launchables.eye: Will save eye video to: /home/tru/recordings/session_pupilli_testi/001/
*** Correcting clock frequency to 14999469
*** Correcting clock frequency to 14999707
*** Correcting clock frequency to 14999781
*** Correcting clock frequency to 14999485
*** Correcting clock frequency to 14999719
*** Correcting clock frequency to 14999799
*** Correcting clock frequency to 14999492
*** Correcting clock frequency to 14999727
*** Correcting clock frequency to 14999506
*** Correcting clock frequency to 14999877
*** Correcting clock frequency to 14999842
*** Correcting clock frequency to 15000763
eye1 - [ERROR] launchables.eye: Process Eye1 crashed with trace:
Traceback (most recent call last):
  File "launchables/eye.py", line 716, in eye
  File "shared_modules/av_writer.py", line 155, in write_video_frame
ValueError: Non-monotonic timestamps!Last timestamp: 3755.734155. Given timestamp: 3755.727532

*** Correcting clock frequency to 15000520
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "launchables/world.py", line 619, in world
  File "shared_modules/recorder.py", line 439, in recent_events
  File "shared_modules/av_writer.py", line 155, in write_video_frame
ValueError: Non-monotonic timestamps!Last timestamp: 3755.825783. Given timestamp: 3755.814749

world - [INFO] launchables.world: Process shutting down.
eye0 - [INFO] launchables.eye: Done recording eye.
eye0 - [INFO] launchables.eye: Process shutting down.
```

**Comment by papr** [comment]
This issue has been worked around in #1812
