### ISSUE TITLE
pupil_capture_v0.3.9.3_Linux_i686.zip fails to find OpenGL

### ISSUE THREAD

**Issue by jampekka** [pupil-labs/pupil#17]
Launching the pupil_capture (Arch Linux updated today, i686) results in a error pasted in the end of this post. This may be due to incompability of PyOpenGL 3.0 < rc1 with PyInstaller (see [here](http://www.pyinstaller.org/wiki/SupportedPackages)). Running the git master works on the same setup.

```
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
Traceback (most recent call last):
  File "<string>", line 80, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/eye", line 17, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/atb", line 16, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/atb.raw", line 20, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/OpenGL.GL", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/OpenGL.raw.GL", line 6, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/OpenGL.raw.GL.constants", line 7, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/OpenGL.platform", line 36, in <module>
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/OpenGL.platform", line 27, in _load
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/OpenGL.plugins", line 14, in load
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/OpenGL.plugins", line 28, in importByName
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/OpenGL.platform.glx", line 8, in <module>
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/OpenGL.platform.glx", line 20, in GLXPlatform
ImportError: ('Unable to load OpenGL library', 'GL: cannot open shared object file: No such file or directory', 'GL', None)
```

**Comment by mkassner** [comment]
Since we are moving to v0.4 I m closing this.
