### ISSUE TITLE
Error while installing pyglui in Ubuntu 18.04

### ISSUE THREAD

**Issue by yves84** [pupil-labs/pupil#1710]
```
Collecting git+https://github.com/pupil-labs/pyglui
  Cloning https://github.com/pupil-labs/pyglui to /tmp/pip-req-build-3p0cr4gw
  Running command git clone -q https://github.com/pupil-labs/pyglui /tmp/pip-req-build-3p0cr4gw
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/yves/.local/share/virtualenvs/pupil-gu_hiFUp/bin/python3 /home/yves/.local/share/virtualenvs/pupil-gu_hiFUp/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp032jtilf
       cwd: /tmp/pip-req-build-3p0cr4gw
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/home/yves/.local/share/virtualenvs/pupil-gu_hiFUp/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/yves/.local/share/virtualenvs/pupil-gu_hiFUp/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/yves/.local/share/virtualenvs/pupil-gu_hiFUp/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-rmfhdv3z/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-rmfhdv3z/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-rmfhdv3z/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 13, in <module>
      from glew_pxd import generate_pxd
  ModuleNotFoundError: No module named 'glew_pxd'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/yves/.local/share/virtualenvs/pupil-gu_hiFUp/bin/python3 /home/yves/.local/share/virtualenvs/pupil-gu_hiFUp/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp032jtilf Check the logs for full command output.
```

I'm using Ubuntu 18.04 and i install the python deps in a virt env (pipenv).

thx

**Comment by yves84** [comment]
Uh i'm Sorry. Maybe it's better to post this bug in the right Repo...
