### ISSUE TITLE
Error while opening pupil Capture

### ISSUE THREAD

**Issue by sparshbaluni07** [pupil-labs/pupil#1745]
Hello there,
Whenever I try to open pupil capture I get this error;
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "launchables\world.py", line 138, in world
  File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "shared_modules\pupil_detectors\__init__.py", line 13, in <module>
ImportError: DLL load failed: The specified module could not be found.
world - [INFO] launchables.world: Process shutting down.

Thanks,

**Comment by pfaion** [comment]
Hi, please download and run the file `vc_redist.x64.exe` file from [the official Microsoft support page](https://support.microsoft.com/en-ca/help/2977003/the-latest-supported-visual-c-downloads). Afterwards, Pupil should start up as expected.
