### ISSUE TITLE
Failed to build pupil-detectors ERROR: Could not build wheels for pupil-detectors which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by KamranBinaee** [pupil-labs/pupil#1779]
Hi,

I'm trying to run from source and except pupil-detectors everything else seems to be installed perfectly fine. I'm running on Ubuntu 18 and this is the log of the error. 
I appreciate your help.
Thanks
```
(myPython3_directory) veddy@vedbpom01:~/myPython3_directory$ pip install pupil-detectors
Collecting pupil-detectors
  Using cached https://files.pythonhosted.org/packages/28/10/2517642dc8ba66b087f0722472decdbf95b98e1ad090e944a60f121dcffa/pupil-detectors-1.0.2.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in ./myPython3_directory/lib/python3.6/site-packages (from pupil-detectors) (1.18.0)
Requirement already satisfied: cysignals in ./myPython3_directory/lib/python3.6/site-packages (from pupil-detectors) (1.10.2)
Requirement already satisfied: Cython>=0.28 in ./myPython3_directory/lib/python3.6/site-packages (from cysignals->pupil-detectors) (0.29.14)
Building wheels for collected packages: pupil-detectors
  Building wheel for pupil-detectors (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/veddy/myPython3_directory/myPython3_directory/bin/python /home/veddy/myPython3_directory/myPython3_directory/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpau_hprw3
       cwd: /tmp/pip-install-1d5pmmxz/pupil-detectors
  Complete output (36 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/pupil_detectors
  copying src/pupil_detectors/utils.py -> build/lib.linux-x86_64-3.6/pupil_detectors
  copying src/pupil_detectors/__init__.py -> build/lib.linux-x86_64-3.6/pupil_detectors
  creating build/lib.linux-x86_64-3.6/pupil_detectors/detector_3d
  copying src/pupil_detectors/detector_3d/__init__.py -> build/lib.linux-x86_64-3.6/pupil_detectors/detector_3d
  creating build/lib.linux-x86_64-3.6/pupil_detectors/detector_2d
  copying src/pupil_detectors/detector_2d/__init__.py -> build/lib.linux-x86_64-3.6/pupil_detectors/detector_2d
  running build_ext
  building 'pupil_detectors.detector_base' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  creating build/temp.linux-x86_64-3.6/src/pupil_detectors
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/veddy/myPython3_directory/myPython3_directory/include -I/usr/include/python3.6m -c src/pupil_detectors/detector_base.cpp -o build/temp.linux-x86_64-3.6/src/pupil_detectors/detector_base.o -w -std=c++11 -O2
  x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/pupil_detectors/detector_base.o -o build/lib.linux-x86_64-3.6/pupil_detectors/detector_base.cpython-36m-x86_64-linux-gnu.so
  building 'pupil_detectors.detector_2d.detector_2d' extension
  creating build/temp.linux-x86_64-3.6/src/pupil_detectors/detector_2d
  creating build/temp.linux-x86_64-3.6/src/singleeyefitter
  creating build/temp.linux-x86_64-3.6/src/singleeyefitter/ImageProcessing
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc -Isrc/pupil_detectors/detector_2d -Isrc/shared_cpp/include -Isrc/singleeyefitter/ -I/tmp/pip-build-env-jbq05_sv/overlay/lib/python3.6/site-packages/numpy/core/include -I/usr/local/opt/opencv/include -I/usr/local/opt/opencv@3/include -I/usr/local/include/opencv4 -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/home/veddy/myPython3_directory/myPython3_directory/include -I/usr/include/python3.6m -c src/pupil_detectors/detector_2d/detector_2d.cpp -o build/temp.linux-x86_64-3.6/src/pupil_detectors/detector_2d/detector_2d.o -w -std=c++11 -O2
  In file included from src/singleeyefitter/mathHelper.h:7:0,
                   from src/shared_cpp/include/geometry/Conic.h:5,
                   from src/singleeyefitter/projection.h:8,
                   from src/shared_cpp/include/common/types.h:8,
                   from src/pupil_detectors/detector_2d/detector_2d.cpp:670:
  src/shared_cpp/include/common/traits.h:5:10: fatal error: ceres/jet.h: No such file or directory
   #include <ceres/jet.h>
            ^~~~~~~~~~~~~
  compilation terminated.
  /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'zip_save'
    warnings.warn(msg)
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pupil-detectors
  Running setup.py clean for pupil-detectors
Failed to build pupil-detectors
ERROR: Could not build wheels for pupil-detectors which use PEP 517 and cannot be installed directly
```

**Comment by pfaion** [comment]
Hi @KamranBinaee 
it looks like you are missing the ceres dependency. Did you install all dependencies for Pupil as documented in [here](https://github.com/pupil-labs/pupil/blob/master/docs/dependencies-ubuntu18.md)?

**Comment by KamranBinaee** [comment]
Apparently it wasn't installed successfully! Let me make sure.
Thanks for your response

**Comment by KamranBinaee** [comment]
Thanks again!
I reinstalled the ceres and double checked the dependencies and now I'm able to run from the source without an error.
However, I am trying to use an [oCam](https://github.com/withrobot/oCam/tree/master/Examples) camera due to its wider angle as the world camera. As soon as I select it from the list of available USB cameras in the capture menu, it seems that it returns an empty frame size and shuts down the process. Could you please guide me through this?
Or I guess I can ask this through another issue/thread?

Thanks

Here's the log:
```
world - [INFO] video_capture.uvc_backend: Hardware timestamps not supported for oCam-1CGN-U-T. Using software timestamps.
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/veddy/pupil/pupil_src/launchables/world.py", line 624, in world
    handle_notifications(n)
  File "/home/veddy/pupil/pupil_src/launchables/world.py", line 410, in handle_notifications
    g_pool.plugin_by_name[noti["name"]], args=noti.get("args", {})
  File "/home/veddy/pupil/pupil_src/shared_modules/plugin.py", line 374, in add
    plugin_instance = new_plugin(self.g_pool, **args)
  File "/home/veddy/pupil/pupil_src/shared_modules/video_capture/uvc_backend.py", line 138, in __init__
    self.configure_capture(frame_size, frame_rate, uvc_controls)
  File "/home/veddy/pupil/pupil_src/shared_modules/video_capture/uvc_backend.py", line 232, in configure_capture
    self.frame_size = frame_size
  File "/home/veddy/pupil/pupil_src/shared_modules/video_capture/uvc_backend.py", line 470, in frame_size
    best_size_idx = sizes.index(min(sizes))
ValueError: min() arg is an empty sequence

```

**Comment by pfaion** [comment]
@KamranBinaee 
Please open another issue for this! I'll close this one.
