### ISSUE TITLE
Torch still loaded

### ISSUE THREAD

**Issue by pfaion** [pupil-labs/pupil#1782]
We removed the fingertip calibration, but other modules still use code from there, causing torch to be imported:
```
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/pfa/code/pupil/pupil_src/launchables/world.py", line 149, in world
    from plugin_manager import Plugin_Manager
  File "/home/pfa/code/pupil/pupil_src/shared_modules/plugin_manager.py", line 14, in <module>
    from calibration_routines import Calibration_Plugin, Gaze_Mapping_Plugin
  File "/home/pfa/code/pupil/pupil_src/shared_modules/calibration_routines/__init__.py", line 15, in <module>
    from .fingertip_calibration import Fingertip_Calibration
  File "/home/pfa/code/pupil/pupil_src/shared_modules/calibration_routines/fingertip_calibration/__init__.py", line 12, in <module>
    from calibration_routines.fingertip_calibration.fingertip_calibration import (
  File "/home/pfa/code/pupil/pupil_src/shared_modules/calibration_routines/fingertip_calibration/fingertip_calibration.py", line 13, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

Tested on Ubuntu 18.04

**Comment by pfaion** [comment]
I was on an old branch.
