### ISSUE TITLE
Using oCam as world camera and it returns empty frame

### ISSUE THREAD

**Issue by KamranBinaee** [pupil-labs/pupil#1783]
Hi,
I'm trying to use the [oCam](https://github.com/withrobot/oCam/tree/master/Products/oCam-1CGN-U-T) as the world camera and when I select it from the list of USB Cameras it returns an empty frame.

Is there any step that I'm missing in order to be able to use this camera?
Thanks

```
Estimated / selected altsetting bandwith : 151 / 256. 
!!!!Packets per transfer = 32 frameInterval = 82712
eye0 - [WARNING] video_capture.uvc_backend: Received frame with invalid timestamp. This can happen after a disconnect. Frame will be dropped!
eye1 - [INFO] camera_models: No user calibration found for camera Pupil Cam2 ID1 at resolution (192, 192)
eye1 - [INFO] camera_models: No pre-recorded calibration available
eye1 - [WARNING] camera_models: Loading dummy calibration
eye1 - [INFO] root: Refraction corrected 3D pupil detector not available
eye1 - [WARNING] launchables.eye: Process started.
Estimated / selected altsetting bandwith : 151 / 256. 
!!!!Packets per transfer = 32 frameInterval = 82712
eye1 - [WARNING] video_capture.uvc_backend: Received frame with invalid timestamp. This can happen after a disconnect. Frame will be dropped!
world - [INFO] video_capture.uvc_backend: Hardware timestamps not supported for oCam-1CGN-U-T. Using software timestamps.
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/veddy/pupil/pupil_src/launchables/world.py", line 624, in world
    handle_notifications(n)
  File "/home/veddy/pupil/pupil_src/launchables/world.py", line 410, in handle_notifications
    g_pool.plugin_by_name[noti["name"]], args=noti.get("args", {})
  File "/home/veddy/pupil/pupil_src/shared_modules/plugin.py", line 374, in add
    plugin_instance = new_plugin(self.g_pool, **args)
  File "/home/veddy/pupil/pupil_src/shared_modules/video_capture/uvc_backend.py", line 138, in __init__
    self.configure_capture(frame_size, frame_rate, uvc_controls)
  File "/home/veddy/pupil/pupil_src/shared_modules/video_capture/uvc_backend.py", line 232, in configure_capture
    self.frame_size = frame_size
  File "/home/veddy/pupil/pupil_src/shared_modules/video_capture/uvc_backend.py", line 470, in frame_size
    best_size_idx = sizes.index(min(sizes))
ValueError: min() arg is an empty sequence

world - [INFO] launchables.world: Process shutting down.
eye0 - [INFO] launchables.eye: Process shutting down.
eye1 - [INFO] launchables.eye: Process shutting down.

```

**Comment by papr** [comment]
Hi @KamranBinaee 

Apologies for the very delayed response.

It looks like this camera does not correctly announce the available frame sizes to pyuvc. Unfortunately, as this is a third-party camera, we are not able to reproduce or investigate this issue.

**Comment by KamranBinaee** [comment]
No problem, Thanks for letting me know. Actually, I had other issues with
this camera and ended up writing a wrapper for FLIR camera which has many
more parameters to set and much higher resolution. Thanks!

**Comment by papr** [comment]
@KamranBinaee Sounds great! Feel free to link the project in https://github.com/pupil-labs/pupil-community in case that you have published it.
