### ISSUE TITLE
Crash when recording in the dark

### ISSUE THREAD

**Issue by euryalus** [pupil-labs/pupil#1790]
Recording the world cam in complete darkness, with two eye cameras running at the same time, leads to crash due to non-monotonic timestamps. 

Here is the capture log: 
2020-01-17 11:39:47,169 - MainProcess - [INFO] os_utils: Disabled idle sleep.
2020-01-17 11:39:47,710 - world - [INFO] launchables.world: Application Version: 1.21.5
2020-01-17 11:39:47,710 - world - [INFO] launchables.world: System Info: User: kai, Platform: Darwin, Machine: Kais-MBP.fritz.box, Release: 18.7.0, Version: Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64
2020-01-17 11:39:47,833 - world - [DEBUG] video_capture: Install pyrealsense to use the Intel RealSense backend
2020-01-17 11:39:47,834 - world - [DEBUG] video_capture: Install pyrealsense2 to use the Intel RealSense backend for D400 series cameras
2020-01-17 11:39:48,190 - world - [DEBUG] pupil_apriltags: Testing possible hit: /Users/kai/Environments/pupil-labs/lib/python3.7/site-packages/pupil_apriltags/lib/libapriltag.3.dylib...
2020-01-17 11:39:48,191 - world - [DEBUG] pupil_apriltags: Found working clib at /Users/kai/Environments/pupil-labs/lib/python3.7/site-packages/pupil_apriltags/lib/libapriltag.3.dylib
2020-01-17 11:39:48,426 - world - [DEBUG] plugin: Loading plugin: UVC_Source with settings {'frame_size': [1280, 720], 'frame_rate': 30, 'check_stripes': True, 'exposure_mode': 'manual', 'name': 'Pupil Cam1 ID2', 'uvc_controls': {'Auto Exposure Mode': 8, 'Auto Exposure Priority': 1, 'Absolute Exposure Time': 157, 'Backlight Compensation': 1, 'Brightness': 0, 'Contrast': 32, 'Gain': 0, 'Power Line frequency': 1, 'Hue': 0, 'Saturation': 60, 'Sharpness': 2, 'Gamma': 100, 'White Balance temperature': 4600, 'White Balance temperature,Auto': 1}}
2020-01-17 11:39:48,459 - world - [DEBUG] uvc: Found device that mached uid:'20:26'
2020-01-17 11:39:48,468 - world - [DEBUG] uvc: Device '20:26' opended.
2020-01-17 11:39:48,469 - world - [DEBUG] uvc: avaible video modes: [{'size': (1920, 1080), 'rates': [30]}, {'size': (640, 480), 'rates': [120, 90, 60, 30]}, {'size': (1280, 720), 'rates': [60, 30]}, {'size': (1024, 768), 'rates': [30]}, {'size': (800, 600), 'rates': [60]}, {'size': (1280, 1024), 'rates': [30]}, {'size': (320, 240), 'rates': [120]}]
2020-01-17 11:39:48,470 - world - [DEBUG] uvc: Adding "Auto Exposure Mode" control.
2020-01-17 11:39:48,482 - world - [DEBUG] uvc: Adding "Auto Exposure Priority" control.
2020-01-17 11:39:48,492 - world - [DEBUG] uvc: Adding "Absolute Exposure Time" control.
2020-01-17 11:39:48,500 - world - [DEBUG] uvc: Adding "Backlight Compensation" control.
2020-01-17 11:39:48,506 - world - [DEBUG] uvc: Adding "Brightness" control.
2020-01-17 11:39:48,517 - world - [DEBUG] uvc: Adding "Contrast" control.
2020-01-17 11:39:48,529 - world - [DEBUG] uvc: Adding "Gain" control.
2020-01-17 11:39:48,546 - world - [DEBUG] uvc: Adding "Power Line frequency" control.
2020-01-17 11:39:48,558 - world - [DEBUG] uvc: Adding "Hue" control.
2020-01-17 11:39:48,566 - world - [DEBUG] uvc: Adding "Saturation" control.
2020-01-17 11:39:48,574 - world - [DEBUG] uvc: Adding "Sharpness" control.
2020-01-17 11:39:48,580 - world - [DEBUG] uvc: Adding "Gamma" control.
2020-01-17 11:39:48,586 - world - [DEBUG] uvc: Adding "White Balance temperature" control.
2020-01-17 11:39:48,593 - world - [DEBUG] uvc: Adding "White Balance temperature,Auto" control.
2020-01-17 11:39:48,624 - world - [INFO] camera_models: No user calibration found for camera Pupil Cam1 ID2 at resolution (1280, 720)
2020-01-17 11:39:48,624 - world - [INFO] camera_models: Loading pre-recorded calibration
2020-01-17 11:39:48,624 - world - [DEBUG] uvc: Setting mode: 1280,720,30
2020-01-17 11:39:48,790 - world - [DEBUG] plugin: Loading plugin: Pupil_Data_Relay with settings {}
2020-01-17 11:39:48,791 - world - [DEBUG] plugin: Loading plugin: Pupil_Remote with settings {'host': '0.0.0.0', 'use_primary_interface': True}
2020-01-17 11:39:48,802 - world - [DEBUG] plugin: Loading plugin: Dummy_Gaze_Mapper with settings {}
2020-01-17 11:39:48,802 - world - [DEBUG] plugin: Loading plugin: Log_Display with settings {}
2020-01-17 11:39:48,805 - world - [DEBUG] plugin: Loading plugin: UVC_Manager with settings {}
2020-01-17 11:39:48,816 - world - [DEBUG] plugin: Loading plugin: Screen_Marker_Calibration with settings {'fullscreen': True, 'marker_scale': 1.0, 'monitor_idx': 0}
2020-01-17 11:39:48,817 - world - [DEBUG] plugin: Loading plugin: Plugin_Manager with settings {}
2020-01-17 11:39:48,818 - world - [DEBUG] plugin: Loading plugin: System_Graphs with settings {'show_cpu': True, 'show_fps': True, 'show_conf0': True, 'show_conf1': True, 'show_dia0': False, 'show_dia1': False}
2020-01-17 11:39:48,825 - world - [DEBUG] plugin: Loading plugin: Display_Recent_Gaze with settings {}
2020-01-17 11:39:48,825 - world - [DEBUG] plugin: Loading plugin: Accuracy_Visualizer with settings {'outlier_threshold': 5.0, 'vis_mapping_error': True, 'vis_calibration_area': True}
2020-01-17 11:39:48,826 - world - [DEBUG] plugin: Loading plugin: Recorder with settings {'record_eye': True, 'session_name': '2020_01_17', 'user_info': {'name': '', 'additional_field': 'change_me'}, 'info_menu_conf': {}, 'show_info_menu': False, 'rec_root_dir': '/Users/kai/pupil_test/pupil/recordings', 'raw_jpeg': True}
2020-01-17 11:39:48,828 - world - [WARNING] launchables.world: Process started.
2020-01-17 11:39:48,906 - world - [DEBUG] uvc: Stream start.
2020-01-17 11:39:50,269 - eye1 - [DEBUG] video_capture: Install pyrealsense to use the Intel RealSense backend
2020-01-17 11:39:50,270 - eye1 - [DEBUG] video_capture: Install pyrealsense2 to use the Intel RealSense backend for D400 series cameras
2020-01-17 11:39:50,291 - eye1 - [INFO] root: Refraction corrected 3D pupil detector not available
2020-01-17 11:39:50,484 - eye1 - [DEBUG] plugin: Loading plugin: UVC_Source with settings {'frame_size': [400, 400], 'frame_rate': 120, 'check_stripes': True, 'exposure_mode': 'auto', 'name': 'Pupil Cam2 ID1', 'uvc_controls': {'Auto Exposure Mode': 1, 'Auto Exposure Priority': 0, 'Absolute Exposure Time': 18, 'Auto Focus': 0, 'Absolute Focus': 1, 'Absolute Iris ': 100, 'Scanning Mode ': 0, 'Zoom absolute control': 0, 'Pan control': 0, 'Tilt control': 0, 'Roll absolute control': 0, 'Privacy Shutter control': 0, 'Backlight Compensation': 121, 'Brightness': 0, 'Contrast': 48, 'Gain': 0, 'Power Line frequency': 1, 'Hue': 0, 'Saturation': 0, 'Sharpness': 2, 'Gamma': 200, 'White Balance temperature': 4600, 'White Balance temperature,Auto': 1}}
2020-01-17 11:39:50,502 - eye1 - [DEBUG] uvc: Found device that mached uid:'20:25'
2020-01-17 11:39:50,506 - eye1 - [DEBUG] uvc: Device '20:25' opended.
2020-01-17 11:39:50,506 - eye1 - [DEBUG] uvc: avaible video modes: [{'size': (400, 400), 'rates': [120, 90, 60, 30]}, {'size': (192, 192), 'rates': [200, 180, 120, 90, 60, 30]}]
2020-01-17 11:39:50,506 - eye1 - [DEBUG] uvc: Adding "Auto Exposure Mode" control.
2020-01-17 11:39:50,509 - eye1 - [DEBUG] uvc: Adding "Auto Exposure Priority" control.
2020-01-17 11:39:50,510 - eye1 - [DEBUG] uvc: Adding "Absolute Exposure Time" control.
2020-01-17 11:39:50,513 - eye1 - [DEBUG] uvc: Adding "Auto Focus" control.
2020-01-17 11:39:50,515 - eye1 - [DEBUG] uvc: Adding "Absolute Focus" control.
2020-01-17 11:39:50,519 - eye1 - [DEBUG] uvc: Adding "Absolute Iris " control.
2020-01-17 11:39:50,524 - eye1 - [DEBUG] uvc: Adding "Scanning Mode " control.
2020-01-17 11:39:50,525 - eye1 - [DEBUG] uvc: Adding "Zoom absolute control" control.
2020-01-17 11:39:50,529 - eye1 - [DEBUG] uvc: Adding "Pan control" control.
2020-01-17 11:39:50,533 - eye1 - [DEBUG] uvc: Adding "Tilt control" control.
2020-01-17 11:39:50,538 - eye1 - [DEBUG] uvc: Adding "Roll absolute control" control.
2020-01-17 11:39:50,541 - eye1 - [DEBUG] uvc: Adding "Privacy Shutter control" control.
2020-01-17 11:39:50,542 - eye1 - [DEBUG] uvc: Adding "Backlight Compensation" control.
2020-01-17 11:39:50,547 - eye1 - [DEBUG] uvc: Adding "Brightness" control.
2020-01-17 11:39:50,553 - eye1 - [DEBUG] uvc: Adding "Contrast" control.
2020-01-17 11:39:50,557 - eye1 - [DEBUG] uvc: Adding "Gain" control.
2020-01-17 11:39:50,561 - eye1 - [DEBUG] uvc: Adding "Power Line frequency" control.
2020-01-17 11:39:50,563 - eye1 - [DEBUG] uvc: Adding "Hue" control.
2020-01-17 11:39:50,567 - eye1 - [DEBUG] uvc: Adding "Saturation" control.
2020-01-17 11:39:50,571 - eye1 - [DEBUG] uvc: Adding "Sharpness" control.
2020-01-17 11:39:50,575 - eye1 - [DEBUG] uvc: Adding "Gamma" control.
2020-01-17 11:39:50,579 - eye1 - [DEBUG] uvc: Adding "White Balance temperature" control.
2020-01-17 11:39:50,583 - eye1 - [DEBUG] uvc: Adding "White Balance temperature,Auto" control.
2020-01-17 11:39:50,604 - eye1 - [INFO] camera_models: No user calibration found for camera Pupil Cam2 ID1 at resolution (400, 400)
2020-01-17 11:39:50,604 - eye1 - [INFO] camera_models: No pre-recorded calibration available
2020-01-17 11:39:50,604 - eye1 - [WARNING] camera_models: Loading dummy calibration
2020-01-17 11:39:50,604 - eye1 - [DEBUG] uvc: Setting mode: 400,400,120
2020-01-17 11:39:50,721 - eye1 - [WARNING] uvc: Could not set Value. 'Backlight Compensation'.
2020-01-17 11:39:50,787 - eye1 - [DEBUG] plugin: Loading plugin: Detector3DPlugin with settings {}
2020-01-17 11:39:50,789 - eye1 - [DEBUG] plugin: Loading plugin: PupilDetectorManager with settings {}
2020-01-17 11:39:50,790 - eye1 - [INFO] root: Refraction corrected 3D pupil detector not available
2020-01-17 11:39:50,790 - eye1 - [DEBUG] plugin: Loading plugin: UVC_Manager with settings {}
2020-01-17 11:39:50,804 - eye1 - [WARNING] launchables.eye: Process started.
2020-01-17 11:39:50,871 - eye1 - [DEBUG] uvc: Stream start.
2020-01-17 11:39:51,061 - eye1 - [DEBUG] plugin: Plugin <pupil_detector_plugins.detector_3d_plugin.Detector3DPlugin object at 0x11e727470> of base class PupilDetectorPlugin will be replaced by Detector3DPlugin.
2020-01-17 11:39:51,062 - eye1 - [DEBUG] plugin: Unloaded Plugin: <pupil_detector_plugins.detector_3d_plugin.Detector3DPlugin object at 0x11e727470>
2020-01-17 11:39:54,114 - eye1 - [DEBUG] plugin: Plugin <pupil_detector_plugins.detector_3d_plugin.Detector3DPlugin object at 0x11e727978> of base class PupilDetectorPlugin will be replaced by Detector3DPlugin.
2020-01-17 11:39:54,114 - eye1 - [DEBUG] plugin: Unloaded Plugin: <pupil_detector_plugins.detector_3d_plugin.Detector3DPlugin object at 0x11e727978>
2020-01-17 11:39:54,729 - eye0 - [DEBUG] video_capture: Install pyrealsense to use the Intel RealSense backend
2020-01-17 11:39:54,731 - eye0 - [DEBUG] video_capture: Install pyrealsense2 to use the Intel RealSense backend for D400 series cameras
2020-01-17 11:39:54,757 - eye0 - [INFO] root: Refraction corrected 3D pupil detector not available
2020-01-17 11:39:54,758 - eye0 - [DEBUG] file_methods: Session settings file '/Users/kai/pupil_test/pupil/capture_settings/user_settings_eye0' not found. Will make new one on exit.
2020-01-17 11:39:54,758 - eye0 - [INFO] launchables.eye: Session setting are from a different version of this app. I will not use those.
2020-01-17 11:39:55,032 - eye0 - [DEBUG] plugin: Loading plugin: UVC_Source with settings {'preferred_names': ['Pupil Cam3 ID0', 'Pupil Cam2 ID0', 'Pupil Cam1 ID0', 'HD-6000'], 'frame_size': (320, 240), 'frame_rate': 120}
2020-01-17 11:39:55,118 - eye0 - [DEBUG] uvc: Found device that mached uid:'20:28'
2020-01-17 11:39:55,122 - eye0 - [DEBUG] uvc: Device '20:28' opended.
2020-01-17 11:39:55,122 - eye0 - [DEBUG] uvc: avaible video modes: [{'size': (400, 400), 'rates': [120, 90, 60, 30]}, {'size': (192, 192), 'rates': [200, 180, 120, 90, 60, 30]}]
2020-01-17 11:39:55,122 - eye0 - [DEBUG] uvc: Adding "Auto Exposure Mode" control.
2020-01-17 11:39:55,125 - eye0 - [DEBUG] uvc: Adding "Auto Exposure Priority" control.
2020-01-17 11:39:55,126 - eye0 - [DEBUG] uvc: Adding "Absolute Exposure Time" control.
2020-01-17 11:39:55,130 - eye0 - [DEBUG] uvc: Adding "Auto Focus" control.
2020-01-17 11:39:55,132 - eye0 - [DEBUG] uvc: Adding "Absolute Focus" control.
2020-01-17 11:39:55,135 - eye0 - [DEBUG] uvc: Adding "Absolute Iris " control.
2020-01-17 11:39:55,139 - eye0 - [DEBUG] uvc: Adding "Scanning Mode " control.
2020-01-17 11:39:55,141 - eye0 - [DEBUG] uvc: Adding "Zoom absolute control" control.
2020-01-17 11:39:55,147 - eye0 - [DEBUG] uvc: Adding "Pan control" control.
2020-01-17 11:39:55,152 - eye0 - [DEBUG] uvc: Adding "Tilt control" control.
2020-01-17 11:39:55,156 - eye0 - [DEBUG] uvc: Adding "Roll absolute control" control.
2020-01-17 11:39:55,160 - eye0 - [DEBUG] uvc: Adding "Privacy Shutter control" control.
2020-01-17 11:39:55,161 - eye0 - [DEBUG] uvc: Adding "Backlight Compensation" control.
2020-01-17 11:39:55,166 - eye0 - [DEBUG] uvc: Adding "Brightness" control.
2020-01-17 11:39:55,170 - eye0 - [DEBUG] uvc: Adding "Contrast" control.
2020-01-17 11:39:55,174 - eye0 - [DEBUG] uvc: Adding "Gain" control.
2020-01-17 11:39:55,180 - eye0 - [DEBUG] uvc: Adding "Power Line frequency" control.
2020-01-17 11:39:55,183 - eye0 - [DEBUG] uvc: Adding "Hue" control.
2020-01-17 11:39:55,187 - eye0 - [DEBUG] uvc: Adding "Saturation" control.
2020-01-17 11:39:55,190 - eye0 - [DEBUG] uvc: Adding "Sharpness" control.
2020-01-17 11:39:55,194 - eye0 - [DEBUG] uvc: Adding "Gamma" control.
2020-01-17 11:39:55,198 - eye0 - [DEBUG] uvc: Adding "White Balance temperature" control.
2020-01-17 11:39:55,201 - eye0 - [DEBUG] uvc: Adding "White Balance temperature,Auto" control.
2020-01-17 11:39:55,221 - eye0 - [INFO] camera_models: No user calibration found for camera Pupil Cam2 ID0 at resolution (192, 192)
2020-01-17 11:39:55,221 - eye0 - [INFO] camera_models: No pre-recorded calibration available
2020-01-17 11:39:55,221 - eye0 - [WARNING] camera_models: Loading dummy calibration
2020-01-17 11:39:55,221 - eye0 - [DEBUG] uvc: Setting mode: 192,192,120
2020-01-17 11:39:55,264 - eye0 - [DEBUG] plugin: Loading plugin: UVC_Manager with settings {}
2020-01-17 11:39:55,447 - eye0 - [DEBUG] plugin: Loading plugin: Detector3DPlugin with settings {}
2020-01-17 11:39:55,449 - eye0 - [DEBUG] plugin: Loading plugin: PupilDetectorManager with settings {}
2020-01-17 11:39:55,451 - eye0 - [INFO] root: Refraction corrected 3D pupil detector not available
2020-01-17 11:39:55,455 - eye0 - [WARNING] launchables.eye: Process started.
2020-01-17 11:39:55,614 - eye0 - [DEBUG] uvc: Stream start.
2020-01-17 11:39:55,862 - eye0 - [DEBUG] plugin: Plugin <pupil_detector_plugins.detector_3d_plugin.Detector3DPlugin object at 0x118982e10> of base class PupilDetectorPlugin will be replaced by Detector3DPlugin.
2020-01-17 11:39:55,862 - eye0 - [DEBUG] plugin: Unloaded Plugin: <pupil_detector_plugins.detector_3d_plugin.Detector3DPlugin object at 0x118982e10>
2020-01-17 11:39:58,394 - world - [DEBUG] recorder: Created new recordings session dir /Users/kai/pupil_test/pupil/recordings/2020_01_17
2020-01-17 11:39:58,394 - world - [DEBUG] recorder: We dont want to overwrite data, incrementing counter & trying to make new data folder
2020-01-17 11:39:58,394 - world - [DEBUG] recorder: We dont want to overwrite data, incrementing counter & trying to make new data folder
2020-01-17 11:39:58,398 - world - [DEBUG] recorder: Created new recording dir /Users/kai/pupil_test/pupil/recordings/2020_01_17/002/
2020-01-17 11:39:58,400 - world - [DEBUG] av_writer: Opened '/Users/kai/pupil_test/pupil/recordings/2020_01_17/002/world.mp4' for writing.
2020-01-17 11:39:58,406 - world - [INFO] recorder: Started Recording.
2020-01-17 11:39:58,411 - eye1 - [INFO] launchables.eye: Will save eye video to: /Users/kai/pupil_test/pupil/recordings/2020_01_17/002/
2020-01-17 11:39:58,411 - eye1 - [DEBUG] av_writer: Opened '/Users/kai/pupil_test/pupil/recordings/2020_01_17/002/eye1.mp4' for writing.
2020-01-17 11:39:58,412 - eye0 - [INFO] launchables.eye: Will save eye video to: /Users/kai/pupil_test/pupil/recordings/2020_01_17/002/
2020-01-17 11:39:58,413 - eye0 - [DEBUG] av_writer: Opened '/Users/kai/pupil_test/pupil/recordings/2020_01_17/002/eye0.mp4' for writing.
2020-01-17 11:39:58,418 - eye1 - [DEBUG] av_writer: Skipping frame that arrived before sync time.
2020-01-17 11:39:58,419 - world - [DEBUG] av_writer: Skipping frame that arrived before sync time.
2020-01-17 11:39:58,453 - world - [DEBUG] av_writer: Skipping frame that arrived before sync time.
2020-01-17 11:43:17,256 - eye0 - [INFO] video_capture.uvc_backend: Exposure mode for camera Pupil Cam2 ID0 is now set to auto mode
2020-01-17 11:43:26,277 - eye0 - [DEBUG] uvc: Stream stopped
2020-01-17 11:43:26,306 - eye0 - [DEBUG] uvc: Stream closed
2020-01-17 11:43:26,306 - eye0 - [DEBUG] uvc: Stream stop.
2020-01-17 11:43:26,338 - eye0 - [INFO] camera_models: No user calibration found for camera Pupil Cam2 ID0 at resolution (400, 400)
2020-01-17 11:43:26,338 - eye0 - [INFO] camera_models: No pre-recorded calibration available
2020-01-17 11:43:26,338 - eye0 - [WARNING] camera_models: Loading dummy calibration
2020-01-17 11:43:26,487 - eye0 - [DEBUG] uvc: Stream start.
2020-01-17 11:44:36,267 - eye0 - [DEBUG] uvc: Setting mode: 400,400,120
2020-01-17 11:44:36,268 - eye0 - [DEBUG] uvc: Stream stopped
2020-01-17 11:44:36,304 - eye0 - [DEBUG] uvc: Stream closed
2020-01-17 11:44:36,304 - eye0 - [DEBUG] uvc: Stream stop.
2020-01-17 11:44:36,400 - eye0 - [DEBUG] uvc: Stream start.
2020-01-17 11:50:52,510 - world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/Users/kai/pupil_test/pupil/pupil_src/launchables/world.py", line 635, in world
    p.recent_events(events)
  File "/Users/kai/pupil_test/pupil/pupil_src/shared_modules/recorder.py", line 439, in recent_events
    self.writer.write_video_frame(frame)
  File "/Users/kai/pupil_test/pupil/pupil_src/shared_modules/av_writer.py", line 168, in write_video_frame
    "Non-monotonic timestamps!"
ValueError: Non-monotonic timestamps!Last timestamp: 42408.348138. Given timestamp: 42408.246185

2020-01-17 11:50:52,511 - world - [INFO] launchables.world: Process shutting down.
2020-01-17 11:50:52,765 - eye0 - [INFO] launchables.eye: Done recording eye.
2020-01-17 11:50:52,779 - eye1 - [INFO] launchables.eye: Done recording eye.
2020-01-17 11:50:52,797 - eye0 - [DEBUG] plugin: Unloaded Plugin: <video_capture.uvc_backend.UVC_Manager object at 0x118982dd8>
2020-01-17 11:50:52,798 - eye0 - [DEBUG] plugin: Unloaded Plugin: <pupil_detector_plugins.manager.PupilDetectorManager object at 0x118996240>
2020-01-17 11:50:52,798 - eye0 - [DEBUG] plugin: Unloaded Plugin: <pupil_detector_plugins.detector_3d_plugin.Detector3DPlugin object at 0x118996dd8>
2020-01-17 11:50:52,799 - eye0 - [DEBUG] uvc: Stream stopped
2020-01-17 11:50:52,808 - eye1 - [DEBUG] plugin: Unloaded Plugin: <video_capture.uvc_backend.UVC_Manager object at 0x11e7276d8>
2020-01-17 11:50:52,808 - eye1 - [DEBUG] plugin: Unloaded Plugin: <pupil_detector_plugins.manager.PupilDetectorManager object at 0x11e727630>
2020-01-17 11:50:52,809 - eye1 - [DEBUG] plugin: Unloaded Plugin: <pupil_detector_plugins.detector_3d_plugin.Detector3DPlugin object at 0x11e727a90>
2020-01-17 11:50:52,809 - eye1 - [DEBUG] uvc: Stream stopped
2020-01-17 11:50:52,837 - eye0 - [DEBUG] uvc: Stream closed
2020-01-17 11:50:52,837 - eye0 - [DEBUG] uvc: Stream stop.
2020-01-17 11:50:52,840 - eye1 - [DEBUG] uvc: Stream closed
2020-01-17 11:50:52,841 - eye1 - [DEBUG] uvc: Stream stop.
2020-01-17 11:50:52,853 - eye0 - [DEBUG] uvc: UVC device closed.
2020-01-17 11:50:52,853 - eye0 - [DEBUG] plugin: Unloaded Plugin: <video_capture.uvc_backend.UVC_Source object at 0x1189829b0>
2020-01-17 11:50:52,856 - eye1 - [DEBUG] uvc: UVC device closed.
2020-01-17 11:50:52,856 - eye1 - [DEBUG] plugin: Unloaded Plugin: <video_capture.uvc_backend.UVC_Source object at 0x11e714fd0>
2020-01-17 11:50:52,862 - eye0 - [INFO] launchables.eye: Process shutting down.
2020-01-17 11:50:52,863 - eye1 - [INFO] launchables.eye: Process shutting down.
2020-01-17 11:53:42,130 - MainProcess - [INFO] os_utils: Re-enabled idle sleep.

**Comment by papr** [comment]
Worked around in v1.22, see #1812
