### ISSUE TITLE
AttributeError: 'Simple_Gaze_Mapper' object has no attribute '__bases__'

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#189]
This error occurred in the end of a screen marker calibration.
 
``` text
Traceback (most recent call last):
  File "/home/rafael/git/pupil_upstream/pupil_src/capture/main.py", line 145, in <module>
    main()
  File "/home/rafael/git/pupil_upstream/pupil_src/capture/main.py", line 138, in main
    world(g_pool,world_src,world_size)
  File "/home/rafael/git/pupil_upstream/pupil_src/capture/world.py", line 322, in world
    p.update(frame,events)
  File "/home/rafael/git/pupil_upstream/pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py", line 311, in update
    self.stop()
  File "/home/rafael/git/pupil_upstream/pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py", line 251, in stop
    self.g_pool.plugins.add(Simple_Gaze_Mapper(self.g_pool,params))
  File "/home/rafael/git/pupil_upstream/pupil_src/shared_modules/plugin.py", line 206, in add
    if p.base_class == new_plugin.__bases__[-1]:
AttributeError: 'Simple_Gaze_Mapper' object has no attribute '__bases__'
```

**Comment by elmorg** [comment]
I have the same error. Haven't found a solution yet

**Comment by elmorg** [comment]
thanks!
