### ISSUE TITLE
Capture crashes if no reference data was collected during a calibration

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#1924]
```py
world - [INFO] gaze_mapping.utils: Dismissing 99.20% pupil data due to confidence < 0.80
world - [ERROR] gaze_mapping.gazer_base: AssertionError
world - [DEBUG] gaze_mapping.gazer_base: Traceback (most recent call last):
  File "/Users/papr/work/pupil/pupil_src/shared_modules/gaze_mapping/gazer_base.py", line 196, in __init__
    self.fit_on_calib_data(calib_data)
  File "/Users/papr/work/pupil/pupil_src/shared_modules/gaze_mapping/gazer_3d/gazer_headset.py", line 336, in fit_on_calib_data
    super().fit_on_calib_data(calib_data)
  File "/Users/papr/work/pupil/pupil_src/shared_modules/gaze_mapping/gazer_base.py", line 262, in fit_on_calib_data
    matches = self.match_pupil_to_ref(pupil_data, ref_data)
  File "/Users/papr/work/pupil/pupil_src/shared_modules/gaze_mapping/gazer_base.py", line 329, in match_pupil_to_ref
    matches = _match_data_batch(pupil_data, ref_data)
  File "/Users/papr/work/pupil/pupil_src/shared_modules/gaze_mapping/utils.py", line 36, in _match_data_batch
    assert ref_list
AssertionError

world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/Users/papr/work/pupil/pupil_src/shared_modules/gaze_mapping/gazer_base.py", line 196, in __init__
    self.fit_on_calib_data(calib_data)
  File "/Users/papr/work/pupil/pupil_src/shared_modules/gaze_mapping/gazer_3d/gazer_headset.py", line 336, in fit_on_calib_data
    super().fit_on_calib_data(calib_data)
  File "/Users/papr/work/pupil/pupil_src/shared_modules/gaze_mapping/gazer_base.py", line 262, in fit_on_calib_data
    matches = self.match_pupil_to_ref(pupil_data, ref_data)
  File "/Users/papr/work/pupil/pupil_src/shared_modules/gaze_mapping/gazer_base.py", line 329, in match_pupil_to_ref
    matches = _match_data_batch(pupil_data, ref_data)
  File "/Users/papr/work/pupil/pupil_src/shared_modules/gaze_mapping/utils.py", line 36, in _match_data_batch
    assert ref_list
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/papr/work/pupil/pupil_src/launchables/world.py", line 642, in world
    handle_notifications(n)
  File "/Users/papr/work/pupil/pupil_src/launchables/world.py", line 408, in handle_notifications
    g_pool.plugins.add(
  File "/Users/papr/work/pupil/pupil_src/shared_modules/plugin.py", line 391, in add
    plugin_instance = new_plugin_cls(self.g_pool, **args)
  File "/Users/papr/work/pupil/pupil_src/shared_modules/gaze_mapping/gazer_base.py", line 208, in __init__
    raise CalibrationError() from err
gaze_mapping.gazer_base.CalibrationError
```

**Comment by papr** [comment]
Fixed in #1960
