### ISSUE TITLE
glfw Attribute Error

### ISSUE THREAD

**Issue by fiza09** [pupil-labs/pupil#1945]
I am working from ubuntu 18.04.

When I try to open pupil player from terminal, I get the following error: 

```
player - [INFO] numexpr.utils: Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.

player - [INFO] numexpr.utils: NumExpr defaulting to 8 threads.
player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
player - [ERROR] launchables.player: Process player_drop crashed with trace:
Traceback (most recent call last):
  File "/home/fiza/anaconda3/envs/pupil_labs/pupil/pupil_src/launchables/player.py", line 768, in player_drop
    window = glfw.glfwCreateWindow(w, h, "Pupil Player")
  File "/home/fiza/anaconda3/envs/pupil_labs/pupil/pupil_src/shared_modules/glfw.py", line 566, in glfwCreateWindow
    raise Exception(f"GLFW window failed to create: {glfwGetError()}")
  File "/home/fiza/anaconda3/envs/pupil_labs/pupil/pupil_src/shared_modules/glfw.py", line 512, in glfwGetError
    _glfwGetError = _glfw.glfwGetError
  File "/home/fiza/anaconda3/envs/pupil_labs/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/home/fiza/anaconda3/envs/pupil_labs/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libglfw.so.3: undefined symbol: glfwGetError
```

I do have libglfw.so.3 installed in another directory, which I also copied into the sitepackages folder of my environment. That does not help. To be sure, when I did run dpkg --listfiles libglfw3-dev, I got the following: 

```
/.
/usr
/usr/include
/usr/include/GLFW
/usr/include/GLFW/glfw3.h
/usr/include/GLFW/glfw3native.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/cmake
/usr/lib/x86_64-linux-gnu/cmake/glfw3
/usr/lib/x86_64-linux-gnu/cmake/glfw3/glfw3Config.cmake
/usr/lib/x86_64-linux-gnu/cmake/glfw3/glfw3ConfigVersion.cmake
/usr/lib/x86_64-linux-gnu/cmake/glfw3/glfw3Targets-none.cmake
/usr/lib/x86_64-linux-gnu/cmake/glfw3/glfw3Targets.cmake
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/glfw3.pc
/usr/share
/usr/share/doc
/usr/share/doc/libglfw3-dev
/usr/share/doc/libglfw3-dev/copyright
/usr/lib/x86_64-linux-gnu/libglfw.so
/usr/share/doc/libglfw3-dev/changelog.Debian.gz
```
I've looked at different solutions to Attribute Error but it doesn't help. Most them are application-specific.

**Comment by papr** [comment]
`glfwGetError` was added in glfw 3.3. Please uninstall the apt-installed glfw version and build glfw `v3.3` or later from source: https://github.com/glfw/glfw
