### ISSUE TITLE
AttributeError: libglfw.so.3: undefined symbol: glfwGetWindowContentScale

### ISSUE THREAD

**Issue by WZSin7** [pupil-labs/pupil#2013]
Hi everyone! I have a problem getting Pupil software to run on my Ubuntu 18.04 machine.
```
(pupilLab) sinwz@SWZ:~/pupil/pupil_src$ python main.py capture
world - [INFO] numexpr.utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
world - [INFO] numexpr.utils: NumExpr defaulting to 8 threads.
world - [INFO] launchables.world: Application Version: 2.4.0
world - [INFO] launchables.world: System Info: User: sinwz, Platform: Linux, Machine: SWZ, Release: 5.4.0-47-generic, Version: #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020
world - [ERROR] video_capture.uvc_backend: Could not connect to device! No images will be supplied.
world - [INFO] camera_models: No recorded intrinsics found for camera (disconnected) at resolution [1280, 720]
world - [WARNING] camera_models: No default intrinsics available! Loading dummy intrinsics!
world - [INFO] calibration_choreography.mixin.monitor_selection_mixin: Monitor "Generic PnP Monitor [PRIMARY]" no longer available. Using "eDP-1 [PRIMARY]" instead.
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/sinwz/pupil/pupil_src/launchables/world.py", line 641, in world
    g_pool.plugins = Plugin_List(g_pool, loaded_plugins)
  File "/home/sinwz/pupil/pupil_src/shared_modules/plugin.py", line 376, in __init__
    self.add(plugin, args)
  File "/home/sinwz/pupil/pupil_src/shared_modules/plugin.py", line 400, in add
    plugin_instance.init_ui()
  File "/home/sinwz/pupil/pupil_src/shared_modules/system_graphs.py", line 72, in init_ui
    self.on_window_resize(self.g_pool.main_window)
  File "/home/sinwz/pupil/pupil_src/shared_modules/system_graphs.py", line 76, in on_window_resize
    content_scale = glfw.get_content_scale(window)
  File "/home/sinwz/pupil/pupil_src/shared_modules/glfw.py", line 749, in get_content_scale
    return glfwGetWindowContentScale(window)[0]
  File "/home/sinwz/pupil/pupil_src/shared_modules/glfw.py", line 680, in glfwGetWindowContentScale
    _glfw.glfwGetWindowContentScale(window, byref(xscale), byref(yscale))
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libglfw.so.3: undefined symbol: glfwGetWindowContentScale

world - [INFO] launchables.world: Process shutting down.

```
FYI, I am not using the world camera hence it is not connected. I don't believe it is the cause of the issue, the same setup ran fine for my Windows machine.

**Comment by WZSin7** [comment]
I have found a way to get around the issue, I believe it is a version problem. 
V2.1 seems to work just fine, anything after that (V2.2 , V2.3, V2.4) have the same issue.

**Comment by pfaion** [comment]
Hi @WZSin7, are you running Pupil from source or from the installable bundle?

**Comment by WZSin7** [comment]
From source

**Comment by papr** [comment]
To install the required glfw version on Ubuntu 18.04., please follow these steps to build glfw from source:
```sh
sudo apt install xorg-dev
git clone https://github.com/glfw/glfw
cd glfw
git checkout 3.3.2
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=ON ..
make
sudo make install
sudo ldconfig
```
