### ISSUE TITLE
Process Eye0 crashed with trace: AttributeError: 'types.SimpleNamespace' object has no attribute 'zmq_ctx'

### ISSUE THREAD

**Issue by Lifestohack** [pupil-labs/pupil#2049]
I created a video backend to stream a video from raspberry to my laptop where pupil capture software is running. The hmd_streaming is then started via a notification. My video stream server behaves like hmd_streaming expects it. 
Here is the code: https://github.com/Lifestohack/pupil-video-backend/blob/master/video_backend.py#L60
I am able to start the world view via the notification. But eye0 and eye1 cannot be started. If I start my video backend server I get the error on the pupil capture software that says: Process Eye0 crashed with trace. 

Looking at the capture.log following Traceback is found:

```
- eye0 - [ERROR] launchables.eye: Process Eye0 crashed with trace:
Traceback (most recent call last):
  File "launchables/eye.py", line 654, in eye
  File "shared_modules/plugin.py", line 398, in add
  File "shared_modules/video_capture/hmd_streaming.py", line 50, in __init__
AttributeError: 'types.SimpleNamespace' object has no attribute 'zmq_ctx'
```

**Comment by Lifestohack** [comment]
Reproduction steps:

1. Start pupil capture software.
2. Click on "Detect eye 0" on pupil capture software. Small window pops up where eye0 video feed supposed to be shown.
3. Started pupil video backend.

But pupil detection eye 0 window closes automatically. And pupil capture shows the error: Process Eye0 crashed with trace.

```
2020-11-12 13:32:15,630 - world - [DEBUG] network_api.controller.pupil_remote_controller: Request: 'PUB_PORT', Response: '44017'
2020-11-12 13:32:15,634 - world - [DEBUG] network_api.controller.pupil_remote_controller: Request: 'notify.start_eye_plugin', Response: 'Message forwarded.'
2020-11-12 13:32:15,656 - eye0 - [DEBUG] plugin: Replacing Video Source due to 'by_base_class' uniqueness
2020-11-12 13:32:15,656 - eye0 - [DEBUG] plugin: Unloaded Plugin: <video_capture.uvc_backend.UVC_Source object at 0x7f0e638784a8>
2020-11-12 13:32:15,657 - eye0 - [ERROR] launchables.eye: Process Eye0 crashed with trace:
Traceback (most recent call last):
  File "launchables/eye.py", line 654, in eye
  File "shared_modules/plugin.py", line 398, in add
  File "shared_modules/video_capture/hmd_streaming.py", line 50, in __init__
AttributeError: 'types.SimpleNamespace' object has no attribute 'zmq_ctx'
```
