### ISSUE TITLE
Player crash

### ISSUE THREAD

**Issue by martingasser** [pupil-labs/pupil#2060]
The player crashes after loading a recording.

Python 2.6.9, Ubuntu 18.04

```
player - [INFO] numexpr.utils: Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
player - [INFO] numexpr.utils: NumExpr defaulting to 8 threads.
player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
player - [INFO] launchables.player: Starting new session with '/home/martin/devel/pupil/recordings/2020_12_01/001'
player - [INFO] pupil_recording.update.new_style: Checking for world-less recording...
player - [ERROR] launchables.player: Process player_drop crashed with trace:
Traceback (most recent call last):
  File "/home/martin/devel/pupil/pupil_src/launchables/player.py", line 935, in player_drop
    update_recording(rec_dir)
  File "/home/martin/devel/pupil/pupil_src/shared_modules/pupil_recording/update/__init__.py", line 79, in update_recording
    _generate_all_lookup_tables(rec_dir)
  File "/home/martin/devel/pupil/pupil_src/shared_modules/pupil_recording/update/__init__.py", line 105, in _generate_all_lookup_tables
    SimpleNamespace(), source_path=source_path, fill_gaps=True, timing=None
  File "/home/martin/devel/pupil/pupil_src/shared_modules/video_capture/file_backend.py", line 247, in __init__
    self.reset_video()
  File "/home/martin/devel/pupil/pupil_src/shared_modules/video_capture/file_backend.py", line 639, in reset_video
    self._setup_video(container_idx_of_first_frame)
  File "/home/martin/devel/pupil/pupil_src/shared_modules/video_capture/file_backend.py", line 305, in _setup_video
    self.video_stream = self._get_streams(container, self.buffering)
  File "/home/martin/devel/pupil/pupil_src/shared_modules/video_capture/file_backend.py", line 324, in _get_streams
    video_stream.thread_count = cpu_count()
  File "av/stream.pyx", line 126, in av.stream.Stream.__setattr__
  File "av/codec/context.pyx", line 580, in av.codec.context.CodecContext.thread_count.__set__
RuntimeError: Cannot change thread_count after codec is open.

```

Any help is appreciated!

**Comment by papr** [comment]
@martingasser Hey, as you are running from source, could you let us know what pyav you have installed? You can do this by running this code in your terminal:
> `python -c "import av; print(av.__version__)"`

Should you have installed the dependencies into a virtual environment, please activate first.

**Comment by martingasser** [comment]
My fault - turns out I had installed the latest pypi version instead of your fork.

Thanks for pointing me in the right direction!
