### ISSUE TITLE
Pupil Service Crashes/Shutdowns when running sample code from website

### ISSUE THREAD

**Issue by trakevital** [pupil-labs/pupil#2066]
### System/Packages Used:

- Ubuntu 18.04

- Python 2.7

- msgpack-numpy 0.4.3.2

- pyzmq 19.0.2

- pupil service linux os x64 v2.6-19-g6344358

### To Replicate:

1. make a new directory in home called pupil-labs-research
2. cd to the new directory
3. make a file called simple_rec.py
4. paste the code below into the file

```python
import zmq, msgpack, time
ctx = zmq.Context()

#create a zmq REQ socket to talk to Pupil Service/Capture
req = ctx.socket(zmq.REQ)
req.connect('tcp://localhost:50020')

#convenience functions
def send_recv_notification(n):
    # REQ REP requirese lock step communication with multipart msg (topic,msgpack_encoded dict)
    req.send_multipart(('notify.%s'%n['subject'], msgpack.dumps(n)))
    return req.recv()

def get_pupil_timestamp():
    req.send('t') #see Pupil Remote Plugin for details
    return float(req.recv())

# set start eye windows
n = {'subject':'eye_process.should_start.0','eye_id':0, 'args':{}}
print(send_recv_notification(n))
n = {'subject':'eye_process.should_start.1','eye_id':1, 'args':{}}
print(send_recv_notification(n))
time.sleep(2)


# set calibration method to hmd calibration
n = {'subject':'start_plugin','name':'HMD_Calibration', 'args':{}}
print(send_recv_notification(n))


time.sleep(2)
# set calibration method to hmd calibration
n = {'subject':'service_process.should_stop'}
print(send_recv_notification(n))
```
5. run the code in a terminal with python2

Output:
 
```
Message forwarded.
Message forwarded.
```

-at this point pupil service shutdowns and an infinite loop occurs in the terminal. 

### Log file content:

```
2020-12-06 15:12:11,344 - service - [INFO] launchables.service: Process shutting down.
2020-12-06 15:12:11,362 - eye0 - [ERROR] launchables.eye: Process Eye0 crashed with trace:
Traceback (most recent call last):
  File "launchables/eye.py", line 632, in eye
KeyError: 'subject'

2020-12-06 15:12:11,362 - eye1 - [ERROR] launchables.eye: Process Eye1 crashed with trace:
Traceback (most recent call last):
  File "launchables/eye.py", line 632, in eye
KeyError: 'subject'
```

**Comment by papr** [comment]
@trakevital Hi, thank you for the very detailed issue description. The issue is that you are running the script with Python 2.7 that uses `bytes` for strings, while Service uses Python 3, which uses unicode for strings. Please convert all your strings to unicode (especially the notification dict keys) before converting them with msgpack.

**Comment by trakevital** [comment]
@papr Hello, I tried converting all the strings to Unicode but to no avail; now I get a new problem.

My new code:
```python
import zmq, msgpack, time
ctx = zmq.Context()

#create a zmq REQ socket to talk to Pupil Service/Capture
req = ctx.socket(zmq.REQ)
req.connect('tcp://localhost:50020')

#convenience functions
def send_recv_notification(n):
    
    # REQ REP requirese lock step communication with multipart msg (topic,msgpack_encoded dict)
    req.send_multipart((unicode('notify.%s'%n[unicode('subject')]), msgpack.dumps(n)))
    return req.recv()

def get_pupil_timestamp():
    req.send(unicode('t')) #see Pupil Remote Plugin for details
    return float(req.recv())

# set start eye windows
n = {unicode('subject'):unicode('eye_process.should_start.0'),unicode('eye_id'):0, unicode('args'):{}}
print(send_recv_notification(n))
n = {unicode('subject'):unicode('eye_process.should_start.1'),unicode('eye_id'):1, unicode('args'):{}}
print(send_recv_notification(n))
time.sleep(2)


# set calibration method to hmd calibration
n = {unicode('subject'):unicode('start_plugin'),unicode('name'):unicode('HMD_Calibration'), unicode('args'):{}}
print(send_recv_notification(n))


time.sleep(2)

n = {unicode('subject'):unicode('service_process.should_stop')}
print(send_recv_notification(n))

```

Console output:

```
Traceback (most recent call last):
  File "simple_rec.py", line 21, in <module>
    print(send_recv_notification(n))
  File "simple_rec.py", line 12, in send_recv_notification
    req.send_multipart((unicode('notify.%s'%n[unicode('subject')]), msgpack.dumps(n)))
  File "/home/flight-host/.local/lib/python2.7/site-packages/zmq/sugar/socket.py", line 458, in send_multipart
    i, rmsg,
TypeError: Frame 0 (u'notify.eye_process.should_star...) does not support the buffer interface.
```

**Comment by trakevital** [comment]
Thank you @papr ! I managed to fix the problem. Here are the steps I took to fix it:

1. I switched from python 2.7 to python 3.6
2. I removed the following library: `zmq 0.0.0`
3. I installed the following pip libraries:
- `pyzmq 20.0.0`
- `msgpack 1.0.1`
- `msgpack-numpy 0.4.3.2`
4. I changed this line: 

```python
 req.send_multipart(('notify.%s'%n['subject'], msgpack.dumps(n)))
```
  To this one:

```python
req.send_multipart((bytes('notify.%s'%n['subject'], 'utf8'), bytes(msgpack.dumps(n))))
```

Console Output:
```
b'Message forwarded.'
b'Message forwarded.'
b'Message forwarded.'
b'Message forwarded.'
```
(instead of only 2 messages forwarded and an infinite loop happening)

**Comment by trakevital** [comment]
Raw code:

```python
import zmq, msgpack, time
ctx = zmq.Context()

#create a zmq REQ socket to talk to Pupil Service/Capture
req = ctx.socket(zmq.REQ)
req.connect('tcp://localhost:50020')

#convenience functions
def send_recv_notification(n):
    # REQ REP requirese lock step communication with multipart msg (topic,msgpack_encoded dict)
	req.send_multipart((bytes('notify.%s'%n['subject'], 'utf8'), bytes(msgpack.dumps(n))))
    return req.recv()

def get_pupil_timestamp():
    req.send('t') #see Pupil Remote Plugin for details
    return float(req.recv())

# set start eye windows
n = {'subject':'eye_process.should_start.0','eye_id':0, 'args':{}}
print(send_recv_notification(n))
n = {'subject':'eye_process.should_start.1','eye_id':1, 'args':{}}
print(send_recv_notification(n))
time.sleep(2)


# set calibration method to hmd calibration
n = {'subject':'start_plugin','name':'HMD_Calibration', 'args':{}}
print(send_recv_notification(n))


time.sleep(2)
# set calibration method to hmd calibration
n = {'subject':'service_process.should_stop'}
print(send_recv_notification(n))
```
