### ISSUE TITLE
Import DLL load error

### ISSUE THREAD

**Issue by fiza09** [pupil-labs/pupil#2088]
It seems like I've been installing the program forever. That is because I have encountered a lot of technical problems including multiple OS crashes because of graphics or dual booting or surface tracker plugin errors. So I have had to install the program multiple times of the same machine or different ones. 

The one on my personal computer Windows laptop froze a lot presumably because of lower processing power. So, I installed and re-installed ubuntu 18 OS on my desktop multiple times. As of now, the software freezes a lot to the point where it does not allow me to do anything. I did follow all of the steps, including updating to the newer pupil v3 and downloading/updating packages through the requirements.txt file because the older version froze a lot. That didn't work and led to import/export errors so I reverted back to v2.5. It still freezes a lot and still gets in the way of actual work. 

Please help me set up my program on the Windows 10 or Ubuntu 18 at least. Its very frustrating! 

I am getting the error below when re-installing pupil on a borrowed machine, a Windows 10. 

```
(venv) C:\Users\farza\PycharmProjects\PupilLabs\pupil\pupil_src>python main.py player
Adding C:\Users\farza\PycharmProjects\PupilLabs\pupil\pupil_external to PATH
Adding C:\Users\farza\PycharmProjects\PupilLabs\pupil\pupil_external to PATH
player - [INFO] numexpr.utils: NumExpr defaulting to 8 threads.
player - [ERROR] launchables.player: Process player_drop crashed with trace:
Traceback (most recent call last):
  File "C:\Users\farza\PycharmProjects\PupilLabs\pupil\pupil_src\launchables\player.py", line 825, in player_drop
    from pupil_recording.update import update_recording
  File "C:\Users\farza\PycharmProjects\PupilLabs\pupil\pupil_src\shared_modules\pupil_recording\update\__init__.py", line 15, in <module>
    from video_capture.file_backend import File_Source
  File "C:\Users\farza\PycharmProjects\PupilLabs\pupil\pupil_src\shared_modules\video_capture\__init__.py", line 40, in <module>
    from .uvc_backend import UVC_Manager, UVC_Source
  File "C:\Users\farza\PycharmProjects\PupilLabs\pupil\pupil_src\shared_modules\video_capture\uvc_backend.py", line 25, in <module>
    import uvc
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by papr** [comment]
I am sorry to hear that. It looks like you were able to run from source successfully a few months back, based on https://github.com/pupil-labs/pupil/issues/1872

Are you still using Anaconda to build your virtual environment?

**Comment by fiza09** [comment]
No, I am using venv in both places. Yes and my OS crashed soon after because of problems with graphical display. What do you recommend for the above error? And, also how to fix the freezes on ubuntu?

**Comment by papr** [comment]
You did install pyuvc using the wheel, correct?
```
pip install "uvc @ https://github.com/pupil-labs/pyuvc/releases/download/v0.14/uvc-0.14-cp36-cp36m-win_amd64.whl" --force-reinstall
```
If you did successfully, then it is not clear _why_ a dll is missing. The wheel includes everything one needs.

Unfortunately, it is not clear what dll is missing. We can recommend using the [Dependencies](https://github.com/lucasg/Dependencies) application to find out. Download it [here](https://github.com/lucasg/Dependencies/releases/download/v1.10/Dependencies_x64_Release.zip).

Afterward, start `Dependencies_Gui.exe` and drag and drop the `uvc.cp36-win_amd64.pyd` file onto it. You can find it in your python installation's site-packages folder.

**Comment by papr** [comment]
Closing due to inactivity.

**Comment by papr** [comment]
The wheel linked above https://github.com/pupil-labs/pupil/issues/2088#issuecomment-768944093 does not ship all required dependencies. Use this wheel instead: [uvc-0.15.0-cp36-cp36m-win_amd64.zip](https://github.com/pupil-labs/pupil/files/9372573/uvc-0.15.0-cp36-cp36m-win_amd64.zip)
