### ISSUE TITLE
HMD Calibration crashes pupil service

### ISSUE THREAD

**Issue by ChristophEbner** [pupil-labs/pupil#2119]
Stopping the hmd calibration causes the pupil service to crash.

relevant Log:
2021-03-17 13:55:14,149 - service - [ERROR] launchables.service: Process Service crashed with trace:
Traceback (most recent call last):
  File "launchables\service.py", line 287, in service
  File "calibration_choreography\hmd_plugin.py", line 86, in on_notify
  File "calibration_choreography\base_plugin.py", line 512, in on_notify
  File "calibration_choreography\base_plugin.py", line 569, in _perform_stop
AttributeError: 'types.SimpleNamespace' object has no attribute 'trigger_main_window_redraw'

operating system: windows 10
version: v3.2-16

steps to reproduce:
- start HMD3DChoreographyPlugin
- start calibration "calibration.should_start"
- add some calibration points
- stop calibration "calibration.should_stop"

**Comment by papr** [comment]
This seems to expect a [change that was introduced to `world.py`](https://github.com/pupil-labs/pupil/commit/c1941e040dd9bbdab0582301b040ccfd4f1811ea) in https://github.com/pupil-labs/pupil/pull/2095 (released in v3.1). This change should have been and will be applied to `service.py`. You can expect an updated release on Monday.

**Comment by ChristophEbner** [comment]
Thank you!

**Comment by papr** [comment]
@ChristophEbner Please check out the updated release at https://github.com/pupil-labs/pupil/releases/tag/v3.2

**Comment by ChristophEbner** [comment]
Yay, it works! Thank you!
