### ISSUE TITLE
av.AVError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#212]
Trying to record something.
```
Traceback (most recent call last):
  File "/home/rafael/git/pupil_0.6/pupil_src/capture/main.py", line 145, in <module>
    main()
  File "/home/rafael/git/pupil_0.6/pupil_src/capture/main.py", line 138, in main
    world(g_pool,world_src,world_size)
  File "/home/rafael/git/pupil_0.6/pupil_src/capture/world.py", line 311, in world
    p.update(frame,events)
  File "/home/rafael/git/pupil_0.6/pupil_src/capture/recorder.py", line 280, in update
    self.writer.write_video_frame(frame)
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/av_writer.py", line 142, in write_video_frame
    packet = self.video_stream.encode(self.frame)
  File "av/video/stream.pyx", line 86, in av.video.stream.VideoStream.encode (src/av/video/stream.c:2652)
  File "av/video/stream.pyx", line 95, in av.video.stream.VideoStream.encode (src/av/video/stream.c:2048)
  File "av/container.pyx", line 495, in av.container.OutputContainer.start_encoding (src/av/container.c:7983)
  File "av/container.pyx", line 505, in av.container.OutputContainer.start_encoding (src/av/container.c:7803)
  File "av/container.pyx", line 189, in av.container.ContainerProxy.err_check (src/av/container.c:3729)
  File "av/utils.pyx", line 30, in av.utils.err_check (src/av/utils.c:969)
av.AVError: [Errno 1] Operation not permitted: '/home/rafael/git/pupil_0.6/recordings/2015_10_04/001/world.mp4'
WORLD Process [ERROR] libav.mpeg4 : bitrate tolerance too small for bitrate
```

**Comment by cpicanco** [comment]
World will freeze when `smaller file, more cpu` is selected and will record just fine with `bigger file, less cpu`

**Comment by mkassner** [comment]
Could you please pull and try if this fixes it?

**Comment by cpicanco** [comment]
Fixed!
