### ISSUE TITLE
crash after calibration: accuracy visualizer

### ISSUE THREAD

**Issue by bpinsard** [pupil-labs/pupil#2122]
Experienced a crash the other day after calibration (the data for calibration was not good enough for sure), here is the traceback that I saved:

``` 
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/scratch/neuromod/src/pupil/pupil_src/launchables/world.py", line 742, in world
    p.on_notify(n)
  File "/scratch/neuromod/src/pupil/pupil_src/shared_modules/accuracy_visualizer.py", line 302, in on_notify
    if self.__handle_calibration_result_notification(notification):
  File "/scratch/neuromod/src/pupil/pupil_src/shared_modules/accuracy_visualizer.py", line 336, in __handle_calibration_result_notification
    self.recalculate()
  File "/scratch/neuromod/src/pupil/pupil_src/shared_modules/accuracy_visualizer.py", line 403, in recalculate
    hull = ConvexHull(ref_locations)  # requires at least 3 points
  File "qhull.pyx", line 2431, in scipy.spatial.qhull.ConvexHull.__init__
  File "qhull.pyx", line 356, in scipy.spatial.qhull._Qhull.__init__
scipy.spatial.qhull.QhullError: QH6013 qhull input error: input is less than 2-dimensional since all points have the same x coordinate  0.5

While executing:  | qhull i Qt
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 150558979  incidence  Qtriangulate  _pre-merge  _zero-centrum
  _max-width 0.9  Error-roundoff 8.1e-16  _one-merge 4.1e-15
  _near-inside 2e-14  Visible-distance 1.6e-15  U-max-coplanar 1.6e-15
  Width-outside 3.3e-15  _wide-facet 9.8e-15  _maxoutside 4.9e-15

``` 

I think that this exception should be caught to avoid crashing the whole software, WDYT? 

Thanks

**Comment by bpinsard** [comment]
I guess what happened is that after filtering the bad calibration data in the GazeMapper2D, there was only 2 reference points left.

**Comment by papr** [comment]
@bpinsard Thank you for reporting this issue! This and other edge cases will no longer crash the software in our next release. See https://github.com/pupil-labs/pupil/pull/2128 for details.
