### ISSUE TITLE
Player - pressing space in the end of video will crash

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#214]
```
Traceback (most recent call last):
  File "/home/rafael/git/pupil_0.6/pupil_src/player/main.py", line 525, in <module>
    session(this_session_dir)
  File "/home/rafael/git/pupil_0.6/pupil_src/player/main.py", line 354, in session
    new_frame = cap.get_frame_nowait()
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/video_capture/av_file_capture.py", line 186, in get_frame_nowait
    frame = self.next_frame.next()
StopIteration
```

**Comment by mkassner** [comment]
Thanks for spotting this!
