### ISSUE TITLE
Cannot run latest release (ValueError: NULL pointer access)

### ISSUE THREAD

**Issue by TheZadok42** [pupil-labs/pupil#2174]
I installed the latest MSI from the releases and this is the output from `capture`:  
```
world - [INFO] numexpr.utils: NumExpr defaulting to 8 threads.
world - [INFO] launchables.world: Application Version: 3.4.0
world - [INFO] launchables.world: System Info: User: Talza, Platform: Windows, Machine: DESKTOP-25EOQ5D, Release: 10, Version: 10.0.19041
world - [INFO] launchables.world: Session setting are from a different version of this app. I will not use those.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "pyre\zactor.py", line 59, in run
  File "pyre\zbeacon.py", line 66, in __init__
  File "pyre\zbeacon.py", line 303, in run
  File "pyre\zbeacon.py", line 218, in handle_pipe
  File "pyre\zbeacon.py", line 201, in configure
  File "pyre\zbeacon.py", line 73, in prepare_udp
  File "pyre\zbeacon.py", line 137, in _prepare_socket
  File "pyre\zhelper.py", line 113, in get_ifaddrs
  File "pyre\zhelper.py", line 527, in get_win_ifaddrs
ValueError: NULL pointer access
```

Am I missing something?

**Comment by papr** [comment]
Hi, please see https://github.com/pupil-labs/pupil/issues/2098

Also, disabling your network devices one by one has helped in the past.

**Comment by TheZadok42** [comment]
Hi!  
Thank you for the quick response  
It seems that removing my vpn worked  
Is there a way to still use it without removing the vpn?  
Or should I open this issue with the package mentioned in #2098 ?

**Comment by papr** [comment]
A workaround was introduced to the package yesterday. We will ship it with our next release end of August.
