### ISSUE TITLE
No matching distribution found for ndsi==1.4.* after running pip install -r requirements.txt in virtual Enviroment

### ISSUE THREAD

**Issue by ArcticBeat05** [pupil-labs/pupil#2193]
Running on Jetson Nano 2GB, JP46

pip install -r requirements.txt

  ```
`Using cached glfw-2.2.0-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-manylinux2014_aarch64.whl (196 kB)
Collecting ndsi==1.4.*
  Using cached ndsi-1.4.2.tar.gz (299 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/arctic/pupil-env/bin/python /home/arctic/pupil-env/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpdfmfwq1z
       cwd: /tmp/pip-install-xtjq5a36/ndsi_efb10836b78b4490a086bc8d44425229
  Complete output (22 lines):
  Traceback (most recent call last):
    File "/home/arctic/pupil-env/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/arctic/pupil-env/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/arctic/pupil-env/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 103, in get_requires_for_build_wheel
      return _get_build_requires(config_settings)
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 89, in _get_build_requires
      _run_setup()
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 72, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 122, in <module>
      ext_modules=cythonize(extensions),
    File "/tmp/pip-build-env-r7538341/overlay/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 972, in cythonize
      aliases=aliases)
    File "/tmp/pip-build-env-r7538341/overlay/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "/tmp/pip-build-env-r7538341/overlay/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
      raise ValueError(error_msg)
  ValueError: 'ndsi/frame.pyx' doesn't match any files
```
  ----------------------------------------
```
WARNING: Discarding https://files.pythonhosted.org/packages/69/28/a4d67d92082fcf663822d2884062aa443e40af7c466ad93298aadcc6b524/ndsi-1.4.2.tar.gz#sha256=590b2b7098424b34a10ccc7d71eccddbd2407e117c7b41e82af241db06122f92 (from https://pypi.org/simple/ndsi/). Command errored out with exit status 1: /home/arctic/pupil-env/bin/python /home/arctic/pupil-env/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpdfmfwq1z Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement ndsi==1.4.* (from versions: 1.4.2)
ERROR: No matching distribution found for ndsi==1.4.*
```
`

**Comment by papr** [comment]
This is an issue with the source distribution. I will check if I can this fixed soon.
