### ISSUE TITLE
Syncing timebase causes crash on close (v0.6.9)

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#222]
Closing the plugin causes a crash.
Syncing should work, if the user added a permission for the Windows firewall.

**edit** Sync does not work, since pyre init fails.

**Comment by mkassner** [comment]
Can you post the exception?

**Comment by MichaelBarz** [comment]
Ok, the error actually occurs on start in `pupil_sync.py` line `121`.
`n.start()` causes 

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\lib\site-packages\pyre\zactor.py", line 57, in run
    self.shim_handler(*self.shim_args, **self.shim_kwargs)
  File "C:\Python27\lib\site-packages\pyre\zbeacon.py", line 64, in __init__
    self.run()
  File "C:\Python27\lib\site-packages\pyre\zbeacon.py", line 283, in run
    self.handle_pipe()
  File "C:\Python27\lib\site-packages\pyre\zbeacon.py", line 212, in handle_pipe
    self.configure(port)
  File "C:\Python27\lib\site-packages\pyre\zbeacon.py", line 195, in configure
    self.prepare_udp()
  File "C:\Python27\lib\site-packages\pyre\zbeacon.py", line 71, in prepare_udp
    self._prepare_socket()
  File "C:\Python27\lib\site-packages\pyre\zbeacon.py", line 143, in _prepare_socket
    logger.debug("Checking out interface {0}.".format(name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 13: ordinal not in range(128)
```

**Comment by cpicanco** [comment]
Pupil Sync is not thread safe yet, it is a know issue (reading the comments, :smile:).

**Comment by mkassner** [comment]
I think this is all the classic. Windows is supported but the dev use Linux/Mac. I say this is a zyre bug in the windows implementation. Not related to Pupil directly.

**Comment by MichaelBarz** [comment]
error still persists in new version...
