### ISSUE TITLE
Pupil Capture not launching

### ISSUE THREAD

**Issue by sumiya-kuroda** [pupil-labs/pupil#2303]
Hello,

I'm trying to launch Pupil Capture v3.5.1 on Windows 10 v1809, but I'm getting the following error message. Could you let us know how to selve this issue?

```
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "launchables\world.py", line 141, in world
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "methods.py", line 21, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "cv2\__init__.py", line 5, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by papr** [comment]
@sumiya-kuroda Hi! v1809 is a fairly old version of Windows 10. Could you check if there is a Windows udpate available for your PC and try running Capture after installing it?

**Comment by sumiya-kuroda** [comment]
Yes, after I updated my Windows OS, it starts to work with no problem. Thank you so much for the advice!

**Comment by papr** [comment]
This is great news! Thanks for letting us know!
