### ISSUE TITLE
Screen Marker Calibration crashes (v0.6.149)

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#237]
with error:

```
Starting Calibration
Traceback (most recent call last):
  File "<string>", line 145, in <module>
  File "<string>", line 138, in main
  File "C:\Users\mb\Documents\pupil\deploy_capture\build\bundle\out00-PYZ.pyz\world", line 327, in world
  File "C:\Users\mb\Documents\pupil\deploy_capture\build\bundle\out00-PYZ.pyz\calibration_routines.screen_marker_calibration", line 349, in gl_display
  File "C:\Users\mb\Documents\pupil\deploy_capture\build\bundle\out00-PYZ.pyz\calibration_routines.screen_marker_calibration", line 376, in gl_display_in_window

  File "pyglui\cygl\utils.pyx", line 102, in pyglui.cygl.utils.draw_concentric_circles (pyglui/cygl/utils.c:4020)
  File "pyglui\cygl\utils.pyx", line 163, in pyglui.cygl.utils.draw_concentric_circles (pyglui/cygl/utils.c:3564)
  File "pyglui\cygl\shader.pyx", line 39, in pyglui.cygl.shader.Shader.__init__(pyglui/cygl/shader.c:1711)
  File "pyglui\cygl\shader.pyx", line 92, in pyglui.cygl.shader.Shader._build_shader (pyglui/cygl/shader.c:2156)
Exception: Fragment compilation: ERROR: 0:20: 'const 2-element array of float' : cannot declare arrays of this qualifier
ERROR: 0:20: 'const' :  non-matching types (using implicit conversion) for const initializer
ERROR: 0:21: 'const 2-element array of float' : cannot declare arrays of this qualifier
ERROR: 0:21: 'const' :  non-matching types (using implicit conversion) for const initializer
ERROR: 0:23: 'colors' :  left of '[' is not of type array, matrix, or vector
ERROR: 0:24: 'colors2' :  left of '[' is not of type array, matrix, or vector
```

**Comment by MichaelBarz** [comment]
... I'll update pyglui and submodles and test again.

**Comment by mkassner** [comment]
@patrickFuerst  any idea? This is on windows.

**Comment by MichaelBarz** [comment]
In v0.6.9 the calibration target for Screen Marker Calibration was rendered from an image (as texture). The new version draws circles directly, is that right?

Since the accuracy test is related to this issue, the root is probably drawing the circles.

**Comment by mkassner** [comment]
This is a cygl problem with windows as you already noted.

**Comment by MichaelBarz** [comment]
This is not a problem anymore.
