### ISSUE TITLE
Capture crashes with most recent pyglui version (v0.6.149)

### ISSUE THREAD

**Issue by MichaelBarz** [pupil-labs/pupil#238]
Seems that Capture cannot load the fonts anymore... but they are available in the bundle.

```
Traceback (most recent call last):
  File "<string>", line 145, in <module>
  File "<string>", line 138, in main
  File "C:\Users\mb\Documents\pupil\deploy_capture\build\bundle\out00-PYZ.pyz\world", line 189, in world
  File "pyglui\ui.pyx", line 45, in pyglui.ui.UI.__cinit__ (pyglui/ui.c:5847)
  File "pyglui\pyfontstash\fontstash.pyx", line 32, in pyglui.pyfontstash.fontstash.Context.add_font (pyglui/pyfontstash/fontstash.c:1358)
Exception: Font could not be loaded from 'C:\Users\Michael\AppData\Roaming\Python-Eggs\pyglui-0.6-py2.7-win32.egg-tmp\pyglui\Roboto-Regular.ttf'.
```

**Comment by mkassner** [comment]
please make sure that your build process is clean. This is a build problem.

**Comment by MichaelBarz** [comment]
Ok, solved. The reason was that I updated pyglui via `setup.py install`. Reinstalling pyglui with

```
setup.py bdist_wheel
pip install --upgrade <wheel>
```

works! (I'll add this to the docs)
