### ISSUE TITLE
ValueError on loading Offline_Marker_Detector

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#248]
```
Player [INFO] plugin : Loaded: Offline_Marker_Detector
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/marker_detector_cacher.py", line 102, in fill_cache
    handle_frame(next)
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/marker_detector_cacher.py", line 77, in handle_frame
    markers[:] = detect_markers_robust(frame.gray,
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/video_capture/av_file_capture.py", line 76, in gray
    self._gray = np.frombuffer(self._av_frame.planes[0],np.uint8).reshape(self.height,self.width)
ValueError: total size of new array must be unchanged
```

**Comment by mkassner** [comment]
Hi,

Is this reproducible? Does this happen with all your videos? 

This bug is not related to the offline marker tracker but to av file capture. Its a bit odd to see this...

**Comment by cpicanco** [comment]
No, it is not related to the offline marker tracker. Yes it is reproducible, including new videos 0.6.x. The way I found the bug:

1) you must have no cached markers (delete it, if necessary)
2) then begin some routine using the `frame.gray`. For example, loading the plugin `offline_marker_detector.py` (that will call `fill_cache.handle_frame` in the `marker_detector_cacher.py`).

____

ps.: I am temporarily using the `frame.img` instead of `frame.gray` in a plugin and using cv2 to the conversion:
```
gray = cv2.cvtColor(frame.img,cv2.COLOR_BGR2GRAY)
```

By doing this, with longer videos (~5min+), the computer will soon get unresponsive (due player memory consumption). I am using a closing-opening technique, taking advantage of the real time cacher. :dancers:

**Comment by mkassner** [comment]
Hmm I cant reproduce this on mac. I ll try on Linux. 

The error comes from the buffer not reporting the correct size. 

could you try running pyav with a 

```
        print self.buffer_size
```

in def __getwritebuffer__(self, Py_ssize_t index, void **data): in  https://github.com/pupil-labs/PyAV/blob/master/av/plane.pyx

you'll need to rebuild pyav for this.

Then simply run av_capture.py pointing to one of the mp4 files that does not work for you.

Best,

M

**Comment by cpicanco** [comment]
Ok, will test.

**Comment by cpicanco** [comment]
Getting mostly `2764800` of size then `944640` produce the error.

**Comment by cpicanco** [comment]
Where is av_capture.py?

**Comment by cpicanco** [comment]
Ok, this one was an .mkv will test in a .mp4 now.

**Comment by cpicanco** [comment]
ok, I got it. With mkv and with mp4

```
Player [WARNING] plugin : Failed to load 'k_means'. Reason: '[Errno 2] No such file or directory: 'input.txt'' 
Player [INFO] plugin : Added: <class 'screen_detector.Screen_Detector'>
Player [INFO] plugin : Added: <class 'trim_marks_patch.Trim_Marks_Extended'>
Player [INFO] plugin : Added: <class 'kmeans_gaze_correction.KMeans_Gaze_Correction'>
Player [INFO] plugin : Added: <class 'filter_opencv_threshold.Filter_Opencv_Threshold'>
Player [INFO] plugin : Added: <class 'fixation_detector_patch.Dispersion_Duration_Fixation_Detector_Extended'>
Player [WARNING] plugin : Failed to load 'LICENSE'. Reason: 'need more than 1 value to unpack' 
Player [INFO] plugin : Added: <class 'display_recent_gaze_patch.Display_Recent_Gaze'>
Player [INFO] plugin : Added: <class 'vis_circle_on_contours.Vis_Circle_On_Contours'>
Player [WARNING] plugin : Failed to load '.git'. Reason: 'relative imports require the 'package' argument' 
Player [INFO] plugin : Added: <class 'segmentation.Segmentation'>
Player [INFO] plugin : Added: <class 'screen_offline_detector.Offline_Screen_Detector'>
Player [INFO] player_methods : Updatig recording from v0.4x format to current version
Player [INFO] plugin : Loaded: Trim_Marks
Player [INFO] plugin : Loaded: Seek_Bar
Player [INFO] plugin : Loaded: Log_Display
Player [INFO] plugin : Loaded: Offline_Marker_Detector
Player [INFO] plugin : Loaded: Vis_Circle
Player [WARNING] video_capture.av_file_capture : Filecapture is not a realtime source. -NOW- will be the current timestamp
944640
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
2764800    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/marker_detector_cacher.py", line 102, in fill_cache
    handle_frame(next)
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/marker_detector_cacher.py", line 77, in handle_frame
    markers[:] = detect_markers_robust(frame.gray,
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/video_capture/av_file_capture.py", line 76, in gray

    self._gray = np.frombuffer(self._av_frame.planes[0],np.uint8).reshape(self.width,self.height)
ValueError: total size of new array must be unchanged
```

**Comment by cpicanco** [comment]
Now mp4.

```
Player [INFO] plugin : Loaded: Trim_Marks
Player [INFO] plugin : Loaded: Seek_Bar
Player [INFO] plugin : Loaded: Log_Display
Player [INFO] plugin : Loaded: Offline_Marker_Detector
Player [INFO] plugin : Loaded: Vis_Circle
Player [WARNING] video_capture.av_file_capture : Filecapture is not a realtime source. -NOW- will be the current timestamp
2764800
944640
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/marker_detector_cacher.py", line 102, in fill_cache
    handle_frame(next)
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/marker_detector_cacher.py", line 77, in handle_frame
    markers[:] = detect_markers_robust(frame.gray,
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/video_capture/av_file_capture.py", line 76, in gray
    self._gray = np.frombuffer(self._av_frame.planes[0],np.uint8).reshape(self.width,self.height)
ValueError: total size of new array must be unchanged
```

**Comment by mkassner** [comment]
Sorry I did not make myself clear.

Please run the av_file_capture.py file.  You should change the bottom part to look like so:

```python
if __name__ == '__main__':
    import os
    import cv2
    logging.basicConfig(level=logging.DEBUG)
   
    file_loc = os.path.expanduser("~/Desktop/world.mp4") #this is the path to the file you want to test.
    logging.getLogger("libav").setLevel(logging.ERROR)

    cap = File_Capture(file_loc)
    print 'durantion',float(cap.container.duration/av.time_base)
    print 'frame_count', cap.get_frame_count()
    print "container timebase",av.time_base
    print 'time_base',cap.video_stream.time_base
    print 'avg rate',cap.video_stream.average_rate
    # exit()
    # print cap.video_stream.time_base
    import time
    frame = cap.get_frame_nowait()
    t = time.time()
    try:
        while 1:
            frame = cap.get_frame_nowait()
            frame.gray
            # print frame.index
            # cv2.imshow("test",frame.img)
            # print frame.index, frame.timestamp
            # if cv2.waitKey(30)==27:
            #     print "seeking to ",95
            #     cap.seek_to_frame(95)

    except EndofVideoFileError:
        print 'Video Over'
    print'avcapture took:', time.time()-t
```

**Comment by mkassner** [comment]
Also: I can run my files on Mac and Linux. I dont know what the problem is but I cant reproduce. Maybe you send me one of the files?

**Comment by cpicanco** [comment]
Just sent you a dropbox link.

**Comment by cpicanco** [comment]
Same stuff has ocurred when running the av_file_capture.py.

**Comment by mkassner** [comment]
Hi,

the video file is missing...

**Comment by cpicanco** [comment]
Sorry about thaaaaat! Video finished to upload now.

**Comment by mkassner** [comment]
I cant reproduce this :-(

**Comment by cpicanco** [comment]
Maybe hardware specific (Logitech C615). Will close this, please open if necessary. For now, I am simply skipping the frame as the error is easily catchable and occurs with very few frames.

**Comment by cpicanco** [comment]
Just want to make sure if this was not related to a bad ffmpg instalation.

**Comment by cpicanco** [comment]
Well, possibly a bad ffmpg instalation.
