### ISSUE TITLE
Capture does not record audio

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#253]
I am not sure if it is hardware specific, Logitech C615.

```
Failed to connect to Speech Dispatcher:
Error: Can't connect to unix socket /run/user/1000/speech-dispatcher/speechd.sock: No such file or directory. Autospawn: Autospawn failed. Speech Dispatcher refused to start with error code, stating this as a reason: 
WORLD Process [ERROR] libav.alsa : cannot set channel count to 2 (Invalid argument)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/av_writer.py", line 233, in rec_thread
    in_container = av.open('hw:%s'%audio_src,format="alsa")
  File "av/container.pyx", line 211, in av.container.open (src/av/container.c:3895)
  File "av/container.pyx", line 257, in av.container.InputContainer.__cinit__ (src/av/container.c:4959)
  File "av/container.pyx", line 189, in av.container.ContainerProxy.err_check (src/av/container.c:3729)
  File "av/utils.pyx", line 30, in av.utils.err_check (src/av/utils.c:969)
AVError: [Errno 5] Input/output error: 'hw:1'
```

**Comment by mkassner** [comment]
I could you post your outpit from 

```
arecord -l
```

?

**Comment by cpicanco** [comment]
```
**** List of CAPTURE Hardware Devices ****
card 0: MID [HDA Intel MID], device 0: 92HD81B1X5 Analog [92HD81B1X5 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: C615 [HD Webcam C615], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by mkassner** [comment]
I think this is a device specific problem. But I cant debug it myself without the hardware...

**Comment by cpicanco** [comment]
I don't need the audio for my current work. Just reporting, for your knowledge.
