### ISSUE TITLE
Camera intrinsics 

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#254]
I was exploring the calibration methods and found this. By the way, how are you using this "intrinsics" data?
```
Traceback (most recent call last):
  File "/home/rafael/git/pupil_0.6/pupil_src/capture/main.py", line 145, in <module>
    main()
  File "/home/rafael/git/pupil_0.6/pupil_src/capture/main.py", line 138, in main
    world(g_pool,world_src,world_size)
  File "/home/rafael/git/pupil_0.6/pupil_src/capture/world.py", line 320, in world
    p.update(frame,events)
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/calibration_routines/camera_intrinsics_estimation.py", line 225, in update
    self.calculate()
  File "/home/rafael/git/pupil_0.6/pupil_src/shared_modules/calibration_routines/camera_intrinsics_estimation.py", line 209, in calculate
    self.camera_intrinsics = camera_matrix,dist_coefs,resolution
NameError: global name 'resolution' is not defined
```

**Comment by mkassner** [comment]
Hi,

yes, I saw that bug too and fixed it. We use the intrinsics for our new
vector calibration routines and 3d pose estimation form markers.

Best,

Moritz

**Comment by cpicanco** [comment]
3d eye model = vector calibration = Happy Christmas? :smile:
