### ISSUE TITLE
notes on cpp_2d_3d_detector and new dependencies

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#284]
I successfully installed the new '3d eye model' dependencies. As usual, I just want to share my experience. First, I would like to note that the instruction:

```
curl https://gist.githubusercontent.com/mkassner/1caa1b45c19521c884d5/raw/b5ce332808b8e26406af0db78115761ea605441c/install_ffmpeg_ubuntu.sh | bash

```
did not work for me. I moved to manually installing the stuff in the gist.
 
I am having difficulties to run some tests. I think I am missing something related to the cpp environment, setup_test.py/build_test.py will return the following (for SphereCircleTests and CircleGoodnessTest):
```
CircleGoodnessTest.cpp:283:45: fatal error: singleeyefitter/singleeyefitter.h: No such file or directory
 #include "singleeyefitter/singleeyefitter.h"
                                             ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
Maybe those tests are just not self contained yet, as the file `singleeyefitter.h_unused` makes me think.

Also, the detector test will not run:
```
# cap_src = <my_path>/eye0.mkv
No handlers could be found for logger "video_capture.av_file_capture"
Traceback (most recent call last):
  File "/home/rafael/git/pupil/pupil_src/capture/pupil_detectors/Tests/DetectorTests/test_detectors.py", line 265, in <module>
    compare_test_cpp()
  File "/home/rafael/git/pupil/pupil_src/capture/pupil_detectors/Tests/DetectorTests/test_detectors.py", line 175, in compare_test_cpp
    reference_result = load_object( test_file_Folder + 'result_frame_cpp{}'.format(frameNumber))
  File "/home/rafael/git/pupil/pupil_src/shared_modules/file_methods.py", line 47, in load_object
    with open(file_path,'rb') as fh:
IOError: [Errno 2] No such file or directory: '../../../../../Pupil_Test_Files/cpp/result_frame_cpp1'
```
How to produce this "result_frame_cpp1"?

Was necessary to include the eigen3 path to the projection test
```
if __name__ == '__main__':
    import subprocess as sp
    sp.call("g++ -std=c++11 -I /usr/local/include/eigen3 -g projectionTest.cpp -o test",shell=True)
    print "BUILD COMPLETE ______________________"
    sp.call("./test",shell=True)
```

Also, I am getting the following error when trying to start the eye process in capture:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rafael/git/pupil/pupil_src/capture/eye.py", line 94, in eye
    from pupil_detectors import Canny_Detector, Detector_2D, Detector_3D
  File "/home/rafael/git/pupil/pupil_src/capture/pupil_detectors/__init__.py", line 13, in <module>
    from detector_3d import Detector_3D
ImportError: /home/rafael/git/pupil/pupil_src/capture/pupil_detectors/detector_3d.so: undefined symbol: _ZN2cv12KalmanFilterC1Eiiii
```
It means a bad compilation or not finished yet?

**Comment by patrickFuerst** [comment]
Hey Rafael, 

thanks for the feedback. 

Regarding the tests: 

Most of the code we don't even use anymore. But obviously I didn't clean up the branch. 
We plan to merge to master very soon, so next thing on the list is to clean this up. 

Regarding the detector_3d error: 
Were you able to build everything without errors ?
Since KalmanFilter is an OpenCv class, it should be there.

**Comment by patrickFuerst** [comment]
f617dd14f34917c2f53353441a4eda4fab16cbd8 , 2cb88ea0800a4b1357a760359878531514a1a9d7 and 935935d4cb8f6c198ab58f629a019d56af474f55 are fixing the test cases. 

@cpicanco  in order to run the detector test successfully you first need to write the test files. 
Have a look on the last lines of test_detector.py [here](https://github.com/pupil-labs/pupil/blob/cpp_2d_3d_detector/pupil_src/capture/pupil_detectors/Tests/DetectorTests/test_detectors.py#L261-L267) and uncomment the right one.

**Comment by cpicanco** [comment]
As far as I know yes, without errors, but lot of warnings. I will double check the opencv installation and rebuild the detector though.

**Comment by cpicanco** [comment]
@patrickFuerst , are you using the `python-opencv` or something else?

**Comment by mkassner** [comment]
I think this could be ralated to the fact that we use this for developement:

```shell
wget -O OpenCV-2.4.9.zip http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/2.4.9/opencv-2.4.9.zip/download
unzip OpenCV-2.4.9.zip
cd opencv-2.4.9
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_SKIP_RPATH=ON -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=OFF -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF -D WITH_QT=OFF -D WITH_OPENGL=OFF -D WITH_FFMPEG=OFF -D WITH_GSTREAMER=OFF ..
make -j4
sudo make install
sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
sudo ldconfig
```


I think the problem is that the apt-get version is not found during runtime the way we are building our extensions right now.

**Comment by patrickFuerst** [comment]
@cpicanco last commit fixes it on ubuntu. Not realy sure why it worked on osx.

**Comment by cpicanco** [comment]
Good. :+1:

**Comment by cpicanco** [comment]
I am afraid the fix does not work.

**Comment by patrickFuerst** [comment]
can you check which libraries  detector_3d.so is linking to. 
for me it looks like this. 
```
pupil-labs@ubuntu:~/pupil/pupil_src/capture/pupil_detectors$ ldd detector_3d.so 
	linux-vdso.so.1 =>  (0x00007ffd798fe000)
	libopencv_core.so.2.4 => /usr/local/lib/libopencv_core.so.2.4 (0x00007f8467249000)
	libopencv_imgproc.so.2.4 => /usr/local/lib/libopencv_imgproc.so.2.4 (0x00007f8466d61000)
	libopencv_video.so.2.4 => /usr/local/lib/libopencv_video.so.2.4 (0x00007f8466b07000)
	libceres.so.1 => /usr/local/lib/libceres.so.1 (0x00007f84666b4000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f84663a7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f84660a0000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8465e89000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8465ac4000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f84658aa000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f846568c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8465484000)
	libglog.so.0 => /usr/lib/x86_64-linux-gnu/libglog.so.0 (0x00007f846524b000)
	libspqr.so.1.3.1 => /usr/lib/x86_64-linux-gnu/libspqr.so.1.3.1 (0x00007f8465020000)
	libcholmod.so.2.1.2 => /usr/lib/x86_64-linux-gnu/libcholmod.so.2.1.2 (0x00007f8464d4d000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f84645b0000)
	libf77blas.so.3 => /usr/lib/libf77blas.so.3 (0x00007f8464390000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f846416e000)
	/lib64/ld-linux-x86-64.so.2 (0x00005621bb7aa000)
	libgflags.so.2 => /usr/lib/x86_64-linux-gnu/libgflags.so.2 (0x00007f8463f4d000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f8463d32000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f8463766000)
	libamd.so.2.3.1 => /usr/lib/x86_64-linux-gnu/libamd.so.2.3.1 (0x00007f846355c000)
	libcolamd.so.2.8.0 => /usr/lib/x86_64-linux-gnu/libcolamd.so.2.8.0 (0x00007f8463355000)
	libcamd.so.2.3.1 => /usr/lib/x86_64-linux-gnu/libcamd.so.2.3.1 (0x00007f846314b000)
	libccolamd.so.2.8.0 => /usr/lib/x86_64-linux-gnu/libccolamd.so.2.8.0 (0x00007f8462f40000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f8462c26000)
	libcblas.so.3 => /usr/lib/libcblas.so.3 (0x00007f8462a05000)
	libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007f8462471000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f846226d000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f846204b000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f8461e0b000)
```

and if I remove libopencv_video again it doesn't work.

**Comment by cpicanco** [comment]
Hi, I think the problem was that the *.so wasn't being rewritten with

```
sudo python setup.py install
```

After deleting the detector_2d.so and detector_3d.so and running `sudo python build.py`:

```
rafael@B14HM21:~/git/pupil/pupil_src/capture/pupil_detectors$ ldd detector_3d.so 
	linux-vdso.so.1 =>  (0x00007ffdce4ff000)
	libopencv_core.so.2.4 => /usr/local/lib/libopencv_core.so.2.4 (0x00007fd602ff9000)
	libopencv_imgproc.so.2.4 => /usr/local/lib/libopencv_imgproc.so.2.4 (0x00007fd602b11000)
	libopencv_video.so.2.4 => /usr/local/lib/libopencv_video.so.2.4 (0x00007fd6028b8000)
	libceres.so.1 => /usr/local/lib/libceres.so.1 (0x00007fd602462000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd602155000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd601e4f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd601c38000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd601873000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd60165a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd60143c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd601234000)
	libglog.so.0 => /usr/lib/x86_64-linux-gnu/libglog.so.0 (0x00007fd600ffc000)
	libspqr.so.1.3.1 => /usr/lib/x86_64-linux-gnu/libspqr.so.1.3.1 (0x00007fd600dd1000)
	libcholmod.so.2.1.2 => /usr/lib/x86_64-linux-gnu/libcholmod.so.2.1.2 (0x00007fd600afe000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007fd600362000)
	libf77blas.so.3 => /usr/lib/libf77blas.so.3 (0x00007fd600142000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fd5fff20000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd603718000)
	libgflags.so.2 => /usr/lib/x86_64-linux-gnu/libgflags.so.2 (0x00007fd5ffd00000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007fd5ffae5000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007fd5ff519000)
	libamd.so.2.3.1 => /usr/lib/x86_64-linux-gnu/libamd.so.2.3.1 (0x00007fd5ff310000)
	libcolamd.so.2.8.0 => /usr/lib/x86_64-linux-gnu/libcolamd.so.2.8.0 (0x00007fd5ff109000)
	libcamd.so.2.3.1 => /usr/lib/x86_64-linux-gnu/libcamd.so.2.3.1 (0x00007fd5feeff000)
	libccolamd.so.2.8.0 => /usr/lib/x86_64-linux-gnu/libccolamd.so.2.8.0 (0x00007fd5fecf5000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fd5fe9d4000)
	libcblas.so.3 => /usr/lib/libcblas.so.3 (0x00007fd5fe7b3000)
	libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007fd5fe220000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd5fe01c000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fd5fddfa000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fd5fdbbb000)
```

**Comment by patrickFuerst** [comment]
Hi, 

that's right. you need to call ```sudo python build.py``` inorder to recompile the c++ extensions. 
And they just get recompiled if one of the c++ files changed. So if you just change the setup.py file it won't recompile. 

For now you need to resave any c++ file inorder to force cython to recompile the both 2D and 3D extensions.

**Comment by cpicanco** [comment]
:)
![screenshot from 2016-01-22 08 58 46](https://cloud.githubusercontent.com/assets/6511849/12510161/95e880f4-c0e6-11e5-9068-185bfe3cf57c.png)
