### ISSUE TITLE
Crashes on Calibration

### ISSUE THREAD

**Issue by mothman1** [pupil-labs/pupil#328]
System crashes on calibration - I use apple mac pro retina display and I used to get this error in earlier versions with screen marker calibration until I was told to not use fullscreen that makes it possible to calibrate. However, with the new version of Pupil-Labs I no longer can calibrate regardless of fullscreen or not

here is the error stack I get

OpenCV Error: Assertion failed (step[dims-1] == (size_t)CV_ELEM_SIZE(flags)) in create, file /tmp/opencv20160219-62336-1nvqwmy/opencv-2.4.12/modules/core/src/matrix.cpp, line 236
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Developments/NCLUni/pupil-master-19Feb16/pupil_src/capture/world.py", line 403, in world
    p.update(frame,events)
  File "/Developments/NCLUni/pupil-master-19Feb16/pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py", line 252, in update
    visual_debug=False)
  File "/Developments/NCLUni/pupil-master-19Feb16/pupil_src/shared_modules/circle_detector.py", line 24, in get_candidate_ellipses
    method=cv2.CHAIN_APPROX_NONE,offset=(0,0)) #TC89_KCOS
error: /tmp/opencv20160219-62336-1nvqwmy/opencv-2.4.12/modules/core/src/matrix.cpp:236: error: (-215) step[dims-1] == (size_t)CV_ELEM_SIZE(flags) in function create

**Comment by mkassner** [comment]
Hi,

this error is not related to the prior error you had been getting. I m not sure what the issue is here. Does this happen when running from the bundle as well? It might be an opencv incompatibility.

Best,

Moritz

**Comment by mothman1** [comment]
Following PatrickFuerst recent work with OpenCv3 solved my problem. Thanks
