### ISSUE TITLE
pupil server crashes

### ISSUE THREAD

**Issue by Tobias-Fischer** [pupil-labs/pupil#387]
Hi @mkassner.
The recent commit https://github.com/pupil-labs/pupil/commit/5cf1801ffb71a73ef7a7a65ea07c549b5da81782 leads to the following crash on my machine:
```
tobias@deepthought:~/robot/pupil/pupil/pupil_src/capture$ python main.py 
running build_ext
Estimated / selected altsetting bandwith : 815 / 1600. 
world - [WARNING] world : Eye 0 process started.
running build_ext
eye0 - [WARNING] video_capture : Camera 'Pupil Cam1 ID0' matches the pattern but is already in use
eye0 - [ERROR] video_capture : No accessible device found that matched ['Pupil Cam1 ID0', 'HD-6000', 'Integrated Camera', 'HD USB Camera', 'USB 2.0 Camera']
eye0 - [WARNING] video_capture : Starting with Fake_Capture.
world - [ERROR] pupil_server : No such file or directory
dt 0.0319759845734
Process world:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tobias/robot/pupil/pupil/pupil_src/capture/world.py", line 430, in world
    p.update(frame,events)
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/pupil_server.py", line 78, in update
    for d in data:
TypeError: 'float' object is not iterable
^CTraceback (most recent call last):
  File "main.py", line 109, in <module>
    main()
  File "main.py", line 87, in main
    cmd = cmd_launcher_end.recv()
KeyboardInterrupt
Process eye0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tobias/robot/pupil/pupil/pupil_src/capture/eye.py", line 345, in eye
    frame = cap.get_frame()
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/video_capture/uvc_capture.py", line 149, in get_frame
    frame = self.capture.get_frame_robust()
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/video_capture/fake_capture.py", line 81, in get_frame_robust
    return self.get_frame()
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/video_capture/fake_capture.py", line 74, in get_frame
    sleep(wait)
KeyboardInterrupt
```

Reverting back to the previous version fixes the problem. The problem is with the `dt` topic (not sure what that is) which only receives a float.

Best, Tobias

**Comment by mkassner** [comment]
Thanks for catching that. I just fixed it.
