### ISSUE TITLE
3D Localization for surface tracker is not working

### ISSUE THREAD

**Issue by Tobias-Fischer** [pupil-labs/pupil#391]
Hi,

Unfortunately the surface tracking is crashing when I select the 3D localization:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tobias/robot/pupil/pupil/pupil_src/capture/world.py", line 430, in world
    p.update(frame,events)
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/surface_tracker.py", line 206, in update
    s.locate(self.markers,self.camera_calibration,self.min_marker_perimeter, self.locate_3d)
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/reference_surface.py", line 207, in locate
    res = self._get_location(visible_markers,camera_calibration,min_marker_perimeter,locate_3d)
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/reference_surface.py", line 291, in _get_location
    is3dPoseAvailable, rot3d_cam_to_object, translate3d_cam_to_object = cv2.solvePnP(uv3d, yx, K, dist_coef,flags=cv2.CV_EPNP)
NameError: global name 'yx' is not defined
```

It seems like `yx` was removed in the following commit: https://github.com/pupil-labs/pupil/commit/5a1b28eff5a3421fa85a48fbd8beb4469679ce46

I am not sure how to fix it. Would be great if you point me to the correct spot.

Thanks a lot,
Tobias

**Comment by mkassner** [comment]
Alright. I think I fixed this one.

**Comment by Tobias-Fischer** [comment]
Works perfectly, thank you very much!
