### ISSUE TITLE
Capture does not start after  revisions to idle sleep utility

### ISSUE THREAD

**Issue by Tobias-Fischer** [pupil-labs/pupil#433]
Hi,
I get this error when trying to start capture.
```
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    from os_utils import Prevent_Idle_Sleep
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/os_utils.py", line 19, in <module>
    mac_major,mac_minor,mac_patch = map(int,mac_version[0].split('.'))
ValueError: invalid literal for int() with base 10: ''
```
I'm on Ubuntu 14.04.
Relevant commit: https://github.com/pupil-labs/pupil/commit/8857db976c2d94fef7370d27cf4b7c9178bbcfe5

Best, Tobias

**Comment by mkassner** [comment]
Sorry about that. This should have been caught before pushing to master :-(.

**Comment by Tobias-Fischer** [comment]
Thanks!
