### ISSUE TITLE
ImportError ndsi

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#515]
Not sure why I am getting this. Trying to run from source. Clean install.

```
Traceback (most recent call last):
  File "/home/rafael/git/pupil/pupil_src/player/main.py", line 88, in <module>
    from video_capture import File_Source,EndofVideoFileError,FileSeekError
  File "/home/rafael/git/pupil/pupil_src/shared_modules/video_capture/__init__.py", line 27, in <module>
    from ndsi_backend import NDSI_Source, NDSI_Manager
  File "/home/rafael/git/pupil/pupil_src/shared_modules/video_capture/ndsi_backend.py", line 14, in <module>
    import ndsi
  File "/usr/local/lib/python2.7/dist-packages/ndsi/__init__.py", line 23, in <module>
    from network import Network
  File "ndsi/sensor.pxd", line 13, in init ndsi.network (ndsi/network.c:4610)
  File "ndsi/sensor.pyx", line 13, in init ndsi.sensor (ndsi/sensor.c:20928)
  File "/usr/lib/python2.7/dist-packages/zmq/__init__.py", line 49, in <module>
    from zmq.backend import *
  File "/usr/lib/python2.7/dist-packages/zmq/backend/__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "/usr/lib/python2.7/dist-packages/zmq/backend/__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "/usr/lib/python2.7/dist-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/usr/lib/python2.7/dist-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /usr/lib/python2.7/dist-packages/zmq/backend/cython/utils.x86_64-linux-gnu.so: undefined symbol: zmq_curve_keypair
```

**Comment by cpicanco** [comment]
Just a bad zmq install.
