### ISSUE TITLE
Capture crashing when 'add surface' is clicked

### ISSUE THREAD

**Issue by elmorg** [pupil-labs/pupil#529]
When I select 'add surface' in the surface tracking plugin the World window disappears. If I want to restart then I have to restart once and force quit before it will work again. Using Mac 10.11.6, and latest version of the Capture software.

**Comment by mkassner** [comment]
Hi could you please start the software via command line and post the output when it crashes?

**Comment by elmorg** [comment]
Traceback (most recent call last):
  File "/Users/pupil/pupil/deployment/deploy_capture/build/bundle/out00-PYZ.pyz/billiard.process", line 287, in _bootstrap
  File "/Users/pupil/pupil/deployment/deploy_capture/build/bundle/out00-PYZ.pyz/billiard.process", line 121, in run
  File "/Users/pupil/pupil/deployment/deploy_capture/build/bundle/out00-PYZ.pyz/world", line 479, in world
  File "/Users/pupil/pupil/deployment/deploy_capture/build/bundle/out00-PYZ.pyz/surface_tracker", line 207, in update
  File "/Users/pupil/pupil/deployment/deploy_capture/build/bundle/out00-PYZ.pyz/reference_surface", line 412, in map_data_to_surface
  File "/Users/pupil/pupil/deployment/deploy_capture/build/bundle/out00-PYZ.pyz/reference_surface", line 409, in map_datum_to_surface
KeyError: 'topic'

**Comment by elmorg** [comment]
When running from source I get a similar output: 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/billiard/process.py", line 292, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/site-packages/billiard/process.py", line 123, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/emorgan/GitHub/pupil/pupil_src/capture/world.py", line 477, in world
    p.update(frame,events)
  File "/Users/emorgan/GitHub/pupil/pupil_src/shared_modules/surface_tracker.py", line 207, in update
    s.gaze_on_srf = s.map_data_to_surface(events.get('gaze_positions',[]),s.m_from_screen)
  File "/Users/emorgan/GitHub/pupil/pupil_src/shared_modules/reference_surface.py", line 412, in map_data_to_surface
    return [self.map_datum_to_surface(d,m_from_screen) for d in data]
  File "/Users/emorgan/GitHub/pupil/pupil_src/shared_modules/reference_surface.py", line 409, in map_datum_to_surface
    return {'topic':d['topic']+"_on_surface",'norm_pos':(mapped_pos[0],mapped_pos[1]),'confidence':d['confidence'],'on_srf':on_srf,'base_data':d }
KeyError: 'topic'

**Comment by mkassner** [comment]
Yes error appears when an older version of the detector extensions is running. This is odd. I ll have a look.

**Comment by mkassner** [comment]
This is fixed now.
