### ISSUE TITLE
Selecting Pupil Mobile in Eye Process -> Crash

### ISSUE THREAD

**Issue by PolynomialDivision** [pupil-labs/pupil#547]
When you select 'Pupil Mobile' in the Eye Window Pupil will crash.

    Process eye0:
    Traceback (most recent call last):
      File "multiprocessing\process.py", line 249, in _bootstrap
      File "multiprocessing\process.py", line 93, in run
      File "eye.py", line 524, in eye
      File "pyglui\ui.pyx", line 169, in pyglui.ui.UI.update (pyglui/ui.cpp:8760)
      File "pyglui\ui.pyx", line 137, in pyglui.ui.UI.handle_input (pyglui/ui.cpp:8298)
      File "pyglui\menus.pxi", line 525, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.cpp:41331)
      File "pyglui\menus.pxi", line 542, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.cpp:41113)
      File "pyglui\menus.pxi", line 360, in pyglui.ui.Growing_Menu.handle_input (pyglui/ui.cpp:38407)
      File "pyglui\menus.pxi", line 370, in pyglui.ui.Growing_Menu.handle_input (pyglui/ui.cpp:38267)
      File "pyglui\ui_elements.pxi", line 409, in pyglui.ui.Selector.handle_input (pyglui/ui.cpp:19409)
      File "pyglui\ui_elements.pxi", line 420, in pyglui.ui.Selector.handle_input (pyglui/ui.cpp:19251)
      File "pyglui\ui_elements.pxi", line 439, in pyglui.ui.Selector.finish_selection (pyglui/ui.cpp:19705)
      File "pyglui\ui.pyx", line 332, in pyglui.ui.Synced_Value.value.__set__ (pyglui/ui.cpp:43408)
      File "eye.py", line 311, in open_manager
      File "video_capture\ndsi_backend.py", line 275, in init_gui
      File "video_capture\ndsi_backend.py", line 266, in host_selection_list
    AttributeError: 'dict' object has no attribute 'iteritems'

I'm using Windows Version v0.8.7-w.

**Comment by papr** [comment]
According to [this](http://stackoverflow.com/a/30418498/5859392), it is a Python 3 issue. I was not aware of the incompatibility. I will work on fixing all the occurrences of this issue.

**Comment by papr** [comment]
These fixes will be included in the next release.
