### ISSUE TITLE
v0.4 World Recorder menu is non responsive.

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#56]
On linux. That is it.

**Comment by mkassner** [comment]
Hmm,

it seems that the recorder plugin is not loading properly.

**Comment by mkassner** [comment]
Please try again with lastest version...

**Comment by cpicanco** [comment]
Trying v0.4_restruct (687db8771a356eaa00ae5353575b0a5cd97c40da)

**Comment by cpicanco** [comment]
```bash
Traceback (most recent call last):
  File "/home/rafael/bin/pupil/pupil_src/capture/main.py", line 78, in <module>
    from world import world
  File "/home/rafael/bin/pupil/pupil_src/capture/world.py", line 47, in <module>
    from calibration_routines import calibration_plugins, gaze_mapping_plugins
  File "/home/rafael/bin/pupil/pupil_src/capture/calibration_routines/__init__.py", line 17, in <module>
    from screen_marker_calibration import Screen_Marker_Calibration
  File "/home/rafael/bin/pupil/pupil_src/capture/calibration_routines/screen_marker_calibration.py", line 30, in <module>
    from pyglui.ui import get_opensans_font_path
ImportError: cannot import name get_opensans_font_path
```

**Comment by mkassner** [comment]
Please pull and rebuild pyglui.

**Comment by cpicanco** [comment]
Recorder Menu is responsive, but C (calibration) button was gone. Clicking on Screen Marker Calibration dropdown item freezes everything (but see next log):
```bash
starting PUPIL capture python script
WORLD Process [DEBUG] c_methods : Compiling now.
WORLD Process [DEBUG] c_methods : Compiler status: make: Nothing to be done for `make_all'.

WORLD Process [DEBUG] c_methods : Compiling done.
EYE Process [ERROR] uvc_capture : No device found that matched ['USB 2.0 Camera', 'Microsoft', '6000', 'Integrated Camera']
EYE Process [DEBUG] uvc_capture.fake_capture : Capture will run with app wide adjustable timebase
WORLD Process [DEBUG] file_methods : Session settings file '/home/rafael/bin/pupil/capture_settings/user_settings_world' not found. Will make new one on exit.
WORLD Process [ERROR] uvc_capture : No device found that matched ['Logitech Camera', '(046d:081d)', 'C510', 'B525', 'C525', 'C615', 'C920', 'C930e']
WORLD Process [DEBUG] uvc_capture.fake_capture : Capture will run with app wide adjustable timebase
WORLD Process [INFO] plugin : Loading plugin: Dummy_Gaze_Mapper with settings {}
WORLD Process [DEBUG] plugin : Loaded Plugin: <calibration_routines.gaze_mappers.Dummy_Gaze_Mapper object at 0x2ebd150>
WORLD Process [INFO] plugin : Loading plugin: Display_Recent_Gaze with settings {}
WORLD Process [DEBUG] plugin : Loaded Plugin: <display_recent_gaze.Display_Recent_Gaze object at 0x2ebd1d0>
WORLD Process [INFO] plugin : Loading plugin: Screen_Marker_Calibration with settings {}
WORLD Process [WARNING] plugin : Plugin 'Screen_Marker_Calibration' failed to load from settings file. Becasue of Error:'pyglui.pyfontstash.fontstash.Context' object has no attribute 'set_align_string'
WORLD Process [INFO] plugin : Loading plugin: Recorder with settings {}
WORLD Process [DEBUG] plugin : Loaded Plugin: <recorder.Recorder object at 0x2ebd210>
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    main()
  File "main.py", line 136, in main
    world(g_pool,world_src,world_size)
  File "/home/rafael/bin/pupil/pupil_src/capture/world.py", line 339, in world
    g_pool.gui.update()
  File "pyglui/ui.pyx", line 130, in pyglui.ui.UI.update (pyglui/ui.c:7248)
  File "pyglui/ui.pyx", line 98, in pyglui.ui.UI.handle_input (pyglui/ui.c:6785)
  File "pyglui/menus.pxi", line 524, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.c:37851)
  File "pyglui/menus.pxi", line 540, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.c:37639)
  File "pyglui/menus.pxi", line 303, in pyglui.ui.Growing_Menu.handle_input (pyglui/ui.c:33974)
  File "pyglui/menus.pxi", line 312, in pyglui.ui.Growing_Menu.handle_input (pyglui/ui.c:33834)
  File "pyglui/ui_elements.pxi", line 403, in pyglui.ui.Selector.handle_input (pyglui/ui.c:17162)
  File "pyglui/ui_elements.pxi", line 415, in pyglui.ui.Selector.handle_input (pyglui/ui.c:17016)
  File "pyglui/ui_elements.pxi", line 431, in pyglui.ui.Selector.finish_selection (pyglui/ui.c:17366)
  File "pyglui/ui.pyx", line 266, in pyglui.ui.Synced_Value.value.__set__ (pyglui/ui.c:39758)
  File "/home/rafael/bin/pupil/pupil_src/capture/world.py", line 172, in set_calibration_plugin
    new_plugin = new_calibration(g_pool)
  File "/home/rafael/bin/pupil/pupil_src/capture/calibration_routines/screen_marker_calibration.py", line 126, in __init__
    self.glfont.set_align_string(v_align='center')
AttributeError: 'pyglui.pyfontstash.fontstash.Context' object has no attribute 'set_align_string'
```

**Comment by cpicanco** [comment]
Sorry, but no cameras were attached this time!! I will test with cameras now.

**Comment by cpicanco** [comment]
Pull command have a --recursive flag as well??

**Comment by cpicanco** [comment]
Cloning with --recursive works.

**Comment by cpicanco** [comment]
Selecting items Camera intrinsic and Accuracy Test on Calibration Menu dropdown changes the order of C and R buttons... What is it for? rsrsrs

**Comment by cpicanco** [comment]
Open Plugin dropdown is fully functional? What I should expect when selecting an item? Maybe a brief caption description to each item would be great...

**Comment by cpicanco** [comment]
Mouse keeps visible when calibrating. Should be invisible.
