### ISSUE TITLE
OpenGL context is below 2.1

### ISSUE THREAD

**Issue by madtulip** [pupil-labs/pupil#609]
Using a fresh installation of Ubuntu 16.04 and following these steps.:

https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-Linux
https://github.com/pupil-labs/pupil/wiki/Developer-Setup

the capture software does not start with this error.:

`Process world:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pupil/pupil/pupil_src/capture/world.py", line 292, in world
    cygl.utils.init()
  File "pyglui/cygl/utils.pyx", line 48, in pyglui.cygl.utils.init (pyglui/cygl/utils.cpp:3484)
  File "pyglui/cygl/utils.pyx", line 63, in pyglui.cygl.utils.init (pyglui/cygl/utils.cpp:3422)
Exception: This OpenGL context is below 2.1.`

$ sudo pip3 install --upgrade pyopengl

returns

`Requirement already up-to-date: pyopengl in /usr/local/lib/python3.5/dist-packages`

**Comment by mkassner** [comment]
This may be a problem of your graphics card driver.
