### ISSUE TITLE
Ubuntu installation problem!

### ISSUE THREAD

**Issue by kamiartik** [pupil-labs/pupil#613]
I installed everything that is necessary with no error. In the end, I encountered a problem when I wrote 'python main.py' to the terminal.  

The problem is:

Traceback (most recent call last):
  File "main.py", line 49, in <module>
    from multiprocessing import Process, Value,active_children,freeze_support,set_start_method
ImportError: cannot import name set_start_method

How can I overcome with this issue?

**Comment by papr** [comment]
Dear @kamiartik, please try running `python3 main.py`

**Comment by kamiartik** [comment]
Now I had the following lines but nothing was launched. Thank you.

MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] world: Application Version: 0.8.8.134
world - [INFO] world: System Info: User: kamiartik, Platform: Linux, Machine: kamiartik, Release: 4.4.0-31-generic, Version: #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016
world - [INFO] pupil_detectors.build: Building extention modules... ['pupil_detectors.detector_2d', 'pupil_detectors.detector_3d']
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from singleeyefitter/mathHelper.h:7:0,
                 from ../../shared_cpp/include/geometry/Conic.h:5,
                 from singleeyefitter/projection.h:8,
                 from ../../shared_cpp/include/common/types.h:8,
                 from detector_2d.cpp:516:
../../shared_cpp/include/common/traits.h:5:23: fatal error: ceres/jet.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Process world:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kamiartik/Pupil/pupil/pupil_src/capture/world.py", line 94, in world
    import pupil_detectors
  File "/home/kamiartik/Pupil/pupil/pupil_src/capture/pupil_detectors/__init__.py", line 16, in <module>
    build_cpp_extension()
  File "/home/kamiartik/Pupil/pupil/pupil_src/capture/pupil_detectors/build.py", line 27, in build_cpp_extension
    ret = sp.check_output(build_cmd.format(sys.executable, install_loc), shell=True).decode()
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/usr/bin/python3 setup.py install --install-lib=/home/kamiartik/Pupil/pupil/pupil_src/capture' returned non-zero exit status 1
^CTraceback (most recent call last):
  File "main.py", line 254, in <module>
    launcher()
  File "main.py", line 225, in launcher
    topic,n = cmd_sub.recv()
  File "/home/kamiartik/Pupil/pupil/pupil_src/shared_modules/zmq_tools.py", line 84, in recv
    topic = self.socket.recv_string()
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 457, in recv_string
    msg = self.recv(flags=flags)
  File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7683)
  File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7460)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2344)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9621)
KeyboardInterrupt

**Comment by papr** [comment]
Dear @kamiartik 

> ../../shared_cpp/include/common/traits.h:5:23: **fatal error**: ceres/jet.h: No such file or directory
compilation terminated.

It looks like that you did not install ceres or the installation was not completed correctly.
Please make sure that you followed all installation steps:

> \# install ceres-solver
git clone https://ceres-solver.googlesource.com/ceres-solver
cd ceres-solver
mkdir build && cd build
cmake .. -DBUILD_SHARED_LIBS=ON 
make -j3
make test
sudo make install
sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/ceres.conf'
sudo ldconfig

[Source](https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-Linux)

**Comment by kamiartik** [comment]
Now I am taking this error when I execute the **python3 main.py** 

MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] world: Application Version: 0.8.8.134
world - [INFO] world: System Info: User: kamiartik, Platform: Linux, Machine: kamiartik, Release: 4.4.0-31-generic, Version: #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016
world - [INFO] pupil_detectors.build: Building extention modules... ['pupil_detectors.detector_2d', 'pupil_detectors.detector_3d']
Process world:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kamiartik/Pupil/pupil/pupil_src/capture/world.py", line 94, in world
    import pupil_detectors
  File "/home/kamiartik/Pupil/pupil/pupil_src/capture/pupil_detectors/__init__.py", line 19, in <module>
    from .detector_3d import Detector_3D
ImportError: libceres.so.1: cannot open shared object file: No such file or directory


However I have the libcere.so.1 file in ceres folder. Thank you for helping

**Comment by mkassner** [comment]
This means the runtime linker is not properly finding libceres. Make sure to run sudo ldconfig after ceres install.

**Comment by kamiartik** [comment]
Thank you very much for your support

**Comment by mkassner** [comment]
I guess we can close this...
