### ISSUE TITLE
Surface Tracker: OpenCV Error (on Linux)

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#615]
Linux, Capture v0.8.7 bundle

Playing with one marker and I got this one.
```
OpenCV Error: Assertion failed (scn + 1 == m.cols && (depth == CV_32F || depth == CV_64F)) in perspectiveTransform, file /home/pupil-labs/opencv-2.4.9/modules/core/src/matmul.cpp, line 1936
Process world:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "world.py", line 477, in world
  File "surface_tracker.py", line 207, in update
  File "reference_surface.py", line 412, in map_data_to_surface
  File "reference_surface.py", line 406, in map_datum_to_surface
error: /home/pupil-labs/opencv-2.4.9/modules/core/src/matmul.cpp:1936: error: (-215) scn + 1 == m.cols && (depth == CV_32F || depth == CV_64F) in function perspectiveTransform

```

**Comment by Aeefire** [comment]
Sounds like the same problem I created a duplicate issue for (on Windows). 

Main issue is here: https://github.com/pupil-labs/pupil/issues/598

**Comment by cpicanco** [comment]
Thank you, I guess I can close this one.
