### ISSUE TITLE
Error: Disabling idle sleep not supported on this OS version

### ISSUE THREAD

**Issue by nnnnicholas** [pupil-labs/pupil#623]
Hi I'm new to Pupil. I downloaded, unzipped, and launched pupil_capture.exe. I am running Windows 10 Pro x64. 

It produced this error
```
['C:\\Users\\nn\\Downloads\\Pupil Capture\\pupil_capture.exe']
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
['C:\\Users\\nn\\Downloads\\Pupil Capture\\pupil_capture.exe', '--multiprocessing-fork', 'parent_pid=8512', 'pipe_handle=928']
                                                                                                            Exception in thread Thread-1:
Traceback (most recent call last):
  File "pupil_remote.py", line 199, in thread_loop
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq\backend\cython\socket.c:5327)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:9542)
zmq.error.ZMQError: Address in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\zmq\sugar\socket.py", line 356, in send_multipart
TypeError: memoryview: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "threading.py", line 862, in run
  File "pupil_remote.py", line 202, in thread_loop
  File "site-packages\zmq\sugar\socket.py", line 363, in send_multipart
TypeError: Frame 1 ("Could not bind to Socket: b'tcp...) does not support the buffer interface.

Process world:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 249, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "world.py", line 331, in world
  File "plugin.py", line 225, in __init__
  File "plugin.py", line 255, in add
  File "pupil_remote.py", line 81, in __init__
  File "pupil_remote.py", line 91, in start_server
  File "site-packages\zmq\sugar\socket.py", line 395, in recv_multipart
  File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq\backend\cython\socket.c:7291)
  File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq\backend\cython\socket.c:7089)
  File "zmq/backend/cython/socket.pyx", line 150, in zmq.backend.cython.socket._recv_copy (zmq\backend\cython\socket.c:2134)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq\backend\cython\socket.c:2041)
  File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:9391)
zmq.error.Again: Resource temporarily unavailable
```

**Comment by nnnnicholas** [comment]
Never mind I believe I misunderstood the software.
