### ISSUE TITLE
Double exception on camera calibration look up

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#626]
```
Process world:
Traceback (most recent call last):
  File "/home/papr/work/pupil/pupil_src/shared_modules/calibration_routines/camera_intrinsics_estimation.py", line 86, in load_camera_calibration
    camera_calibration = pre_recorded_calibrations[g_pool.capture.name][g_pool.capture.frame_size]
KeyError: 'Logitech Webcam C930e @ Nexus 6P_NBD91K'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/papr/work/pupil/pupil_src/capture/world.py", line 513, in world
    g_pool.plugins.clean()
  File "/home/papr/work/pupil/pupil_src/shared_modules/plugin.py", line 271, in clean
    if not p.alive:  # reading p.alive will trigger the plug-in cleanup fn.
  File "/home/papr/work/pupil/pupil_src/shared_modules/plugin.py", line 165, in alive
    self.cleanup()
  File "/home/papr/work/pupil/pupil_src/capture/recorder.py", line 381, in cleanup
    self.stop()
  File "/home/papr/work/pupil/pupil_src/capture/recorder.py", line 335, in stop
    camera_calibration = load_camera_calibration(self.g_pool)
  File "/home/papr/work/pupil/pupil_src/shared_modules/calibration_routines/camera_intrinsics_estimation.py", line 88, in load_camera_calibration
    logger.info("Pre recorded calibration for {}@{} not found.".format(g_pool.capture.name,g_pool.capture.frame_size))
  File "/home/papr/work/pupil/pupil_src/shared_modules/video_capture/fake_backend.py", line 114, in frame_size
    return self.img.shape[1],self.img.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

```

Not reproducable 100%

1. Connect a Pupil Mobile camera (in my case: _Logitech Webcam C930e @ Nexus 6P_NBD91K_)
2. Disconnect camera
3. [Maybe optional: Activate Fake Capture] 
4. Start recording
5. Stop recording

**Comment by mkassner** [comment]
stale
