### ISSUE TITLE
KeyError: 'pupil_positions' when loading 0.8.6 recording

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#634]
Hi.  Is Pupil Player v0.9.0.1 backward compatible?

``` text
key,value
System Info,"User: pupil, Platform: Linux, Machine: pupil-desktop, Release: 4.4.0-45-generic, Version: #66~14.04.1-Ubuntu SMP Wed Oct 19 15:05:38 UTC 2016"
World Camera Resolution,1280x720
Start Time,12:16:16
Duration Time,00:07:34
Recording Name,2016_10_26
World Camera Frames,13508
Capture Software Version,v0.8.6
Start Date,26.10.2016
Data Format Version,v0.8.7
```

```
rafael@rafael:~$ pupil_player /home/rafael/recordings/2016_10_26/000
Player [INFO] player_methods : Updating recording from bytes to unicode.
Player [INFO] player_methods : Converted `surface_definitions` from bytes to unicode
Player [INFO] player_methods : Converted `square_marker_cache` from bytes to unicode
Player [INFO] player_methods : Converted `user_calibration_data` from bytes to unicode
Player [INFO] player_methods : Converted `camera_calibration` from bytes to unicode
Player [INFO] player_methods : Converted `surface_definitions.bak` from bytes to unicode
Player [INFO] player_methods : Converted `pupil_data` from bytes to unicode
Player [INFO] player_methods : Converted `square_marker_cache.bak` from bytes to unicode
Player [INFO] player_methods : Updating recording from v0.8.6 format to v0.8.7 format
Player [INFO] __main__ : Application Version: 0.9.0.1
Player [INFO] __main__ : System Info: User: rafael, Platform: Linux, Machine: rafael, Release: 3.16.0-4-amd64, Version: #1 SMP Debian 3.16.39-1 (2016-12-30)
Traceback (most recent call last):
  File "main.py", line 627, in <module>
  File "main.py", line 242, in session
KeyError: 'pupil_positions'
Failed to execute script main
rafael@rafael:~$
```

**Comment by cpicanco** [comment]
``` bash
rafael@rafael:~$ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
``` python
import os
import pickle 

file_path = os.path.expanduser('/home/rafael/recordings/2016_10_26/000/pupil_data')
data = pickle.load(open(file_path, 'rb') , encoding='bytes')
print(type(data))

for key, value in data.items():
    print(key,':',type(value))
```

Hi, the previous code returns the following:

```
<class 'dict'>
b'pupil_positions' : <class 'list'>
b'notifications' : <class 'list'>
b'gaze_positions' : <class 'list'>
[Finished in 5.4s]
```

Seems ok.

Maybe there is a problem with the `update_recording_bytes_to_unicode` function:

https://github.com/pupil-labs/pupil/blob/v0.9.0/pupil_src/player/player_methods.py#L216

**Comment by mkassner** [comment]
Hi,

please edit the info file and downgrade your data_format_version manually to v0.8.6.

If should work then if you open your recording in pupil player. Our suspicion is that you had updated your recording using a version from master at a time when we did not properly convert the pupil_data file.

**Comment by cpicanco** [comment]
Thank you for the update. Will check the issue tomorow.

**Comment by cpicanco** [comment]
Error persists.
```
pupil@pupil-desktop:~$ pupil_player /home/pupil/recordings/2017_02_06/001 
Player [INFO] plugin : Added: <class 'display_recent_gaze_patch.Display_Recent_Gaze'>
Player [INFO] player_methods : Updating recording from bytes to unicode.
Player [INFO] player_methods : Converted `camera_calibration` from bytes to unicode
Player [INFO] player_methods : Converted `pupil_data` from bytes to unicode
Player [INFO] player_methods : Converted `surface_definitions` from bytes to unicode
Player [INFO] player_methods : Converted `user_calibration_data` from bytes to unicode
Player [INFO] player_methods : Converted `square_marker_cache` from bytes to unicode
Player [INFO] player_methods : Updating recording from v0.8.6 format to v0.8.7 format
Player [INFO] __main__ : Application Version: 0.9.0.17
Player [INFO] __main__ : System Info: User: pupil, Platform: Linux, Machine: pupil-desktop, Release: 4.8.0-36-generic, Version: #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017
Traceback (most recent call last):
  File "main.py", line 627, in <module>
  File "main.py", line 242, in session
KeyError: 'pupil_positions'
Failed to execute script main
pupil@pupil-desktop:~$
```

**Comment by cpicanco** [comment]
Fresh install, Ubuntu 16.04.

**Comment by mkassner** [comment]
Please change your .cvs file like below and try again:


```csv
key,value
System Info,"User: pupil, Platform: Linux, Machine: pupil-desktop, Release: 4.4.0-45-generic, Version: #66~14.04.1-Ubuntu SMP Wed Oct 19 15:05:38 UTC 2016"
World Camera Resolution,1280x720
Start Time,12:16:16
Duration Time,00:07:34
Recording Name,2016_10_26
World Camera Frames,13508
Capture Software Version,v0.8.6
Start Date,26.10.2016
Data Format Version,v0.8.6
```

**Comment by cpicanco** [comment]
Sorry, but It does not work.

**Comment by cpicanco** [comment]
@mkassner, is it related to keys encoding?

``` python
import os
import pickle 

file_path = os.path.expanduser('/home/rafael/recordings/2016_10_26/000/pupil_data')
data = pickle.load(open(file_path, 'rb') , encoding='bytes')
print(type(data))

for key, value in data.items():
   print(key.decode('utf-8'),':',type(value))

# output
# <class 'dict'>
# notifications : <class 'list'>
# pupil_positions : <class 'list'>
# gaze_positions : <class 'list'>
# [Finished in 5.1s]
```

**Comment by papr** [comment]
@cpicanco Please use 
> `print(repr(key.decode('utf-8')), ':', type(value))`

**Comment by cpicanco** [comment]
The out was, without the `b` (byte) letter:

``` text
<class 'dict'>
'notifications' : <class 'list'>
'gaze_positions' : <class 'list'>
'pupil_positions' : <class 'list'>
[Finished in 5.2s]
```

**Comment by papr** [comment]
Ah, yeah of course, because you convert the key (`bytes`) to `unicode` with `.decode('utf-8')`. So for some reason, the `pupil_data` file is not getting updated.

But your log of the new version says `Player [INFO] player_methods : Converted `pupil_data` from bytes to unicode`. So it is getting updated.

Therefore the unicode update method is broken for some reason.

**Comment by mkassner** [comment]
@cpicanco  could you upload this recording so we can test?

**Comment by cpicanco** [comment]
The videos are very big (~3gb). Please, confirm if you need all the files.

On Feb 28, 2017 04:32, "mkassner" <notifications@github.com> wrote:

@cpicanco <https://github.com/cpicanco> could you upload this recording so
we can test?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pupil-labs/pupil/issues/634#issuecomment-282964387>,
or mute
the thread

**Comment by mkassner** [comment]
Hi,

no you can leave the video files out.

**Comment by mkassner** [comment]
using the data provided by @fneitzel  I fixed the issue. The latest version is master has this commit. 

We will release a bundle in a bit!

Please edit your info.csv file and remove the data_format line. This will trigger a conversion.
