### ISSUE TITLE
on start error on ubuntu

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#638]
```
pupil@pupil-desktop:~$ pupil_capture 
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
Process world:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "world.py", line 86, in world
  File "/home/pupil-labs/.pyenv/versions/3.6.0/envs/general/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "methods.py", line 19, in <module>
  File "/home/pupil-labs/.pyenv/versions/3.6.0/envs/general/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: librtmp.so.0: cannot open shared object file: No such file or directory
```

**Comment by cpicanco** [comment]
Also `ctrl+c` possibly interrumps some background process.

```
c^CTraceback (most recent call last):
  File "main.py", line 254, in <module>
  File "main.py", line 225, in launcher
  File "zmq_tools.py", line 84, in recv
  File "zmq/sugar/socket.py", line 457, in recv_string
  File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7683)
  File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7460)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2344)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9621)
KeyboardInterrupt
Failed to execute script main
```

**Comment by mkassner** [comment]
Could you post the output of 

```
 ls /usr/lib/x86_64-linux-gnu/librtmp*
```
and 
```
uname -a
```

After doing this could you please do 

```
sudo apt install librtmp0
```

and try again?

**Comment by cpicanco** [comment]
Some information:

I have upgraded from 14.04 to 16.04 recently. Also I was running the bundle. I guess I need a fresh install. Somehow the system is broken.
```
pupil@pupil-desktop:~$  ls /usr/lib/x86_64-linux-gnu/librtmp*
/usr/lib/x86_64-linux-gnu/librtmp.a   /usr/lib/x86_64-linux-gnu/librtmp.so.1
/usr/lib/x86_64-linux-gnu/librtmp.so

pupil@pupil-desktop:~$ uname -a
Linux pupil-desktop 4.4.0-63-generic #84-Ubuntu SMP Wed Feb 1 17:20:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

pupil@pupil-desktop:~$ sudo apt install librtmp0
[sudo] password for pupil: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package librtmp0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

N: Ignoring file '50unattended-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
E: Package 'librtmp0' has no installation candidate
```

**Comment by mkassner** [comment]
Yes it does sound like something is broken on your system ...

**Comment by cpicanco** [comment]
I should note that 0.8.7 is working fine, maybe not so broken.

**Comment by cpicanco** [comment]
I will fresh install and test again, if necessary I will reopen this issue.

**Comment by cpicanco** [comment]
And it wooooooorks! hahahahahaahahahaha
![screenshot from 2017-02-21 13-43-17](https://cloud.githubusercontent.com/assets/6511849/23174705/f93aa596-f83b-11e6-9750-df50d75056d5.png)

**Comment by cpicanco** [comment]
@mkassner  should `librtmp.so` be included here ---> https://github.com/pupil-labs/pupil/commit/904504e8cc53f2fd242b8426c17094fbe8c801c1#diff-7a227140d534814837d549186d81112e
