### ISSUE TITLE
KeyError: 'camera_name' when stopping calibration or recording

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#639]
```
Stopping Calibration
world - [INFO] calibration_routines.screen_marker_calibration: Stopping Calibration
Process world:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "world.py", line 453, in world
  File "calibration_routines/screen_marker_calibration.py", line 286, in recent_events
  File "calibration_routines/screen_marker_calibration.py", line 225, in stop
  File "calibration_routines/finish_calibration.py", line 39, in finish_calibration
  File "calibration_routines/camera_intrinsics_estimation.py", line 75, in load_camera_calibration
KeyError: 'camera_name'
eye0 - [ERROR] uvc: Can't stop stream: Error:'Operation timed out.'. Will ignore this and try to continue.
eye0 - [INFO] eye: Process shutting down.
```
**Work Around**

Deleting old `camera_calibration` files from the `pupil_capture_settings` folder.

**Comment by cpicanco** [comment]
`v0.9`
