### ISSUE TITLE
opencv error: (-215) depth == CV_32F || depth == CV_64F

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#645]
Please ignore if not a bug in pupil capture.

Sometimes this pupil capture bug happens when looking into a surface made from a single marker. 

So `recent_events` in the runtime `screen_tracker.py` plugin is just a copy of `update` in `surface_tracker.py` except for the marker detector method .

``` python
if 'frame' in events:
    frame = events['frame']
    self.img_shape = frame.height,frame.width,3

    if self.running:
        gray = frame.gray
        # instead "self.screens"
        # hack "self.markers" is keep for inheritance compatibility
        self.markers = detect_screens(gray)

        if self.mode == "Show marker IDs":
            draw_markers(frame.img,self.markers)
            events['frame'] = frame

    # locate surfaces, map gaze
    for s in self.surfaces:
        s.locate(self.markers,self.camera_calibration,self.min_marker_perimeter,self.min_id_confidence, self.locate_3d)
        if s.detected:
            # Line 102 >>>>>>>>>>>>>>>>>>>>>>>
            s.gaze_on_srf = s.map_data_to_surface(events.get('gaze_positions',[]),s.m_from_screen)
        else:
            s.gaze_on_srf =[]
```
```
Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "world.py", line 453, in world
  File "/home/pupil/pupil_capture_settings/plugins/screen_tracker.py", line 102, in recent_events
    s.gaze_on_srf = s.map_data_to_surface(events.get('gaze_positions',[]),s.m_from_screen)
  File "reference_surface.py", line 423, in map_data_to_surface
  File "reference_surface.py", line 423, in <listcomp>
  File "reference_surface.py", line 417, in map_datum_to_surface
cv2.error: /home/pupil/git/opencv/modules/core/src/matmul.cpp:2272: error: (-215) depth == CV_32F || depth == CV_64F in function perspectiveTransform
```

> reference_surface.py is up to date e1ecc497e4260e45dcd9c4ee7a133a9da40508b6 
``` python
    @staticmethod
    def map_datum_to_surface(d,m_from_screen):
        pos = np.array([d['norm_pos']]).reshape(1,1,2)
        mapped_pos = cv2.perspectiveTransform(pos , m_from_screen ) #LINE 417 <<<<<<<<<<<<<<<
        mapped_pos.shape = (2)
        on_srf = bool((0 <= mapped_pos[0] <= 1) and (0 <= mapped_pos[1] <= 1))
        return {'topic':d['topic']+"_on_surface",'norm_pos':(mapped_pos[0],mapped_pos[1]),'confidence':d['confidence'],'on_srf':on_srf,'base_data':d }

    def map_data_to_surface(self,data,m_from_screen):
        return [self.map_datum_to_surface(d,m_from_screen) for d in data]

``` 
Maybe is something like this: http://answers.opencv.org/question/252/cv2perspectivetransform-with-python/

**Comment by florianbussmann** [comment]
This seems like the same issue I was experiencing earlier today. Unfortunately the fix from @papr did not help in my case.. https://github.com/pupil-labs/pupil/issues/598
I also found the same solution on opencv.org but it didn't help either..

**Comment by papr** [comment]
This is a duplicate. Closing this in favor of #598
