### ISSUE TITLE
Division by zero during Calibration

### ISSUE THREAD

**Issue by florianbussmann** [pupil-labs/pupil#647]
When running on Windows the screen marker calibration exits occassionally with a ZeroDivisionError. As of now I have no idea what causes this..

```
Traceback (most recent call last):
  File "C:\dev\tools\Python\Python35\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\dev\tools\Python\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "J:\source\eyetracking\dev\trunk\pupil\pupil_src\capture\world.py", line 486, in world
    p.gl_display()
  File "J:\source\eyetracking\dev\trunk\pupil\pupil_src\shared_modules\calibration_routines\screen_marker_calibration.py", line 317, in gl_display
    self.gl_display_in_window()
  File "J:\source\eyetracking\dev\trunk\pupil\pupil_src\shared_modules\calibration_routines\screen_marker_calibration.py", line 330, in gl_display_in_window
    hdpi_factor = glfwGetFramebufferSize(self._window)[0]/glfwGetWindowSize(self._window)[0]
ZeroDivisionError: division by zero
```

**Comment by mkassner** [comment]
Please let us know the OS/Version.

**Comment by mkassner** [comment]
closed because issue is stale
