### ISSUE TITLE
3d screen marker calibration crash

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#694]
```
pupil@pupil-desktop:~$ pupil_capture 
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] world: Application Version: 0.9.4.2
world - [INFO] world: System Info: User: pupil, Platform: Linux, Machine: pupil-desktop, Release: 4.8.0-46-generic, Version: #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017
Estimated / selected altsetting bandwith : 1351 / 1600. 
Estimated / selected altsetting bandwith : 1351 / 1600. 
eye0 - [WARNING] uvc: Could not set Value. 'Absolute Exposure Time'.
eye0 - [WARNING] uvc: Could not set Value. 'White Balance temperature'.
eye0 - [WARNING] eye: Process started.
Estimated / selected altsetting bandwith : 1754 / 2400. 
Ceres Solver Report: Iterations: 3, Initial cost: 4.594733e-01, Final cost: 4.182508e-01, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 3.753599e-01, Final cost: 3.334178e-01, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 3.069747e-01, Final cost: 2.643217e-01, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.512407e-01, Final cost: 2.078043e-01, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.058960e-01, Final cost: 1.615873e-01, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 1.691895e-01, Final cost: 1.239256e-01, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 1.397213e-01, Final cost: 9.343314e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 1.163496e-01, Final cost: 6.898351e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 9.813014e-02, Final cost: 4.964698e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 8.427467e-02, Final cost: 3.464823e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 7.412101e-02, Final cost: 2.333604e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 6.711013e-02, Final cost: 1.516053e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 6.276841e-02, Final cost: 9.655563e-03, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 6.069348e-02, Final cost: 6.424816e-03, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 6.054270e-02, Final cost: 5.130481e-03, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 6.202379e-02, Final cost: 5.484035e-03, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 6.488695e-02, Final cost: 7.238623e-03, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 6.891843e-02, Final cost: 1.018269e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 7.393507e-02, Final cost: 1.413469e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 6.054270e-02, Final cost: 5.130481e-03, Termination: CONVERGENCE
Process world:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "world.py", line 461, in world
  File "calibration_routines/screen_marker_calibration.py", line 286, in recent_events
  File "calibration_routines/screen_marker_calibration.py", line 225, in stop
  File "calibration_routines/finish_calibration.py", line 285, in finish_calibration
  File "plugin.py", line 158, in notify_all
  File "zmq_tools.py", line 159, in notify
  File "zmq_tools.py", line 124, in send
  File "msgpack/__init__.py", line 47, in packb
  File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)
  File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 228, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3382)
TypeError: can't serialize array([[-0.11546495,  0.31202974,  0.00475829,  0.01769476, -0.29852791]])

# ctrl + c
^C

Traceback (most recent call last):
  File "main.py", line 255, in <module>
  File "main.py", line 226, in launcher
  File "zmq_tools.py", line 84, in recv
  File "zmq/sugar/socket.py", line 457, in recv_string
  File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7683)
  File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7460)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2344)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9621)
KeyboardInterrupt
Failed to execute script main
Process eye0:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "eye.py", line 478, in eye
  File "video_capture/uvc_backend.py", line 192, in recent_events
KeyboardInterrupt
pupil@pupil-desktop:~$ 
```

**Comment by cpicanco** [comment]
@papr , maybe related to  0aad51f

**Comment by papr** [comment]
Yes, this is generally related to the change to msgpack. Can you reproduce this error consistently with the Natural Feature Calibration?

**Comment by cpicanco** [comment]
Yes I can.

**Comment by cpicanco** [comment]
```
pupil@pupil-desktop:~$ pupil_capture 
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] world: Application Version: 0.9.4.2
world - [INFO] world: System Info: User: pupil, Platform: Linux, Machine: pupil-desktop, Release: 4.8.0-46-generic, Version: #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017
Estimated / selected altsetting bandwith : 1351 / 1600. 
Estimated / selected altsetting bandwith : 1351 / 1600. 
eye0 - [WARNING] uvc: Could not set Value. 'Absolute Exposure Time'.
eye0 - [WARNING] uvc: Could not set Value. 'White Balance temperature'.
eye0 - [WARNING] eye: Process started.
Estimated / selected altsetting bandwith : 1754 / 2400. 
Ceres Solver Report: Iterations: 3, Initial cost: 2.566373e-01, Final cost: 3.636871e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 16, Initial cost: 6.023726e+01, Final cost: 9.821638e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 4, Initial cost: 7.427804e-01, Final cost: 8.810017e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 3.758593e-01, Final cost: 4.782701e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 3.187543e-01, Final cost: 4.121774e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.913995e-01, Final cost: 3.779018e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.735871e-01, Final cost: 3.536905e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.603170e-01, Final cost: 3.342240e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.496765e-01, Final cost: 3.175064e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.407641e-01, Final cost: 3.026092e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.330917e-01, Final cost: 2.890420e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.263666e-01, Final cost: 2.765228e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.204125e-01, Final cost: 2.648781e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.151003e-01, Final cost: 2.539946e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.103483e-01, Final cost: 2.437932e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.060910e-01, Final cost: 2.342154e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 2.022757e-01, Final cost: 2.252151e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 1.988674e-01, Final cost: 2.167535e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 1.958220e-01, Final cost: 2.087970e-02, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 3, Initial cost: 1.958220e-01, Final cost: 2.087970e-02, Termination: CONVERGENCE
Process world:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "world.py", line 451, in world
  File "calibration_routines/calibration_plugin_base.py", line 49, in on_notify
  File "calibration_routines/natural_features_calibration.py", line 87, in stop
  File "calibration_routines/finish_calibration.py", line 285, in finish_calibration
  File "plugin.py", line 158, in notify_all
  File "zmq_tools.py", line 159, in notify
  File "zmq_tools.py", line 124, in send
  File "msgpack/__init__.py", line 47, in packb
  File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)
  File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 228, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3382)
TypeError: can't serialize array([[-0.11546495,  0.31202974,  0.00475829,  0.01769476, -0.29852791]])
^CTraceback (most recent call last):
  File "main.py", line 255, in <module>
  File "main.py", line 226, in launcher
  File "zmq_tools.py", line 84, in recv
  File "zmq/sugar/socket.py", line 457, in recv_string
  File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7683)
  File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7460)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2344)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9621)
KeyboardInterrupt
Failed to execute script main
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "multiprocessing/popen_fork.py", line 29, in poll
KeyboardInterrupt
Process eye0:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "eye.py", line 478, in eye
  File "video_capture/uvc_backend.py", line 192, in recent_events
KeyboardInterrupt
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "multiprocessing/util.py", line 186, in __call__
  File "multiprocessing/heap.py", line 208, in free
TypeError: 'NoneType' object is not callable
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "multiprocessing/util.py", line 186, in __call__
  File "multiprocessing/heap.py", line 208, in free
TypeError: 'NoneType' object is not callable
pupil@pupil-desktop:~$ 
```

**Comment by papr** [comment]
Does it crash immediately after calibration or when you close Capture?

**Comment by cpicanco** [comment]
Immediately after finishing calibration.

**Comment by papr** [comment]
I see. It will be fixed by Monday.

**Comment by mkassner** [comment]
Hi @cpicanco  you will need to recalibrate your camera. After that it will work. We will add a guard against old calibrations.
