### ISSUE TITLE
Run from source code on macOS

### ISSUE THREAD

**Issue by uncflorians** [pupil-labs/pupil#698]
If I try to run pupil from source ( by python3 main.py) I get this error:

**'invalid command name 'SSHD/florian/pupil_labs/pupil/pupil_src/shared_modules'**

The issue seems to be a space in the original path:
**'/Volumes/Macintosh SSHD/florian/pupil_labs/pupil/pupil_src/player/'**
If I would remove the space in the volume name permanently, it works, but this is no option.

It seems like **_os.path.abspath(__file__)_** can handle spaces in paths but  **_sys.path.append(os.path.join(pupil_base_dir, 'pupil_src', 'shared_modules'))_** 
seems to have trouble in interpreting a path with spaces.

I know spaces are generally a bad idea when naming folders etc. but is there a way to make this aspect of code more robust?

Here is the full error from terminal after **python3 main.py**

invalid command name 'SSHD/florianschertenleib/pupil_labs/pupil/pupil_src/shared_modules'
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    from offline_surface_tracker import Offline_Surface_Tracker
  File "/Volumes/Macintosh SSHD/florianschertenleib/pupil_labs/pupil/pupil_src/shared_modules/offline_surface_tracker.py", line 36, in <module>
    from surface_tracker import Surface_Tracker
  File "/Volumes/Macintosh SSHD/florianschertenleib/pupil_labs/pupil/pupil_src/shared_modules/surface_tracker.py", line 28, in <module>
    from calibration_routines.camera_intrinsics_estimation import load_camera_calibration
  File "/Volumes/Macintosh SSHD/florianschertenleib/pupil_labs/pupil/pupil_src/shared_modules/calibration_routines/__init__.py", line 14, in <module>
    from . screen_marker_calibration import Screen_Marker_Calibration
  File "/Volumes/Macintosh SSHD/florianschertenleib/pupil_labs/pupil/pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py", line 30, in <module>
    from . finish_calibration import finish_calibration
  File "/Volumes/Macintosh SSHD/florianschertenleib/pupil_labs/pupil/pupil_src/shared_modules/calibration_routines/finish_calibration.py", line 20, in <module>
    from . optimization_calibration import bundle_adjust_calibration
  File "/Volumes/Macintosh SSHD/florianschertenleib/pupil_labs/pupil/pupil_src/shared_modules/calibration_routines/optimization_calibration/__init__.py", line 17, in <module>
    build_cpp_extension()
  File "/Volumes/Macintosh SSHD/florianschertenleib/pupil_labs/pupil/pupil_src/shared_modules/calibration_routines/optimization_calibration/build.py", line 26, in build_cpp_extension
    ret = sp.check_output(build_cmd.format(sys.executable, install_loc), shell=True).decode(sys.stdout.encoding)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/usr/local/opt/python3/bin/python3.6 setup.py install --install-lib=/Volumes/Macintosh SSHD/florianschertenleib/pupil_labs/pupil/pupil_src/shared_modules' returned non-zero exit status 1.

**Comment by uncflorians** [comment]
I cloned pupil now to /Applications. That works.

**Comment by uncflorians** [comment]
I cloned pupil now to /Applications. That works.
