### ISSUE TITLE
Unable to define offline surfaces in player v0.9.6

### ISSUE THREAD

**Issue by ignacioxd** [pupil-labs/pupil#718]
I have several recordings with 4 surface markers shown on screen corners.  Pupil Player 0.9.6 hangs on both Windows 10 and MacOS when I click "Add surface" on the offline surface tracker plugin. The error shown on the Windows console output is

```
Traceback (most recent call last):
  File "main.py", line 645, in <module>
  File "main.py", line 502, in session
  File "offline_surface_tracker.py", line 239, in recent_events
  File "offline_surface_tracker.py", line 198, in build_correspondance
  File "offline_surface_tracker.py", line 215, in finalize_correspondance
AttributeError: 'Offline_Reference_Surface' object has no attribute 'on_finish_define'
Failed to execute script main
```

All 4 markers are correctly highlighted by the plugin before I attempt to add the surface. There are no other surfaces defined.

**Comment by mkassner** [comment]
Thanks for the bug report. I just fixed this. If you run the current master from source it will work now. Otherwise please wait until tomorrows release of Pupil Player and Capture.
