### ISSUE TITLE
clean shut-down of Pupil time sync

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#731]
The plugin leaves a socket open thats not closed nicely. Please fix this.

**Comment by mkassner** [comment]
trace:
```
Exception ignored in: <bound method Time_Echo_Server.__del__ of <network_time_sync.Time_Echo_Server :0 at 0x1169e2e48>>
Traceback (most recent call last):
  File "/Users/mkassner/Pupil/pupil_code/pupil_src/shared_modules/network_time_sync.py", line 82, in __del__
    logger.debug("Server closed")
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1289, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1437, in _log
    self.handle(record)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1447, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1509, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 858, in handle
    self.emit(record)
  File "/Users/mkassner/Pupil/pupil_code/pupil_src/shared_modules/zmq_tools.py", line 37, in emit
    record.__dict__)
  File "/Users/mkassner/Pupil/pupil_code/pupil_src/shared_modules/zmq_tools.py", line 123, in send
    self.socket.send_string(topic, flags=zmq.SNDMORE)
  File "/Users/mkassner/Envs/py3/lib/python3.6/site-packages/zmq/sugar/socket.py", line 438, in send_string
    return self.send(u.encode(encoding), flags=flags, copy=copy)
  File "zmq/backend/cython/socket.pyx", line 636, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:7314)
  File "zmq/backend/cython/socket.pyx", line 683, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:7057)
  File "zmq/backend/cython/socket.pyx", line 206, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:3041)
  File "zmq/backend/cython/socket.pyx", line 201, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2929)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:10099)
zmq.error.ZMQError: Socket operation on non-socket
```

**Comment by papr** [comment]
So as @mkassner mentioned in a direct conversation this issue occurs on shutdown of Pupil Capture. This makes sense since the IPC will be shutdown when closing Pupil Capture and sending something to the IPC (in this case a logging message) will fail.

The reason why this logging message is send after the IPC shutdown (usually all plugins are cleaned up beforehand) is that the `Time_Echo_Server` instance is being garbage collected _after_ the IPC shutdown. There is no guaranteed way to force the object to be garbage collected earlier.

In my experience setting the references to the object instance in question to `None` triggers an earlier call of the `__del__` method. Therefore I would suggest the following fix:

```diff
@@ -261,3 +260,6 @@ class Time_Sync(Plugin):
         self.master_service.stop()
         if self.follower_service:
             self.follower_service.stop()
+        self.master_service = None
+        self.follower_service = None
+        self.discovery = None
```

**Comment by papr** [comment]
You can merge https://github.com/papr/pupil/tree/fix731 if you agree with the above proposal.
