### ISSUE TITLE
Windows developer setup: Error building pupil_detector_3d 

### ISSUE THREAD

**Issue by et939651** [pupil-labs/pupil#754]
Dear all, 

I follow this [instructions](https://docs.pupil-labs.com/master/#windows-dependencies) for Window 10 64 bit systems. I have already installed all Windows dependencies as documents mentions. After modifying setup.py, I start to run run_capture.bat. However, an error message shows up as follows:

C:\Users\ycchang\Desktop\pupil\pupil\pupil_src\capture>python main.py
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] world: Application Version: 0.9.12.17
world - [INFO] world: System Info: User: ycchang, Platform: Windows, Machine: uc2214, Release: 10, Version: 10.0.14393
world - [INFO] pupil_detectors.build: Building extention modules...
Process world:
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ycchang\Desktop\pupil\pupil\pupil_src\capture\world.py", line 94, in world
    import pupil_detectors
  File "C:\Users\ycchang\Desktop\pupil\pupil\pupil_src\capture\pupil_detectors\__init__.py", line 19, in <module>
    from .detector_3d import Detector_3D
ImportError: DLL load failed: %1 is not a valid Win32 application.

Is there any suggestions to fix this issue? 

Thank you

**Comment by et939651** [comment]
I have replaced numpy‑1.13.0 with numpy‑1.13.0+mlk and it seems that this error solves. However, the new error message shows up:

error: command 'cl.exe' failed: No such file or directory
Process world:
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ycchang\Desktop\pupil\pupil\pupil_src\capture\world.py", line 94, in world
    import pupil_detectors
  File "C:\Users\ycchang\Desktop\pupil\pupil\pupil_src\capture\pupil_detectors\__init__.py", line 16, in <module>
    build_cpp_extension()
  File "C:\Users\ycchang\Desktop\pupil\pupil\pupil_src\capture\pupil_detectors\build.py", line 25, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "C:\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Python36\\python.exe', 'setup.py', 'install', '--install-lib=C:\\Users\\ycchang\\Desktop\\pupil\\pupil\\pupil_src\\capture']' returned non-zero exit status 1.

**Comment by willpatera** [comment]
@et939651 The error message shows that you are not able to build the pupil detector. You need the latest version of the Numpy wheel available from [Gohlke's site](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy)

Some questions:

1. Are you using Windows 10 64 bit?
1. Are you using MSVS 2017 Preview? 
1. Are you using `x64 Native Tools Command Prompt for VS 2017 Preview` with admin privileges?  :point_left: this would seem to be the issue based on your second error message.
1. Did you install [MSVC++ 2010 runtime](https://www.microsoft.com/en-us/download/details.aspx?id=14632)?

For debugging please cd to the `pupil_detectors` dir and run `python setup.py build` to get more feedback in the build process.

**Comment by et939651** [comment]
Dear willpatera, 

1. Yes, my  system is Window 10 64 bit
2. Yes, I download Virtual Studio Preview 2017 as pupil lab instruction
3. Yes, I use x64 Native Tools Command Prompt. I think that I might not use admin privileges, I will double check that. 
4. Yes. 

I will check the admin again! Thank you for your reply!
