### ISSUE TITLE
Crash on changing capture resolution while tracking a surface

### ISSUE THREAD

**Issue by gendelo3** [pupil-labs/pupil#760]
When i try to change the resolution under "Sensor Settings", the main window of Pupil Capture crashes when i do the following:  

- The surface tracker is activated and my surface is visible and detected (my surface is defined by 6 markers)  
- I try to change the resolution to any other resolution  

Then pupil captures main window crashes.  

I am using pupil capture 0.9.12.2 on Ubuntu 16.04.  
Sorry if this has been mentioned before, i didn't find a related issue.

**Comment by papr** [comment]
I was able to reproduce this error with following traceback:
```
OpenCV Error: Assertion failed (prevPyr[level * lvlStep1].size() == nextPyr[level * lvlStep2].size()) in calc, file /tmp/opencv3-20170704-80534-s1idzt/opencv-3.2.0/modules/video/src/lkpyramid.cpp, line 1365
Process world:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/pabloprietz/work/pupil/pupil_src/launchables/world.py", line 472, in world
    p.recent_events(events)
  File "/Users/pabloprietz/work/pupil/pupil_src/shared_modules/surface_tracker.py", line 210, in recent_events
    min_marker_perimeter=self.min_marker_perimeter)
  File "/Users/pabloprietz/work/pupil/pupil_src/shared_modules/square_marker_detect.py", line 329, in detect_markers_robust
    minEigThreshold=.01,**lk_params)
cv2.error: /tmp/opencv3-20170704-80534-s1idzt/opencv-3.2.0/modules/video/src/lkpyramid.cpp:1365: error: (-215) prevPyr[level * lvlStep1].size() == nextPyr[level * lvlStep2].size() in function calc
```
