### ISSUE TITLE
Cannot open my records from about a month ago

### ISSUE THREAD

**Issue by anshvarts** [pupil-labs/pupil#766]
Hi! I tried to come back to my records that were made in May and suddenly PupilPlayer collapses (both, the app and from the source). Could you help me, please?

Here is the log:
Deprecation warning: Please update your homebrew glfw installation by running `brew migrate glfw`
Player [WARNING] __main__ : You did not supply a data directory when you called this script!
Player [ERROR] player_methods : No valid dir supplied
Player [INFO] __main__ : Starting new session with '/Users/AShvarts/recordings/area/Гриша/Adult_2017_05_25_Grisha_Anya/Grisha_adult_area1'
Player [INFO] player_methods : Updating meta info
Player [INFO] player_methods : Updating meta info
Player [INFO] __main__ : Application Version: 0.9.12.2
Player [INFO] __main__ : System Info: User: AShvarts, Platform: Darwin, Machine: Annas-MacBook-Air-3.local, Release: 15.6.0, Version: Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64
Traceback (most recent call last):
  File "main.py", line 649, in <module>
    session(this_session_dir)
  File "main.py", line 230, in session
    cap = File_Source(g_pool, video_path, timestamps=list(timestamps))
  File "/Users/AShvarts/Documents/GitHub/pupil/pupil_src/shared_modules/video_capture/file_backend.py", line 107, in __init__
    self.container = av.open(str(source_path))
  File "av/container/core.pyx", line 288, in av.container.core.open (src/av/container/core.c:4991)
  File "av/container/core.pyx", line 254, in av.container.core.Container.__cinit__ (src/av/container/core.c:4406)
  File "av/container/core.pyx", line 108, in av.container.core.ContainerProxy.__init__ (src/av/container/core.c:3024)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 32-36: ordinal not in range(128)

**Comment by anshvarts** [comment]
A-a-a-a! Now the same has happened with the record that I was analysing yesterday.... Is it something wrong with my computer?

**Comment by mkassner** [comment]
please check that your recording is not in a path with non-ascii characters.

**Comment by anshvarts** [comment]
O, yesss! Thank you so much)
