### ISSUE TITLE
Cannot open Pupil Capture after new release...

### ISSUE THREAD

**Issue by johnspenceruea** [pupil-labs/pupil#775]
I saw one issue with the new release and I'm having the same problem. I ran pupil capture from the terminal window as requested. Here is the output:

/Applications/Pupil\ Capture.app/Contents/MacOS/pupil_capture
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
Process world:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "launchables/world.py", line 86, in world
  File "/Users/mkassner/Envs/py3/lib/python3.6/site-packages/PyInstaller-3.3.dev0+g89dc7eb-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "shared_modules/methods.py", line 19, in <module>
  File "/Users/mkassner/Envs/py3/lib/python3.6/site-packages/PyInstaller-3.3.dev0+g89dc7eb-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: dlopen(/Applications/Pupil Capture.app/Contents/MacOS/cv2.so, 2): Library not loaded: @loader_path/libtbb.dylib
  Referenced from: /Applications/Pupil Capture.app/Contents/MacOS/libopencv_reg.3.2.dylib
  Reason: image not found

Any help would be appreciated!

**Comment by papr** [comment]
This has been fixed. Please download and install the newest release.
