### ISSUE TITLE
Pupil Mobile export doesn't work [Pupil Player]?

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#790]
Hi Pupil Team,

the last enhancements are super exciting!

Offline Pupil Detector is working.
Offline Calibration is working,

info.csv
```
key,value
Recording Name,local_recording/20170810171052040
Start Date,10:08:2017
Start Time,17:10:52
System Info,Nexus 6P_N2G47H
Duration Time,00:01:19
Capture Software,Pupil Mobile
Capture Software Version,0.13.0
Data Format Version,v0.9.13
```
terminal log
```
pupil_player '/home/user/Desktop/20170810171052040' 
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [INFO] launchables.player: Starting new session with '/home/user/Desktop/20170810171052040'
player - [INFO] player_methods: Updating meta info
player - [INFO] launchables.player: Application Version: 0.9.13.42
player - [INFO] launchables.player: System Info: User: neitzel, Platform: Linux, Machine: boole, Release: 4.10.0-30-generic, Version: #34~16.04.1-Ubuntu SMP Wed Aug 2 02:13:56 UTC 2017
player - [INFO] plugin: Loaded: Trim_Marks
player - [INFO] plugin: Loaded: Seek_Bar
player - [INFO] plugin: Loaded: Offline_Pupil_Detection
player - [INFO] gaze_producers: Calibrating "1" in 3d mode...
player - [INFO] plugin: Loaded: Offline_Calibration
player - [INFO] plugin: Loaded: Log_Display
player - [INFO] plugin: Loaded: Video_Export_Launcher
player - [INFO] plugin: Loaded: Vis_Scan_Path
player - [INFO] plugin: Loaded: Vis_Polyline
player - [INFO] plugin: Loaded: Vis_Circle
Ceres Solver Report: Iterations: 46, Initial cost: 5.993424e+00, Final cost: 7.343658e-01, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 59, Initial cost: 5.950332e+00, Final cost: 6.986526e-01, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 63, Initial cost: 5.967182e+00, Final cost: 6.846480e-01, Termination: CONVERGENCE
Ceres Solver Report: Iterations: 65, Initial cost: 6.027340e+00, Final cost: 6.867817e-01, Termination: CONVERGENCE

**[...]**

Ceres Solver Report: Iterations: 66, Initial cost: 9.331917e+00, Final cost: 1.596206e+00, Termination: CONVERGENCE
Reflection detected
Ceres Solver Report: Iterations: 61, Initial cost: 6.960924e+00, Final cost: 1.083770e+00, Termination: CONVERGENCE
player - [WARNING] launchables.player: Previous export for range [0-2188] already exsits - overwriting.
player - [WARNING] video_export_launcher: Adding new video export process.
player - [WARNING] video_export_launcher: adding export
Process Export_Process-2:5:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "shared_modules/exporter.py", line 70, in export
IndexError: list index out of range
player - [INFO] launchables.player: Created export dir at "/home/neitzel/Desktop/20170810171052040/exports/0-2180"
player - [WARNING] video_export_launcher: Adding new video export process.
player - [WARNING] video_export_launcher: adding export
Process Export_Process-2:6:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "shared_modules/exporter.py", line 70, in export
IndexError: list index out of range
```

Video files will be provided.

Best Regards

**Comment by mkassner** [comment]
Fixed in master. Thank you for spotting that. If you record the world with h264 compression it will work in the current bundle as well. (or just transcode world.mjpeg to mp4 using ffmpeg)
