### ISSUE TITLE
Eye process crashing

### ISSUE THREAD

**Issue by Tobias-Fischer** [pupil-labs/pupil#802]
Hi,
recently I quite frequently encounter this issue:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tobias/robot/pupil/pupil/pupil_src/launchables/eye.py", line 531, in eye
    clear_gl_screen()
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/gl_utils/utils.py", line 67, in clear_gl_screen
    glClear(GL_COLOR_BUFFER_BIT)
  File "/usr/local/lib/python3.5/dist-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'invalid value',
	baseOperation = glClear,
	cArguments = (GL_COLOR_BUFFER_BIT,)
```

Do you have any idea what the issue could be? Can I help debugging this somehow?

Thanks, Tobias

**Comment by papr** [comment]
Something seems off with your OpenGL setup. Try updating it or re-installing it

**Comment by mkassner** [comment]
@Tobias-Fischer does this happen every time? Can you elaborate on when this happens (any correlation?)

**Comment by Tobias-Fischer** [comment]
I haven't seen this issue for some days now. Closing - will re-open if necessary.
Thanks for your support @papr @mkassner!
