### ISSUE TITLE
AccuracyVisualizer crashes when threshold being changed

### ISSUE THREAD

**Issue by Tobias-Fischer** [pupil-labs/pupil#821]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tobias/robot/pupil/pupil/pupil_src/launchables/world.py", line 462, in world
    p.on_notify(n)
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/accuracy_visualizer.py", line 104, in on_notify
    self.recalculate()
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/accuracy_visualizer.py", line 107, in recalculate
    if not (self.recent_input and self.recent_labels):
AttributeError: 'Accuracy_Visualizer' object has no attribute 'recent_input'
```

**Comment by mkassner** [comment]
thank for the report! just fixed it.
