### ISSUE TITLE
Pupil Capture 0.9.14 give error when trying to initialize Plugin Binocular_Vector_Gaze_Mapper from Unity 

### ISSUE THREAD

**Issue by Muzammilnxs** [pupil-labs/pupil#825]
After successful calibration in Unity, this error won't let gaze mapping to be done. Pupil Capture gets stuck in here. But there was no such problems in previous version that I used 
(0.9.6)
Process world:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 249, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "launchables\world.py", line 462, in world
  File "launchables\world.py", line 274, in handle_notifications
  File "shared_modules\plugin.py", line 277, in add
TypeError: __init__() got an unexpected keyword argument 'camera_intrinsics'
![issueci](https://user-images.githubusercontent.com/10149563/29999607-66dfcbb8-900c-11e7-839c-f9fc1e4b5dcc.png)

**Comment by mkassner** [comment]
Hi,

yes thats a bug. We will fix this tomorrow!

M
