### ISSUE TITLE
Can't find libboost_python-py36

### ISSUE THREAD

**Issue by petr-lee** [pupil-labs/pupil#874]
After finally installing the dependencies, I tried to run...
```python main.py```

And for some reason, I get the following error messages. I've already tried installing `libboost-python-dev` and `libboost-python1.63-dev`, and I still get the error message.
Abridged:
```
/usr/bin/ld: cannot find -lboost_python-py36
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
```

Full:
```
/usr/bin/ld: cannot find -lboost_python-py36
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/home/peter/ComputerScience/Academics/Berkeley/Research/BDD/Pupil/PupilSoftware/pupil_src/launchables/world.py", line 113, in world
    import pupil_detectors
  File "/home/peter/ComputerScience/Academics/Berkeley/Research/BDD/Pupil/PupilSoftware/pupil_src/shared_modules/pupil_detectors/__init__.py", line 16, in <module>
    build_cpp_extension()
  File "/home/peter/ComputerScience/Academics/Berkeley/Research/BDD/Pupil/PupilSoftware/pupil_src/shared_modules/pupil_detectors/build.py", line 25, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "/home/peter/.conda3/envs/pupilenv/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/peter/.conda3/envs/pupilenv/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/peter/.conda3/envs/pupilenv/bin/python', 'setup.py', 'install', '--install-lib=/home/peter/ComputerScience/Academics/Berkeley/Research/BDD/Pupil/PupilSoftware/pupil_src/shared_modules']' returned non-zero exit status 1.

world - [INFO] launchables.world: Process shutting down.
```

Also, when I run `ldconfig -p | grep libboost_python`, I get the following message:
```
libboost_python-py35.so.1.62.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.62.0
libboost_python-py35.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py35.so
libboost_python-py27.so.1.62.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.62.0
libboost_python-py27.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so
```

**Comment by HWiese1980** [comment]
@petr-lee  You found a solution for this issue? If so, please consider sharing it. I'm running into the same issue right now. Thanks!

**Comment by jicont21** [comment]
Same issue here!.
Did you find a solution?

**Comment by huangjiancong1** [comment]
i can not find libboost_python3.6 in `/usr/lib/x86_64-linux-gnu/` and `/usr/local/lib/`,  But i install boost after it
```
tar -xzvf boost_1_65_1.tar.gz
cd boost_1_65_1
echo "using mpi ;
using gcc :  : g++ ;
using python : 3.6 : /usr/bin/python3 : /usr/include/python3.6m : /usr/local/lib ;" > ~/user-config.jam

./bootstrap.sh --with-python=/usr/bin/python3 --with-python-version=3.6 --with-python-root=/usr/local/lib/python3.6 --prefix=/usr/local
sudo ./b2 install -a --with=all
sudo ldconfig
```

**Comment by huangjiancong1** [comment]
Did I not install this `libboost-python1.63-dev`?
My ldconfig:
```
:~$ ldconfig -p | grep libboost_python
	libboost_python35.so.1.68.0 (libc6,x86-64) => /usr/local/lib/libboost_python35.so.1.68.0
	libboost_python35.so (libc6,x86-64) => /usr/local/lib/libboost_python35.so
	libboost_python27.so.1.68.0 (libc6,x86-64) => /usr/local/lib/libboost_python27.so.1.68.0
	libboost_python27.so (libc6,x86-64) => /usr/local/lib/libboost_python27.so
	libboost_python-py35.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0
	libboost_python-py35.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py35.so
	libboost_python-py27.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
	libboost_python-py27.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so
```
