### ISSUE TITLE
Realsense backend crash when setting preset to "Best Quality"

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#879]
Assigned to @pointcontrols

System: MacBook, macOS High Sierra
Software: Current `Pupil` and `pyrealsense` master branches

Steps to reproduce the issue:
1. Connect RealSense camera
2. Select it as input source
3. Set `Preset` from `None` to `best Quality`
4. Crash

Is it possible that the preset changes the color stream to something else than YUV?

Crash log:
```
Traceback (most recent call last):
  File "/Users/testaccount/Desktop/pupil/pupil_src/launchables/world.py", line 436, in world
    p.recent_events(events)
  File "/Users/testaccount/Desktop/pupil/pupil_src/shared_modules/video_capture/realsense_backend.py", line 387, in recent_events
    color_frame, depth_frame = self.get_frames()
  File "/Users/testaccount/Desktop/pupil/pupil_src/shared_modules/video_capture/realsense_backend.py", line 358, in get_frames
    color = ColorFrame(self.device)
  File "/Users/testaccount/Desktop/pupil/pupil_src/shared_modules/video_capture/realsense_backend.py", line 53, in __init__
    self._yuv[:y_plane] = self._yuv422[:, :, 0].flatten()
ValueError: could not broadcast input array from shape (307200) into shape (460800)
```

**Comment by pointcontrols** [comment]
Please use https://github.com/pupil-labs/librealsense
