### ISSUE TITLE
ValueError: no container format 'alsa'

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#881]
When starting Audio Capture plugin (v0.9.14). 
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "shared_modules/audio_capture.py", line 158, in capture_thread
  File "av/container/core.pyx", line 288, in av.container.core.open (src/av/container/core.c:4987)
  File "av/container/core.pyx", line 250, in av.container.core.Container.__cinit__ (src/av/container/core.c:4323)
  File "av/format.pyx", line 49, in av.format.ContainerFormat.__cinit__ (src/av/format.c:1512)
ValueError: no container format 'alsa'
```

**Comment by papr** [comment]
We assume different audio backends depending on your operating system. `AVFoundation` for `macOS` and `alsa` on Linux. It seems like you do not have `alsa` installed. Either install `alsa` or modify [`audio_capture.py#L154`](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/audio_capture.py#L154) such that it uses your installed backend. See [this link for a list of supported backends](https://www.ffmpeg.org/ffmpeg-devices.html#Input-Devices).
