### ISSUE TITLE
Pupil Player 0.9.15 - offline surface detection plugin --> crash

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#894]
while offline calibration  and offline pupil detection was running.

user@boole:~$ pupil_player '/media/user/data/Pupil/SJ_1035' 
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [INFO] launchables.player: Session setting are from a  different version of this app. I will not use those.
player - [INFO] launchables.player: Starting new session with '/media/neitzel/data/Pupil/SJ_1035'
player - [INFO] player_methods: Updating meta info
player - [INFO] player_methods: Updating recording from v0.9.13 to v0.9.15
player - [INFO] player_methods: Updating meta info
player - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
player - [INFO] launchables.player: Application Version: 0.9.14.7
player - [INFO] launchables.player: System Info: User: neitzel, Platform: Linux, Machine: boole, Release: 4.10.0-37-generic, Version: #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017
player - [INFO] camera_models: Previously recorded calibration found and loaded!
player - [INFO] launchables.player: Session setting are a different version of this app. I will not use those.
player - [INFO] plugin: Loaded: Trim_Marks
player - [INFO] plugin: Loaded: Seek_Bar
player - [INFO] plugin: Loaded: Log_Display
player - [INFO] plugin: Loaded: Vis_Scan_Path
player - [INFO] plugin: Loaded: Vis_Polyline
player - [INFO] plugin: Loaded: Vis_Circle
player - [INFO] plugin: Loaded: Video_Export_Launcher
player - [INFO] plugin: Loaded: Pupil_From_Recording
player - [INFO] plugin: Loaded: Gaze_From_Recording
player - [INFO] plugin: Loaded: Offline_Pupil_Detection
eye1 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
eye0 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
eye1 - [INFO] launchables.eye: Session setting are from a different version of this app. I will not use those.
eye0 - [INFO] launchables.eye: Session setting are from a different version of this app. I will not use those.
eye1 - [INFO] camera_models: No user calibration found for camera eye1 at resolution (640, 480)
eye1 - [INFO] camera_models: No pre-recorded calibration available
eye1 - [WARNING] camera_models: Loading dummy calibration
eye0 - [INFO] camera_models: No user calibration found for camera eye0 at resolution (640, 480)
eye0 - [INFO] camera_models: No pre-recorded calibration available
eye0 - [WARNING] camera_models: Loading dummy calibration
eye1 - [WARNING] launchables.eye: Process started.
eye0 - [WARNING] launchables.eye: Process started.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
player - [INFO] plugin: Loaded: Offline_Calibration
circle_detector - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
circle_detector - [INFO] camera_models: Previously recorded calibration found and loaded!
circle_detector - [INFO] launchables.marker_detectors: Starting calibration marker detection...
player - [ERROR] gaze_producers: No pupil data to calibrate section "1"
player - [ERROR] gaze_producers: No pupil data to calibrate section "1"
player - [INFO] camera_models: No user calibration found for camera eye0 at resolution (640, 480)
player - [INFO] camera_models: No pre-recorded calibration available
player - [WARNING] camera_models: Loading dummy calibration
player - [INFO] camera_models: No user calibration found for camera eye1 at resolution (640, 480)
player - [INFO] camera_models: No pre-recorded calibration available
player - [WARNING] camera_models: Loading dummy calibration
player - [INFO] plugin: Loaded: Vis_Eye_Video_Overlay
Process player:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "launchables/player.py", line 507, in player
  File "pyglui/ui.pyx", line 178, in pyglui.ui.UI.update (pyglui/ui.cpp:9399)
  File "pyglui/ui.pyx", line 140, in pyglui.ui.UI.handle_input (pyglui/ui.cpp:8746)
  File "pyglui/menus.pxi", line 525, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.cpp:43442)
  File "pyglui/menus.pxi", line 542, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.cpp:43223)
  File "pyglui/ui_elements.pxi", line 416, in pyglui.ui.Selector.handle_input (pyglui/ui.cpp:20540)
  File "pyglui/ui_elements.pxi", line 427, in pyglui.ui.Selector.handle_input (pyglui/ui.cpp:20382)
  File "pyglui/ui_elements.pxi", line 446, in pyglui.ui.Selector.finish_selection (pyglui/ui.cpp:20836)
  File "pyglui/ui.pyx", line 342, in pyglui.ui.Synced_Value.value.__set__ (pyglui/ui.cpp:45675)
  File "launchables/player.py", line 262, in open_plugin
  File "shared_modules/plugin.py", line 277, in add
  File "shared_modules/offline_surface_tracker.py", line 63, in __init__
  File "shared_modules/offline_surface_tracker.py", line 290, in init_marker_cacher
  File "multiprocessing/process.py", line 105, in start
  File "multiprocessing/context.py", line 277, in _Popen
  File "multiprocessing/popen_fork.py", line 20, in __init__
  File "multiprocessing/popen_fork.py", line 67, in _launch
OSError: [Errno 12] Cannot allocate memory

**Comment by willpatera** [comment]
@fneitzel this will be addressed in v1.1 - please see comment on https://github.com/pupil-labs/pupil/issues/889#issuecomment-340471511 - I will close this issue and we can discuss this behavior in issue #889
