### ISSUE TITLE
Batch Exporter: AssertionError when starting export twice

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#913]
This is due to how the background process is implemented. The plugin does not test for running processes nor cancels them if necessary. The correct way to fix this issue is by implementing #914 

```
Traceback (most recent call last):
  File "/home/papr/work/pupil/pupil_src/launchables/player.py", line 441, in player
    p.recent_events(events)
  File "/home/papr/work/pupil/pupil_src/shared_modules/batch_exporter.py", line 190, in recent_events
    self.workers[i].start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 99, in start
    assert self._popen is None, 'cannot start a process twice'
AssertionError: cannot start a process twice
```

**Comment by papr** [comment]
A hot fix is not possible without a refactor. We decided to disable this plugin as well.
