### ISSUE TITLE
v0.4 offline marker detector crashing

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#93]
Trying to export data:
```bash
Traceback (most recent call last):
  File "<string>", line 469, in <module>
  File "<string>", line 432, in main
  File "pyglui/ui.pyx", line 130, in pyglui.ui.UI.update (pyglui/ui.c:7209)
  File "pyglui/ui.pyx", line 98, in pyglui.ui.UI.handle_input (pyglui/ui.c:6746)
  File "pyglui/menus.pxi", line 524, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.c:38053)
  File "pyglui/menus.pxi", line 540, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.c:37837)
  File "pyglui/ui_elements.pxi", line 752, in pyglui.ui.Button.handle_input (pyglui/ui.c:22512)
  File "pyglui/ui_elements.pxi", line 766, in pyglui.ui.Button.handle_input (pyglui/ui.c:22366)
  File "/home/mkassner/pupil/deploy_player/build/bundle/out00-PYZ.pyz/offline_marker_detector", line 507, in save_surface_statsics_to_file
KeyError: 0
```

And this:
```bash
Traceback (most recent call last):
  File "/home/rafael/cpicanco/pupil/pupil_src/player/main.py", line 470, in <module>
    main()
  File "/home/rafael/cpicanco/pupil/pupil_src/player/main.py", line 433, in main
    g_pool.gui.update()
  File "pyglui/ui.pyx", line 130, in pyglui.ui.UI.update (pyglui/ui.c:7248)
  File "pyglui/ui.pyx", line 98, in pyglui.ui.UI.handle_input (pyglui/ui.c:6785)
  File "pyglui/menus.pxi", line 529, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.c:38040)
  File "pyglui/menus.pxi", line 545, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.c:37828)
  File "pyglui/ui_elements.pxi", line 752, in pyglui.ui.Button.handle_input (pyglui/ui.c:22461)
  File "pyglui/ui_elements.pxi", line 766, in pyglui.ui.Button.handle_input (pyglui/ui.c:22315)
  File "/home/rafael/cpicanco/pupil/pupil_src/shared_modules/offline_marker_detector.py", line 507, in save_surface_statsics_to_file
    csv_writer.writerow( (idx,ts,gp['timestamp'],gp_x,gp_y,gp_x*s.real_world_size[0],gp_x*s.real_world_size[1],on_srf) )
KeyError: 0
```

After a click on (re)calculate with a surface defined:
```bash
Traceback (most recent call last):
  File "<string>", line 469, in <module>
  File "<string>", line 432, in main
  File "pyglui/ui.pyx", line 130, in pyglui.ui.UI.update (pyglui/ui.c:7209)
  File "pyglui/ui.pyx", line 98, in pyglui.ui.UI.handle_input (pyglui/ui.c:6746)
  File "pyglui/menus.pxi", line 524, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.c:38053)
  File "pyglui/menus.pxi", line 540, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.c:37837)
  File "pyglui/ui_elements.pxi", line 752, in pyglui.ui.Button.handle_input (pyglui/ui.c:22512)
  File "pyglui/ui_elements.pxi", line 766, in pyglui.ui.Button.handle_input (pyglui/ui.c:22366)
  File "/home/mkassner/pupil/deploy_player/build/bundle/out00-PYZ.pyz/offline_marker_detector", line 197, in recalculate
  File "/home/mkassner/pupil/deploy_player/build/bundle/out00-PYZ.pyz/offline_reference_surface", line 248, in generate_heatmap
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by mkassner** [comment]
Thats a bug. I'll fix it today. Thanks for spotting it!

**Comment by mkassner** [comment]
fixed.
