### ISSUE TITLE
Pupil Player - Crash when removing gaze mapping section in offline calibration

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#930]
## Overview

Pupil Player crashes in the latest macOS version when removing an existing calibration section in offline calibration. Mapping is complete when attempting to remove the section. 

@papr please migrate to PyGLUI if necessary. 

## Log

Relevant trace from the player.log. 

``` 
2017-11-14 07:59:33,491 - player - [ERROR] launchables.player: Process Player crashed with trace:
Traceback (most recent call last):
  File "launchables/player.py", line 458, in player
  File "pyglui/ui.pyx", line 186, in pyglui.ui.UI.update (pyglui/ui.cpp:11228)
  File "pyglui/ui.pyx", line 155, in pyglui.ui.UI.draw (pyglui/ui.cpp:10739)
  File "pyglui/menus.pxi", line 713, in pyglui.ui.Container.draw (pyglui/ui.cpp:61580)
  File "pyglui/menus.pxi", line 733, in pyglui.ui.Container.draw (pyglui/ui.cpp:61432)
  File "pyglui/menus.pxi", line 713, in pyglui.ui.Container.draw (pyglui/ui.cpp:61580)
  File "pyglui/menus.pxi", line 733, in pyglui.ui.Container.draw (pyglui/ui.cpp:61432)
  File "pyglui/menus.pxi", line 761, in pyglui.ui.Timeline_Menu.draw (pyglui/ui.cpp:63203)
  File "pyglui/menus.pxi", line 765, in pyglui.ui.Timeline_Menu.draw (pyglui/ui.cpp:63077)
  File "pyglui/menus.pxi", line 531, in pyglui.ui.Scrolling_Menu.draw (pyglui/ui.cpp:57971)
  File "pyglui/menus.pxi", line 541, in pyglui.ui.Scrolling_Menu.draw (pyglui/ui.cpp:57839)
  File "pyglui/menus.pxi", line 568, in pyglui.ui.Scrolling_Menu.draw_scroll_window_elements (pyglui/ui.cpp:58581)
  File "pyglui/timelines.pxi", line 20, in pyglui.ui.Timeline.draw (pyglui/ui.cpp:46114)
  File "pyglui/timelines.pxi", line 42, in pyglui.ui.Timeline.draw (pyglui/ui.cpp:45660)
  File "shared_modules/gaze_producers.py", line 483, in draw_sections
  File "shared_modules/gl_utils/utils.py", line 127, in __enter__
  File "site-packages/OpenGL/error.py", line 232, in glCheckError
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'invalid value',
	baseOperation = glMatrixMode,
	cArguments = (GL_PROJECTION,)
)
```

**Comment by papr** [comment]
Reproducable on Linux as well. The issue triggers only when removing the last section is being removed.
