### ISSUE TITLE
New offline fixation detector assertion error

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#938]
```
Traceback (most recent call last):
  File "launchables/player.py", line 441, in player
  File "shared_modules/fixation_detector.py", line 320, in recent_events
  File "shared_modules/fixation_detector.py", line 320, in <listcomp>
  File "shared_modules/background_helper.py", line 70, in fetch
AssertionError: Fixation too short: {'topic': 'fixation', 'norm_pos': [0.4197407306248098, 0.33525362523013036], 'dispersion': 0.98745282500599352, 'method': 'pupil', 'base_data': [{'topic': 'gaze', 'norm_pos': [0.42354963326512174, 0.3350629380203589], 'eye_center_3d': [-264.32769014933484, 34.169337017696385, -80.14390598700811], 'gaze_normal_3d': [0.42069652164070237, 0.03211472443444935, 0.9066328259852021], 'gaze_point_3d': [-53.979429328983684, 50.22669923492105, 373.172507005593], 'confidence': 1.0, 'timestamp': 161562.443785, 'base_data': [{'topic': 'pupil', 'circle_3d': {'center': [-4.380616921612269, 2.4798030598575735, 26.357180756041174], 'normal': [-0.38817429535947207, 0.18387538895996167, -0.90305623178017], 'radius': 2.2148412833407813}, 'confidence': 1.0, 'timestamp': 161562.443785, 'diameter_3d': 4.429682566681563, 'ellipse': {'center': [218.35701694054433, 297.6805823329097], 'axes': [85.67978021979883, 104.27307920020972], 'angle': -26.211189196466165}, 'norm_pos': [0.3411828389696005, 0.3798321201397715], 'diameter': 104.27307920020972, 'sphere': {'center': [0.2774746227013961, 0.2732983923380336, 37.193855537403216], 'radius': 12.0}, 'projected_sphere': {'center': [324.6253410298339, 244.55572569181976], 'axes': [400.0660804050347, 400.0660804050347], 'angle': 90.0}, 'model_confidence': 0.9714208240226063, 'model_id': 208, 'model_birth_timestamp': 161518.528585, 'theta': 1.7557239476489734, 'phi': -1.976763648595513, 'method': '3d c++', 'id': 0}], 'index': 62}, {'topic': 'gaze', 'norm_pos': [0.42349561206518216, 0.3346030853755173], 'eye_center_3d': [-264.32769014933484, 34.169337017696385, -80.14390598700811], 'gaze_normal_3d': [0.4206228797202318, 0.03243888701316495, 0.9066554536676029], 'gaze_point_3d': [-54.01625028921899, 50.38878052427885, 373.1838208467933], 'confidence': 1.0, 'timestamp': 161562.454985, 'base_data': [{'topic': 'pupil', 'circle_3d': {'center': [-4.381121063134778, 2.4758795234616313, 26.356599307308493], 'normal': [-0.3882163071530145, 0.18354842759363313, -0.9031046858412268], 'radius': 2.209363104264082}, 'confidence': 1.0, 'timestamp': 161562.454985, 'diameter_3d': 4.418726208528164, 'ellipse': {'center': [218.3363007727262, 297.5938654282715], 'axes': [85.47855025216676, 104.01709802531626], 'angle': -26.1694190530242}, 'norm_pos': [0.3411504699573847, 0.38001278035776775], 'diameter': 104.01709802531626, 'sphere': {'center': [0.2774746227013961, 0.2732983923380336, 37.193855537403216], 'radius': 12.0}, 'projected_sphere': {'center': [324.6253410298339, 244.55572569181976], 'axes': [400.0660804050347, 400.0660804050347], 'angle': 90.0}, 'model_confidence': 0.9715012789872413, 'model_id': 208, 'model_birth_timestamp': 161518.528585, 'theta': 1.7553913250880273, 'phi': -1.9767834471909258, 'method': '3d c++', 'id': 0}], 'index': 63}, {'topic': 'gaze', 'norm_pos': [0.42048760186435474, 0.3346705004315986], 'eye_center_3d': [-264.32769014933484, 34.169337017696385, -80.14390598700811], 'gaze_normal_3d': [0.41675744328708514, 0.03269738303507602, 0.9084294769587071], 'gaze_point_3d': [-55.948968505792294, 50.5180285352344, 374.07083249234546], 'confidence': 1.0, 'timestamp': 161562.466185, 'base_data': [{'topic': 'pupil', 'circle_3d': {'center': [-4.4276364836127176, 2.464230046540244, 26.37434778686972], 'normal': [-0.39209259219284276, 0.1825776378501842, -0.9016256458777913], 'radius': 2.2007309004254285}, 'confidence': 1.0, 'timestamp': 161562.466185, 'diameter_3d': 4.401461800850857, 'ellipse': {'center': [217.30881654691063, 297.29236243865796], 'axes': [84.81979986837338, 103.54129410625181], 'angle': -25.823536396360893}, 'norm_pos': [0.3395450258545479, 0.3806409115861292], 'diameter': 103.54129410625181, 'sphere': {'center': [0.2774746227013961, 0.2732983923380336, 37.193855537403216], 'radius': 12.0}, 'projected_sphere': {'center': [324.6253410298339, 244.55572569181976], 'axes': [400.0660804050347, 400.0660804050347], 'angle': 90.0}, 'model_confidence': 0.9715057594417265, 'model_id': 208, 'model_birth_timestamp': 161518.528585, 'theta': 1.754403848103169, 'phi': -1.9809996320401735, 'method': '3d c++', 'id': 0}], 'index': 63}, {'topic': 'gaze', 'norm_pos': [0.4114300753045807, 0.3366779770930467], 'eye_center_3d': [-264.32769014933484, 34.169337017696385, -80.14390598700811], 'gaze_normal_3d': [0.40500040985751834, 0.03221591072030457, 0.9137487636717787], 'gaze_point_3d': [-61.82748522057571, 50.277292377848674, 376.7304758488812], 'confidence': 0.99, 'timestamp': 161562.477385, 'base_data': [{'topic': 'pupil', 'circle_3d': {'center': [-4.569559393061392, 2.4433167989814777, 26.43294101470269], 'normal': [-0.4039195013135657, 0.180834867220287, -0.8967428768917106], 'radius': 2.2050645529501116}, 'confidence': 0.99, 'timestamp': 161562.477385, 'diameter_3d': 4.410129105900223, 'ellipse': {'center': [214.23698752860292, 296.68700739323674], 'axes': [83.91872956340136, 103.5182871534685], 'angle': -24.941768284586757}, 'norm_pos': [0.3347452930134421, 0.38190206793075676], 'diameter': 103.5182871534685, 'sphere': {'center': [0.2774746227013961, 0.2732983923380336, 37.193855537403216], 'radius': 12.0}, 'projected_sphere': {'center': [324.6253410298339, 244.55572569181976], 'axes': [400.0660804050347, 400.0660804050347], 'angle': 90.0}, 'model_confidence': 0.971505991774424, 'model_id': 208, 'model_birth_timestamp': 161518.528585, 'theta': 1.7526315739167841, 'phi': -1.9940074196592887, 'method': '3d c++', 'id': 0}], 'index': 63}], 'timestamp': 161562.443785, 'duration': 33.59999999520369, 'confidence': 0.9975, 'gaze_point_3d': [-56.44303333614267, 50.35270016807075, 374.2894090484033], 'start_frame_index': 63, 'end_frame_index': 64, 'mid_frame_index': 63}
```

**Comment by papr** [comment]
Which data set and fixation settings did you use to produce this error?

**Comment by genchukov** [comment]
Hi there got the same issue with pupilplayer v1.1.2 & v1.3.9
Settings are default
Not sure what you mean by data set.

AssertionError: Fixation too short: {'topic': 'fixation', 'norm_pos': [0.2773483218284252, -0.17424376662728322], 'dispersion': 0.71482469217712263, 'method': 'pupil',......

**Comment by papr** [comment]
@genchukov I meant the recording that he used when I said dataset. Do you have an example recording that triggers this issue consistently? Could you share it with me privately? This would help me to debug the issue. I added the assertion because this case should not occur in theory.

**Comment by genchukov** [comment]
I am sorry I am not allowed to share the recording. It is under a secrecy agreement. I will try some other recordings to reproduce the error which I could send to you but I am not sure if I ever had this error before. If there are other information which could help you let me know.

**Comment by papr** [comment]
@genchukov Yes, this is often the case for experiment recordings. Does the issue only appear for one single recording?

**Comment by genchukov** [comment]
Yes it is the only recording even the recordings which were made on same day with same settings (HW & SW) are working fine. The only difference I can recognize is the length of the recording the one with the issue has 61 min the others just 15 min.

**Comment by papr** [comment]
Ok, thank you very much! This helps a lot already! I will try to reproduce the issue with longer recordings.

**Comment by JohnTyCa** [comment]
Hi all, I am experiencing the same issue in Pupil Player 1.4.1 and 1.5.12 when trying to use the offline fixation detector:

AssertionError: Fixation too short: {'base_data': [{'gaze_normal_3d': [-0.3898261493839419, 0.2424969710970205, 0.888386623191311]...

 The recording is 19 minutes long, I'm happy to supply the recording if it helps with debugging.

**Comment by papr** [comment]
Yes, please, this would be very helpful :)

**Comment by JohnTyCa** [comment]
Can you advise on how I would supply you with this data (>7GB)? Thank you.

**Comment by papr** [comment]
We recommend Google Drive

**Comment by sotodea** [comment]
Hi Papr, 
I have this same issue and was wondering if you managed to solve it? 
Cheers
Vicente

**Comment by papr** [comment]
The fixes to the Fixation Detector—introduced in [v1.19](https://github.com/pupil-labs/pupil/releases/v1.19)—should have resolved this issue.
