### ISSUE TITLE
Pupil player 1.1 crash when loading video with annotations 

### ISSUE THREAD

**Issue by callummole** [pupil-labs/pupil#939]
Hi,

This issue may be related to #936 . I am sending annotations to pupil capture through pupil remote. However, when I drop the recordings with annotations into pupil player it crashes, with the following output:

eyetrike@eyetrike-ThinkPad-E570:~$ pupil_player
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [INFO] launchables.player: Starting new session with '/home/eyetrike/recordings/annotations3/001'
player - [INFO] player_methods: Updating meta info
player - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
player - [INFO] launchables.player: Application Version: 1.1.7
player - [INFO] launchables.player: System Info: User: eyetrike, Platform: Linux, Machine: eyetrike-ThinkPad-E570, Release: 4.13.0-16-generic, Version: #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017
player - [INFO] camera_models: Previously recorded calibration found and loaded!
player - [ERROR] launchables.player: Process Player crashed with trace:
Traceback (most recent call last):
  File "launchables/player.py", line 240, in player
  File "shared_modules/player_methods.py", line 48, in correlate_data
TypeError: '<' not supported between instances of 'str' and 'float'

player - [INFO] launchables.player: Process shutting down.

This error does not occur with recordings without annotations.

Thanks,
Callum

**Comment by callummole** [comment]
apologies, the bug was with my code rather than pupil player (I was passing timestamps as strings rather than floats).
