### ISSUE TITLE
getting the pupil headset with realsense to work on macos

### ISSUE THREAD

**Issue by laurentperrinet** [pupil-labs/pupil#960]
I am not able to use the headset because with no world camera, I cannot calibrate the device.

As I understood, the headset with the realsense world camera is not included in the bundle. So I installed everything from source.
I followed the instructions to install all dependencies for mac @ https://docs.pupil-labs.com/#macos-dependencies and got it to install most parts. the only "HACK" was to modify the source of ``pyglui`` to:
```

$ cd ~/science/pupil/pyglui
$ git d
 setup.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/setup.py b/setup.py
index bebf312..6676a77 100644
--- a/setup.py
+++ b/setup.py
@@ -23,7 +23,7 @@ if platform.system() == 'Darwin':
     for root, dirs, files in os.walk('/usr/local/Cellar/glew'):
         if 'glew.h' in files:
             glew_header = os.path.join(root,'glew.h')
-    includes += ['/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers/']
+    includes += ['/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers/']
     link_args = []
     libs = ['GLEW']
     libglew = [] #we are using the dylib

```
this was commented in https://github.com/pupil-labs/pyglui/issues/30 

but still, there is no way to get the camera to run reliably. I can get the example in https://github.com/papr/pyrealsense/blob/master/examples/show_jupyter.ipynb to work but get errors with the latest code.

In particular, I had a message suggesting to "Install pyrealsense to use the Intel RealSense backend" which I traced back to the intialization in ``pupil_src/shared_modules/video_capture/__init__.py``. changing this code to :

```
$ git d
 pupil_src/shared_modules/video_capture/__init__.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/pupil_src/shared_modules/video_capture/__init__.py b/pupil_src/shared_modules/video_capture/__init__.py
index 7a5f7772..d5d34ed0 100644
--- a/pupil_src/shared_modules/video_capture/__init__.py
+++ b/pupil_src/shared_modules/video_capture/__init__.py
@@ -42,7 +42,7 @@ except ImportError:
 else:
     source_classes.append(NDSI_Source)
     manager_classes.append(NDSI_Manager)
-
+from .realsense_backend import Realsense_Source, Realsense_Manager
 try:
     from .realsense_backend import Realsense_Source, Realsense_Manager
 except ImportError:

```

generates this error:

```
$ cd  ~/science/pupil/pupil/pupil_src && python3 main.py
MainProcess - [INFO] os_utils: Disabled idle sleep.
objc[86364]: Class CaptureDelegate is implemented in both /usr/local/lib/python3.6/site-packages/cv2/cv2.cpython-36m-darwin.so (0x114428dc0) and /usr/local/opt/opencv/lib/libopencv_videoio.3.3.dylib (0x116ca7618). One of the two will be used. Which one is undefined.
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/Users/laurentperrinet/science/pupil/pupil/pupil_src/launchables/world.py", line 118, in world
    from plugin_manager import Plugin_Manager
  File "/Users/laurentperrinet/science/pupil/pupil/pupil_src/shared_modules/plugin_manager.py", line 15, in <module>
    from video_capture import Base_Manager, Base_Source
  File "/Users/laurentperrinet/science/pupil/pupil/pupil_src/shared_modules/video_capture/__init__.py", line 45, in <module>
    from .realsense_backend import Realsense_Source, Realsense_Manager
  File "/Users/laurentperrinet/science/pupil/pupil/pupil_src/shared_modules/video_capture/realsense_backend.py", line 19, in <module>
    from pyrealsense.constants import rs_stream, rs_option, rs_preset
ImportError: cannot import name 'rs_preset'

```
any clue?

Thanks!

**Comment by papr** [comment]
Please follow the updated docs in the master branch: https://docs.pupil-labs.com/master/#intel-realsense-3d

Be aware that this tells you to install the custom Pupil Labs `librealsense` and `pyrealsense` forks instead of the official ones.

**Comment by laurentperrinet** [comment]
Thanks, acquisition with the realsense-3d now works!
