### ISSUE TITLE
Surface debug window crashes after some time.

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#97]
Surface debug window crashes after some time.

```bash
Player [WARNING] uvc_capture.file_capture : Reached end of video file.
Traceback (most recent call last):
  File "/home/rafael/cpicanco/pupil/pupil_src/player/main.py", line 473, in <module>
    main()
  File "/home/rafael/cpicanco/pupil/pupil_src/player/main.py", line 429, in main
    p.gl_display()
  File "/home/rafael/cpicanco/pupil/pupil_src/shared_modules/offline_marker_detector.py", line 309, in gl_display
    s.gl_display_in_window(self.g_pool.image_tex)
  File "/home/rafael/cpicanco/pupil/pupil_src/shared_modules/offline_reference_surface.py", line 203, in gl_display_in_window
    clear_gl_screen()
NameError: global name 'clear_gl_screen' is not defined
```

**Comment by willpatera** [comment]
Hi @cpicanco -- Yep, that's a bug. Missing imports, **fixed** here: https://github.com/pupil-labs/pupil/commit/1577da07cf341d892c8f39c6fc5d3f9f8ec81fee

Thanks for spotting the bug :-)
