### ISSUE TITLE
Crashing on offline marker recalculate click

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#99]
Maybe I forgot to click on something.

```bash
Traceback (most recent call last):
  File "/home/rafael/cpicanco/pupil/pupil_src/player/main.py", line 472, in <module>
    main()
  File "/home/rafael/cpicanco/pupil/pupil_src/player/main.py", line 435, in main
    g_pool.gui.update()
  File "pyglui/ui.pyx", line 130, in pyglui.ui.UI.update (pyglui/ui.c:7440)
  File "pyglui/ui.pyx", line 98, in pyglui.ui.UI.handle_input (pyglui/ui.c:6977)
  File "pyglui/menus.pxi", line 529, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.c:38426)
  File "pyglui/menus.pxi", line 545, in pyglui.ui.Scrolling_Menu.handle_input (pyglui/ui.c:38214)
  File "pyglui/ui_elements.pxi", line 759, in pyglui.ui.Button.handle_input (pyglui/ui.c:22844)
  File "pyglui/ui_elements.pxi", line 773, in pyglui.ui.Button.handle_input (pyglui/ui.c:22698)
  File "/home/rafael/cpicanco/pupil/pupil_src/shared_modules/offline_marker_detector.py", line 196, in recalculate
    s.generate_heatmap(section)
  File "/home/rafael/cpicanco/pupil/pupil_src/shared_modules/offline_reference_surface.py", line 247, in generate_heatmap
    for c_e in self.cache[section]:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by mkassner** [comment]
This is a bug I thought I had fixed. I ll fix it
Thanks for the report!

**Comment by willpatera** [comment]
I made a minor change here https://github.com/pupil-labs/pupil/commit/728e44b89b063fd6b6ed2862a5f8b24f44cdc666

@cpicanco -- do you still get a crash after this change? 
@mkassner -- please have a look and edit my quick fix if necessary.

**Comment by mkassner** [comment]
OK. I did a bit of revision but functionally nothing is changed.

**Comment by cpicanco** [comment]
No crash anymore.
